In [4]:
import pandas as pd
import numpy as np

In [5]:
df = pd.read_excel("C:\\Users\\DEEL\\OneDrive\\Desktop\\sakshi\\datasets\\smartphones.xlsx")

In [6]:
df.head()

,model,price,rating,sim,processor,ram,battery,display,camera,card,os
0,OnePlus 11 5G,"₹54,999",89.0,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC","Snapdragon 8 Gen2, Octa Core, 3.2 GHz Processor","12 GB RAM, 256 GB inbuilt",5000 mAh Battery with 100W Fast Charging,"6.7 inches, 1440 x 3216 px, 120 Hz Display wit...",50 MP + 48 MP + 32 MP Triple Rear & 16 MP Fron...,Memory Card Not Supported,Android v13
1,OnePlus Nord CE 2 Lite 5G,"₹19,989",81.0,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi","Snapdragon 695, Octa Core, 2.2 GHz Processor","6 GB RAM, 128 GB inbuilt",5000 mAh Battery with 33W Fast Charging,"6.59 inches, 1080 x 2412 px, 120 Hz Display wi...",64 MP + 2 MP + 2 MP Triple Rear & 16 MP Front ...,"Memory Card (Hybrid), upto 1 TB",Android v12
2,Samsung Galaxy A14 5G,"₹16,499",75.0,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi","Exynos 1330, Octa Core, 2.4 GHz Processor","4 GB RAM, 64 GB inbuilt",5000 mAh Battery with 15W Fast Charging,"6.6 inches, 1080 x 2408 px, 90 Hz Display with...",50 MP + 2 MP + 2 MP Triple Rear & 13 MP Front ...,"Memory Card Supported, upto 1 TB",Android v13
3,Motorola Moto G62 5G,"₹14,999",81.0,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi","Snapdragon 695, Octa Core, 2.2 GHz Processor","6 GB RAM, 128 GB inbuilt",5000 mAh Battery with Fast Charging,"6.55 inches, 1080 x 2400 px, 120 Hz Display wi...",50 MP + 8 MP + 2 MP Triple Rear & 16 MP Front ...,"Memory Card (Hybrid), upto 1 TB",Android v12
4,Realme 10 Pro Plus,"₹24,999",82.0,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi","Dimensity 1080, Octa Core, 2.6 GHz Processor","6 GB RAM, 128 GB inbuilt",5000 mAh Battery with 67W Fast Charging,"6.7 inches, 1080 x 2412 px, 120 Hz Display wit...",108 MP + 8 MP + 2 MP Triple Rear & 16 MP Front...,Memory Card Not Supported,Android v13

Data Assessing
Quality Issues
model - some brands are written diiferently like OPPO in model column #consistency
price - has unneccesary '₹'# validity
price - has ',' between numbers # validity
price - phone Namotel has a price of 99  # accuracy
ratings - missing values completeness
processor - has some incorrect values for some samsung phones(row # -642,647,649,659,667,701,750,759,819,859,883,884,919,927,929,932,1002) validity
There is ipod on row 756 validity
memory - incorrect values in rows (441,485,534,553,584,610,613,642,647,649,659,667,701,750,759,819,859,884,919,927,929,932,990,1002) validity
battery - incorrect values in rows(113,151,309,365,378,441,450,553,584,610,613,630,642,647,649,659,667,701,750,756,759,764,819,855,859,884,915,916,927,929,932,990,1002) validity
display - sometimes frequency is not available completeness
display - incorrect values in rows(378,441,450,553,584,610,613,630,642,647,649,659,667,701,750,759,764,819,859,884,915,916,927,929,932,990,1002) validity
certain phones are foldable and the info is scattered validity
camera - words like Dual, Triple and Quad are used to represent number of cameras and front and rear cameras are separated by '&'
camera - problem with rows (100,113,151,157,161,238,273,308,309,323,324,365,367,378,394,441,450,484,506,534,553,571,572,575,584,610,613,615,630,642,647,649,659,667,684,687,705,711,723,728,750,756,759,764,792,819,846,854,855,858,883,884,896,915,916,927,929,932,945,956,990,995,1002,1016 ) validity
card - sometimes contains info about os and camera validity
os - sometimes contains info about bluetooth and fm radio validity
os - issue with rows (324,378) validity
os - sometimes contains os version name like lollipop consistency
missing values in camera, card and os completeness
datatype of price and rating is incorrect validity
Tidiness Issues
sim - can be split into 3 cols has_5g, has_NFC, has_IR_Blaster
ram - can be split into 2 cols RAM and ROM
processor - can be split into processor name, cores and cpu speed.
battery - can be split into battery capacity, fast_charging_available
display - can be split into size, resolution_width, resolution_height and frequency
camera - can be split into front and rear camera
card - can be split into supported, extended_upto
[ ]

##programatic assesment

In [7]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1020 entries, 0 to 1019
Data columns (total 11 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   model      1020 non-null   object
 1   price      1020 non-null   object
 2   rating     879 non-null    float64
 3   sim        1020 non-null   object
 4   processor  1020 non-null   object
 5   ram        1020 non-null   object
 6   battery    1020 non-null   object
 7   display    1020 non-null   object
 8   camera     1019 non-null   object
 9   card       1013 non-null   object
 10  os         1003 non-null   object
dtypes: float64(1), object(10)
memory usage: 87.8+ KB

In [8]:
df.describe()

           rating
count  879.000000
mean    78.258248
std      7.402854
min     60.000000
25%     74.000000
50%     80.000000
75%     84.000000
max     89.000000

In [9]:
df.duplicated()

0       False
1       False
2       False
3       False
4       False
        ...
1015    False
1016    False
1017    False
1018    False
1019    False
Length: 1020, dtype: bool

##cleaning (basics)

In [10]:
# handling price column
df1 = df.copy()

In [11]:
df1['price'] = df1['price'].str.replace('₹','').str.replace(',','').astype('int')

In [12]:
df1.head()

,model,price,rating,sim,processor,ram,battery,display,camera,card,os
0,OnePlus 11 5G,54999,89.0,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC","Snapdragon 8 Gen2, Octa Core, 3.2 GHz Processor","12 GB RAM, 256 GB inbuilt",5000 mAh Battery with 100W Fast Charging,"6.7 inches, 1440 x 3216 px, 120 Hz Display wit...",50 MP + 48 MP + 32 MP Triple Rear & 16 MP Fron...,Memory Card Not Supported,Android v13
1,OnePlus Nord CE 2 Lite 5G,19989,81.0,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi","Snapdragon 695, Octa Core, 2.2 GHz Processor","6 GB RAM, 128 GB inbuilt",5000 mAh Battery with 33W Fast Charging,"6.59 inches, 1080 x 2412 px, 120 Hz Display wi...",64 MP + 2 MP + 2 MP Triple Rear & 16 MP Front ...,"Memory Card (Hybrid), upto 1 TB",Android v12
2,Samsung Galaxy A14 5G,16499,75.0,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi","Exynos 1330, Octa Core, 2.4 GHz Processor","4 GB RAM, 64 GB inbuilt",5000 mAh Battery with 15W Fast Charging,"6.6 inches, 1080 x 2408 px, 90 Hz Display with...",50 MP + 2 MP + 2 MP Triple Rear & 13 MP Front ...,"Memory Card Supported, upto 1 TB",Android v13
3,Motorola Moto G62 5G,14999,81.0,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi","Snapdragon 695, Octa Core, 2.2 GHz Processor","6 GB RAM, 128 GB inbuilt",5000 mAh Battery with Fast Charging,"6.55 inches, 1080 x 2400 px, 120 Hz Display wi...",50 MP + 8 MP + 2 MP Triple Rear & 16 MP Front ...,"Memory Card (Hybrid), upto 1 TB",Android v12
4,Realme 10 Pro Plus,24999,82.0,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi","Dimensity 1080, Octa Core, 2.6 GHz Processor","6 GB RAM, 128 GB inbuilt",5000 mAh Battery with 67W Fast Charging,"6.7 inches, 1080 x 2412 px, 120 Hz Display wit...",108 MP + 8 MP + 2 MP Triple Rear & 16 MP Front...,Memory Card Not Supported,Android v13

In [13]:
df1 = df1.reset_index()

In [14]:
df1

,index,model,price,rating,sim,processor,ram,battery,display,camera,card,os
0,0,OnePlus 11 5G,54999,89.0,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC","Snapdragon 8 Gen2, Octa Core, 3.2 GHz Processor","12 GB RAM, 256 GB inbuilt",5000 mAh Battery with 100W Fast Charging,"6.7 inches, 1440 x 3216 px, 120 Hz Display wit...",50 MP + 48 MP + 32 MP Triple Rear & 16 MP Fron...,Memory Card Not Supported,Android v13
1,1,OnePlus Nord CE 2 Lite 5G,19989,81.0,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi","Snapdragon 695, Octa Core, 2.2 GHz Processor","6 GB RAM, 128 GB inbuilt",5000 mAh Battery with 33W Fast Charging,"6.59 inches, 1080 x 2412 px, 120 Hz Display wi...",64 MP + 2 MP + 2 MP Triple Rear & 16 MP Front ...,"Memory Card (Hybrid), upto 1 TB",Android v12
2,2,Samsung Galaxy A14 5G,16499,75.0,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi","Exynos 1330, Octa Core, 2.4 GHz Processor","4 GB RAM, 64 GB inbuilt",5000 mAh Battery with 15W Fast Charging,"6.6 inches, 1080 x 2408 px, 90 Hz Display with...",50 MP + 2 MP + 2 MP Triple Rear & 13 MP Front ...,"Memory Card Supported, upto 1 TB",Android v13
3,3,Motorola Moto G62 5G,14999,81.0,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi","Snapdragon 695, Octa Core, 2.2 GHz Processor","6 GB RAM, 128 GB inbuilt",5000 mAh Battery with Fast Charging,"6.55 inches, 1080 x 2400 px, 120 Hz Display wi...",50 MP + 8 MP + 2 MP Triple Rear & 16 MP Front ...,"Memory Card (Hybrid), upto 1 TB",Android v12
4,4,Realme 10 Pro Plus,24999,82.0,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi","Dimensity 1080, Octa Core, 2.6 GHz Processor","6 GB RAM, 128 GB inbuilt",5000 mAh Battery with 67W Fast Charging,"6.7 inches, 1080 x 2412 px, 120 Hz Display wit...",108 MP + 8 MP + 2 MP Triple Rear & 16 MP Front...,Memory Card Not Supported,Android v13
...,...,...,...,...,...,...,...,...,...,...,...,...
1015,1015,Motorola Moto Edge S30 Pro,34990,83.0,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi","Snapdragon 8 Gen1, Octa Core, 3 GHz Processor","8 GB RAM, 128 GB inbuilt",5000 mAh Battery with 68.2W Fast Charging,"6.67 inches, 1080 x 2460 px, 120 Hz Display wi...",64 MP + 8 MP + 2 MP Triple Rear & 16 MP Front ...,Android v12,No FM Radio
1016,1016,Honor X8 5G,14990,75.0,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi","Snapdragon 480+, Octa Core, 2.2 GHz Processor","6 GB RAM, 128 GB inbuilt",5000 mAh Battery with 22.5W Fast Charging,"6.5 inches, 720 x 1600 px Display with Water D...",48 MP + 2 MP + Depth Sensor Triple Rear & 8 MP...,"Memory Card Supported, upto 1 TB",Android v11
1017,1017,POCO X4 GT 5G (8GB RAM + 256GB),28990,85.0,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC, IR Bl...","Dimensity 8100, Octa Core, 2.85 GHz Processor","8 GB RAM, 256 GB inbuilt",5080 mAh Battery with 67W Fast Charging,"6.6 inches, 1080 x 2460 px, 144 Hz Display wit...",64 MP + 8 MP + 2 MP Triple Rear & 16 MP Front ...,Memory Card Not Supported,Android v12
1018,1018,Motorola Moto G91 5G,19990,80.0,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC","Snapdragon 695, Octa Core, 2.2 GHz Processor","6 GB RAM, 128 GB inbuilt",5000 mAh Battery with Fast Charging,"6.8 inches, 1080 x 2400 px Display with Punch ...",108 MP + 8 MP + 2 MP Triple Rear & 32 MP Front...,"Memory Card Supported, upto 1 TB",Android v12
1019,1019,Samsung Galaxy M52s 5G,24990,74.0,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi",Octa Core Processor,"8 GB RAM, 128 GB inbuilt",5000 mAh Battery with Fast Charging,"6.5 inches, 1080 x 2400 px Display with Water ...",64 MP + 8 MP + 5 MP Triple Rear & 32 MP Front ...,"Memory Card Supported, upto 1 TB",Android v12

In [15]:
df1['index'] = df1['index'] + 2

In [16]:
df1

,index,model,price,rating,sim,processor,ram,battery,display,camera,card,os
0,2,OnePlus 11 5G,54999,89.0,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC","Snapdragon 8 Gen2, Octa Core, 3.2 GHz Processor","12 GB RAM, 256 GB inbuilt",5000 mAh Battery with 100W Fast Charging,"6.7 inches, 1440 x 3216 px, 120 Hz Display wit...",50 MP + 48 MP + 32 MP Triple Rear & 16 MP Fron...,Memory Card Not Supported,Android v13
1,3,OnePlus Nord CE 2 Lite 5G,19989,81.0,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi","Snapdragon 695, Octa Core, 2.2 GHz Processor","6 GB RAM, 128 GB inbuilt",5000 mAh Battery with 33W Fast Charging,"6.59 inches, 1080 x 2412 px, 120 Hz Display wi...",64 MP + 2 MP + 2 MP Triple Rear & 16 MP Front ...,"Memory Card (Hybrid), upto 1 TB",Android v12
2,4,Samsung Galaxy A14 5G,16499,75.0,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi","Exynos 1330, Octa Core, 2.4 GHz Processor","4 GB RAM, 64 GB inbuilt",5000 mAh Battery with 15W Fast Charging,"6.6 inches, 1080 x 2408 px, 90 Hz Display with...",50 MP + 2 MP + 2 MP Triple Rear & 13 MP Front ...,"Memory Card Supported, upto 1 TB",Android v13
3,5,Motorola Moto G62 5G,14999,81.0,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi","Snapdragon 695, Octa Core, 2.2 GHz Processor","6 GB RAM, 128 GB inbuilt",5000 mAh Battery with Fast Charging,"6.55 inches, 1080 x 2400 px, 120 Hz Display wi...",50 MP + 8 MP + 2 MP Triple Rear & 16 MP Front ...,"Memory Card (Hybrid), upto 1 TB",Android v12
4,6,Realme 10 Pro Plus,24999,82.0,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi","Dimensity 1080, Octa Core, 2.6 GHz Processor","6 GB RAM, 128 GB inbuilt",5000 mAh Battery with 67W Fast Charging,"6.7 inches, 1080 x 2412 px, 120 Hz Display wit...",108 MP + 8 MP + 2 MP Triple Rear & 16 MP Front...,Memory Card Not Supported,Android v13
...,...,...,...,...,...,...,...,...,...,...,...,...
1015,1017,Motorola Moto Edge S30 Pro,34990,83.0,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi","Snapdragon 8 Gen1, Octa Core, 3 GHz Processor","8 GB RAM, 128 GB inbuilt",5000 mAh Battery with 68.2W Fast Charging,"6.67 inches, 1080 x 2460 px, 120 Hz Display wi...",64 MP + 8 MP + 2 MP Triple Rear & 16 MP Front ...,Android v12,No FM Radio
1016,1018,Honor X8 5G,14990,75.0,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi","Snapdragon 480+, Octa Core, 2.2 GHz Processor","6 GB RAM, 128 GB inbuilt",5000 mAh Battery with 22.5W Fast Charging,"6.5 inches, 720 x 1600 px Display with Water D...",48 MP + 2 MP + Depth Sensor Triple Rear & 8 MP...,"Memory Card Supported, upto 1 TB",Android v11
1017,1019,POCO X4 GT 5G (8GB RAM + 256GB),28990,85.0,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC, IR Bl...","Dimensity 8100, Octa Core, 2.85 GHz Processor","8 GB RAM, 256 GB inbuilt",5080 mAh Battery with 67W Fast Charging,"6.6 inches, 1080 x 2460 px, 144 Hz Display wit...",64 MP + 8 MP + 2 MP Triple Rear & 16 MP Front ...,Memory Card Not Supported,Android v12
1018,1020,Motorola Moto G91 5G,19990,80.0,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC","Snapdragon 695, Octa Core, 2.2 GHz Processor","6 GB RAM, 128 GB inbuilt",5000 mAh Battery with Fast Charging,"6.8 inches, 1080 x 2400 px Display with Punch ...",108 MP + 8 MP + 2 MP Triple Rear & 32 MP Front...,"Memory Card Supported, upto 1 TB",Android v12
1019,1021,Samsung Galaxy M52s 5G,24990,74.0,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi",Octa Core Processor,"8 GB RAM, 128 GB inbuilt",5000 mAh Battery with Fast Charging,"6.5 inches, 1080 x 2400 px Display with Water ...",64 MP + 8 MP + 5 MP Triple Rear & 32 MP Front ...,"Memory Card Supported, upto 1 TB",Android v12

In [17]:
processor_rows = set((642,647,649,659,667,701,750,759,819,859,883,884,919,927,929,932,1002))
ram_rows = set((441,485,534,553,584,610,613,642,647,649,659,667,701,750,759,819,859,884,919,927,929,932,990,1002))
battery_rows = set((113,151,309,365,378,441,450,553,584,610,613,630,642,647,649,659,667,701,750,756,759,764,819,855,859,884,915,916,927,929,932,990,1002))
display_rows = set((378,441,450,553,584,610,613,630,642,647,649,659,667,701,750,759,764,819,859,884,915,916,927,929,932,990,1002))
camera_rows = set((100,113,151,157,161,238,273,308,309,323,324,365,367,378,394,441,450,484,506,534,553,571,572,575,584,610,613,615,630,642,647,649,659,667,684,687,705,711,723,728,750,756,759,764,792,819,846,854,855,858,883,884,896,915,916,927,929,932,945,956,990,995,1002,1016 ))

In [18]:
df1[df1['index'].isin(processor_rows | ram_rows | battery_rows | display_rows | camera_rows)]

,index,model,price,rating,sim,processor,ram,battery,display,camera,card,os
98,100,Vivo X Fold 5G,106990,NaN,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC","Snapdragon 8 Gen1, Octa Core, 3 GHz Processor","12 GB RAM, 256 GB inbuilt",4600 mAh Battery with 66W Fast Charging,"8.03 inches, 1916 x 2160 px, 120 Hz Display",Foldable Display,50 MP Quad Rear & 16 MP Front Camera,Android v12
111,113,Apple iPhone 12,51999,74.0,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC","Bionic A14, Hexa Core, 3.1 GHz Processor","4 GB RAM, 64 GB inbuilt","6.1 inches, 1170 x 2532 px Display with Large ...",12 MP + 12 MP Dual Rear & 12 MP Front Camera,Memory Card Not Supported,iOS v14,No FM Radio
149,151,Apple iPhone 12 Mini,40999,74.0,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC","Bionic A14, Hexa Core, 3.1 GHz Processor","4 GB RAM, 64 GB inbuilt","5.4 inches, 1080 x 2340 px Display",12 MP + 12 MP Dual Rear & 12 MP Front Camera,Memory Card Not Supported,iOS v14,No FM Radio
155,157,Nokia 2780 Flip,4990,NaN,"Dual Sim, 3G, 4G, Wi-Fi","Snapdragon QM215, Quad Core, 1.3 GHz Processor","4 GB RAM, 512 MB inbuilt",1450 mAh Battery,"2.7 inches, 240 x 320 px Display",Dual Display,5 MP Rear Camera,"Memory Card Supported, upto 32 GB"
159,161,Oppo Find N2 5G,94990,NaN,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC","Snapdragon 8+ Gen1, Octa Core, 3.2 GHz Processor","12 GB RAM, 256 GB inbuilt",4520 mAh Battery with 67W Fast Charging,"7.1 inches, 1792 x 1920 px, 120 Hz Display wit...","Foldable Display, Dual Display",50 MP + 48 MP + 32 MP Triple Rear & 32 MP + 32...,Memory Card Not Supported
...,...,...,...,...,...,...,...,...,...,...,...,...
954,956,Vivo X Fold 5G (12GB RAM + 512GB),118990,NaN,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC","Snapdragon 8 Gen1, Octa Core, 3 GHz Processor","12 GB RAM, 512 GB inbuilt",4600 mAh Battery with 66W Fast Charging,"8.03 inches, 1916 x 2160 px, 120 Hz Display",Foldable Display,50 MP Quad Rear & 16 MP Front Camera,Android v12
988,990,Nokia 5310 Dual Sim,3399,NaN,Dual Sim,"8 MB RAM, 16 MB inbuilt",1200 mAh Battery,"2.4 inches, 240 x 320 px Display",0.3 MP Rear Camera,"Memory Card Supported, upto 32 GB",Bluetooth,Browser
993,995,Huawei Mate X,169000,NaN,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC, IR Bl...","Kirin 990, Octa Core, 2.86 GHz Processor","8 GB RAM, 512 GB inbuilt",4500 mAh Battery with 55W Fast Charging,"8 inches, 2200 x 2480 px Display",Foldable Display,48 MP Quad Rear Camera,"Memory Card (Hybrid), upto 256 GB"
1000,1002,XTouch F40 Flip,1999,NaN,Dual Sim,No 3G,No Wifi,"32 MB RAM, 32 MB inbuilt",800 mAh Battery,"1.77 inches, 240 x 320 px Display",Dual Display,1.3 MP Rear Camera
1014,1016,Vivo X Fold 2,119990,NaN,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC","Snapdragon 8 Gen2, Octa Core, 3.2 GHz Processor","12 GB RAM, 256 GB inbuilt",4800 mAh Battery with 66W Fast Charging,"8.03 inches, 1916 x 2160 px, 120 Hz Display",Foldable Display,50 MP + 50 MP + 10 MP Triple Rear & 32 MP Fron...,Android v12

In [19]:
df1[df1['index'].isin(processor_rows & ram_rows & battery_rows & display_rows & camera_rows)]# common problematic rows

,index,model,price,rating,sim,processor,ram,battery,display,camera,card,os
640,642,Nokia 105 Plus,1299,NaN,Dual Sim,"4 MB RAM, 4 MB inbuilt",800 mAh Battery,"1.77 inches, 128 x 160 px Display",No Rear Camera,"Memory Card Supported, upto 32 GB",Bluetooth,NaN
645,647,Nokia 2760 Flip,5490,NaN,"Dual Sim, 3G, 4G, Wi-Fi",1450 mAh Battery,"3.6 inches, 240 x 320 px Display",5 MP Rear & 5 MP Front Camera,"Memory Card Supported, upto 32 GB",Kaios v3.0,Bluetooth,NaN
647,649,Motorola Moto A10,1339,NaN,Dual Sim,"4 MB RAM, 4 MB inbuilt",1750 mAh Battery,"1.8 inches, 160 x 128 px Display",No Rear Camera,"Memory Card Supported, upto 32 GB",NaN,NaN
657,659,Zanco Tiny T1,2799,NaN,Single Sim,"32 MB RAM, 32 MB inbuilt",200 mAh Battery,"0.49 inches, 64 x 32 px Display",No Rear Camera,No FM Radio,Bluetooth,NaN
665,667,itel it2163S,958,NaN,Dual Sim,"4 MB RAM, 4 MB inbuilt",1200 mAh Battery,"1.8 inches, 160 x 128 px Display",No Rear Camera,"Memory Card Supported, upto 32 GB",Bluetooth,NaN
748,750,Nokia 400 4G,3290,NaN,"Dual Sim, 4G, VoLTE, Wi-Fi",2000 mAh Battery,"2.4 inches, 240 x 320 px Display",0.3 MP Rear & 0.3 MP Front Camera,"Memory Card Supported, upto 64 GB",Bluetooth,Browser,NaN
757,759,Karbonn KU3i,995,NaN,Dual Sim,"52 MB RAM, 32 MB inbuilt",1000 mAh Battery,"1.8 inches, 128 x 160 px Display",No Rear Camera,"Memory Card Supported, upto 16 GB",Bluetooth,NaN
817,819,itel Magic X,2239,NaN,"Dual Sim, 3G, 4G, VoLTE, Wi-Fi",No 3G,T117,"48 MB RAM, 128 MB inbuilt",1200 mAh Battery,"2.4 inches, 240 x 320 px Display",1.3 MP Rear Camera,"Memory Card Supported, upto 64 GB"
882,884,Nokia 5710 XpressAudio,4799,NaN,"Dual Sim, 3G, 4G",No Wifi,Unisoc T107,"48 MB RAM, 128 MB inbuilt",1450 mAh Battery,"2.4 inches, 240 x 320 px Display",0.3 MP Rear Camera,"Memory Card Supported, upto 32 GB"
925,927,Nokia 3310 4G,3999,NaN,"Dual Sim, 3G, 4G, VoLTE, Wi-Fi","256 MB RAM, 512 MB inbuilt",1200 mAh Battery,"2.4 inches, 240 x 320 px Display",2 MP Rear Camera,"Memory Card Supported, upto 32 GB",Bluetooth,Browser
927,929,Samsung Guru E1200,1685,NaN,Single Sim,No Wifi,800 mAh Battery,"1.5 inches, 128 x 128 px Display",No Rear Camera,No FM Radio,NaN,NaN
930,932,iKall K88 Pro 4G,2099,NaN,"Dual Sim, 3G, 4G, VoLTE","48 MB RAM, 128 MB inbuilt",1800 mAh Battery,"2.4 inches, 240 x 360 px Display",0.3 MP Rear Camera,"Memory Card Supported, upto 128 GB",Bluetooth,Browser
1000,1002,XTouch F40 Flip,1999,NaN,Dual Sim,No 3G,No Wifi,"32 MB RAM, 32 MB inbuilt",800 mAh Battery,"1.77 inches, 240 x 320 px Display",Dual Display,1.3 MP Rear Camera

In [20]:
df1[df1['index'].isin(processor_rows & ram_rows & battery_rows & display_rows & camera_rows)]['price'].mean() # means problem saste phone me hai(2537 price of phone)

2537.6923076923076

In [21]:
df1 = df1[df1['price'] >= 3400]

In [22]:
df1

,index,model,price,rating,sim,processor,ram,battery,display,camera,card,os
0,2,OnePlus 11 5G,54999,89.0,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC","Snapdragon 8 Gen2, Octa Core, 3.2 GHz Processor","12 GB RAM, 256 GB inbuilt",5000 mAh Battery with 100W Fast Charging,"6.7 inches, 1440 x 3216 px, 120 Hz Display wit...",50 MP + 48 MP + 32 MP Triple Rear & 16 MP Fron...,Memory Card Not Supported,Android v13
1,3,OnePlus Nord CE 2 Lite 5G,19989,81.0,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi","Snapdragon 695, Octa Core, 2.2 GHz Processor","6 GB RAM, 128 GB inbuilt",5000 mAh Battery with 33W Fast Charging,"6.59 inches, 1080 x 2412 px, 120 Hz Display wi...",64 MP + 2 MP + 2 MP Triple Rear & 16 MP Front ...,"Memory Card (Hybrid), upto 1 TB",Android v12
2,4,Samsung Galaxy A14 5G,16499,75.0,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi","Exynos 1330, Octa Core, 2.4 GHz Processor","4 GB RAM, 64 GB inbuilt",5000 mAh Battery with 15W Fast Charging,"6.6 inches, 1080 x 2408 px, 90 Hz Display with...",50 MP + 2 MP + 2 MP Triple Rear & 13 MP Front ...,"Memory Card Supported, upto 1 TB",Android v13
3,5,Motorola Moto G62 5G,14999,81.0,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi","Snapdragon 695, Octa Core, 2.2 GHz Processor","6 GB RAM, 128 GB inbuilt",5000 mAh Battery with Fast Charging,"6.55 inches, 1080 x 2400 px, 120 Hz Display wi...",50 MP + 8 MP + 2 MP Triple Rear & 16 MP Front ...,"Memory Card (Hybrid), upto 1 TB",Android v12
4,6,Realme 10 Pro Plus,24999,82.0,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi","Dimensity 1080, Octa Core, 2.6 GHz Processor","6 GB RAM, 128 GB inbuilt",5000 mAh Battery with 67W Fast Charging,"6.7 inches, 1080 x 2412 px, 120 Hz Display wit...",108 MP + 8 MP + 2 MP Triple Rear & 16 MP Front...,Memory Card Not Supported,Android v13
...,...,...,...,...,...,...,...,...,...,...,...,...
1015,1017,Motorola Moto Edge S30 Pro,34990,83.0,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi","Snapdragon 8 Gen1, Octa Core, 3 GHz Processor","8 GB RAM, 128 GB inbuilt",5000 mAh Battery with 68.2W Fast Charging,"6.67 inches, 1080 x 2460 px, 120 Hz Display wi...",64 MP + 8 MP + 2 MP Triple Rear & 16 MP Front ...,Android v12,No FM Radio
1016,1018,Honor X8 5G,14990,75.0,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi","Snapdragon 480+, Octa Core, 2.2 GHz Processor","6 GB RAM, 128 GB inbuilt",5000 mAh Battery with 22.5W Fast Charging,"6.5 inches, 720 x 1600 px Display with Water D...",48 MP + 2 MP + Depth Sensor Triple Rear & 8 MP...,"Memory Card Supported, upto 1 TB",Android v11
1017,1019,POCO X4 GT 5G (8GB RAM + 256GB),28990,85.0,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC, IR Bl...","Dimensity 8100, Octa Core, 2.85 GHz Processor","8 GB RAM, 256 GB inbuilt",5080 mAh Battery with 67W Fast Charging,"6.6 inches, 1080 x 2460 px, 144 Hz Display wit...",64 MP + 8 MP + 2 MP Triple Rear & 16 MP Front ...,Memory Card Not Supported,Android v12
1018,1020,Motorola Moto G91 5G,19990,80.0,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC","Snapdragon 695, Octa Core, 2.2 GHz Processor","6 GB RAM, 128 GB inbuilt",5000 mAh Battery with Fast Charging,"6.8 inches, 1080 x 2400 px Display with Punch ...",108 MP + 8 MP + 2 MP Triple Rear & 32 MP Front...,"Memory Card Supported, upto 1 TB",Android v12
1019,1021,Samsung Galaxy M52s 5G,24990,74.0,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi",Octa Core Processor,"8 GB RAM, 128 GB inbuilt",5000 mAh Battery with Fast Charging,"6.5 inches, 1080 x 2400 px Display with Water ...",64 MP + 8 MP + 5 MP Triple Rear & 32 MP Front ...,"Memory Card Supported, upto 1 TB",Android v12

In [23]:
#handling processor coloumn
df1[df1['index'].isin(processor_rows)]

,index,model,price,rating,sim,processor,ram,battery,display,camera,card,os
645,647,Nokia 2760 Flip,5490,NaN,"Dual Sim, 3G, 4G, Wi-Fi",1450 mAh Battery,"3.6 inches, 240 x 320 px Display",5 MP Rear & 5 MP Front Camera,"Memory Card Supported, upto 32 GB",Kaios v3.0,Bluetooth,NaN
857,859,LG Folder 2,11999,NaN,"Single Sim, 3G, 4G, Wi-Fi","1 GB RAM, 8 GB inbuilt",1470 mAh Battery,"2.8 inches, 240 x 320 px Display",2 MP Rear Camera,Memory Card Supported,Bluetooth,NaN
882,884,Nokia 5710 XpressAudio,4799,NaN,"Dual Sim, 3G, 4G",No Wifi,Unisoc T107,"48 MB RAM, 128 MB inbuilt",1450 mAh Battery,"2.4 inches, 240 x 320 px Display",0.3 MP Rear Camera,"Memory Card Supported, upto 32 GB"
925,927,Nokia 3310 4G,3999,NaN,"Dual Sim, 3G, 4G, VoLTE, Wi-Fi","256 MB RAM, 512 MB inbuilt",1200 mAh Battery,"2.4 inches, 240 x 320 px Display",2 MP Rear Camera,"Memory Card Supported, upto 32 GB",Bluetooth,Browser

In [24]:
df1.drop([645,857,882,925],inplace=True)

C:\Users\DEEL\AppData\Local\Temp\ipykernel_17040\1676279141.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df1.drop([645,857,882,925],inplace=True)

In [25]:
df1.drop(582,inplace=True)

C:\Users\DEEL\AppData\Local\Temp\ipykernel_17040\544825702.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df1.drop(582,inplace=True)

In [26]:
df1[df1['index'].isin(ram_rows)]

,index,model,price,rating,sim,processor,ram,battery,display,camera,card,os
439,441,Apple iPhone SE 3 2022,43900,NaN,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC","Bionic A15, Hexa Core, 3.22 GHz Processor",64 GB inbuilt,"4.7 inches, 750 x 1334 px Display",12 MP Rear & 7 MP Front Camera,Memory Card Not Supported,iOS v15,No FM Radio
483,485,Huawei Mate 50 RS Porsche Design,239999,81.0,"Dual Sim, 3G, 4G, VoLTE, Wi-Fi, NFC, IR Blaster","Snapdragon 8+ Gen1, Octa Core, 3.2 GHz Processor",512 GB inbuilt,4700 mAh Battery with 66W Fast Charging,"6.74 inches, 1212 x 2616 px, 120 Hz Display",50 MP + 48 MP + 13 MP Triple Rear & 13 MP Fron...,"Memory Card (Hybrid), upto 256 GB",Hongmeng OS v3.0

In [27]:
df1[df1['index'].isin(battery_rows)]

,index,model,price,rating,sim,processor,ram,battery,display,camera,card,os
111,113,Apple iPhone 12,51999,74.0,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC","Bionic A14, Hexa Core, 3.1 GHz Processor","4 GB RAM, 64 GB inbuilt","6.1 inches, 1170 x 2532 px Display with Large ...",12 MP + 12 MP Dual Rear & 12 MP Front Camera,Memory Card Not Supported,iOS v14,No FM Radio
149,151,Apple iPhone 12 Mini,40999,74.0,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC","Bionic A14, Hexa Core, 3.1 GHz Processor","4 GB RAM, 64 GB inbuilt","5.4 inches, 1080 x 2340 px Display",12 MP + 12 MP Dual Rear & 12 MP Front Camera,Memory Card Not Supported,iOS v14,No FM Radio
307,309,Apple iPhone 12 (128GB),55999,75.0,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC","Bionic A14, Hexa Core, 3.1 GHz Processor","4 GB RAM, 128 GB inbuilt","6.1 inches, 1170 x 2532 px Display with Large ...",12 MP + 12 MP Dual Rear & 12 MP Front Camera,Memory Card Not Supported,iOS v14,No FM Radio
363,365,Apple iPhone 12 Mini (128GB),45999,75.0,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC","Bionic A14, Hexa Core, 3.1 GHz Processor","4 GB RAM, 128 GB inbuilt","5.4 inches, 1080 x 2340 px Display",12 MP + 12 MP Dual Rear & 12 MP Front Camera,Memory Card Not Supported,iOS v14,No FM Radio
376,378,Nokia 2660 Flip,4649,NaN,"Dual Sim, 3G, 4G",No Wifi,Unisoc T107,"48 MB RAM, 128 MB inbuilt",1450 mAh Battery,"2.8 inches, 240 x 320 px Display",Dual Display,0.3 MP Rear Camera
439,441,Apple iPhone SE 3 2022,43900,NaN,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC","Bionic A15, Hexa Core, 3.22 GHz Processor",64 GB inbuilt,"4.7 inches, 750 x 1334 px Display",12 MP Rear & 7 MP Front Camera,Memory Card Not Supported,iOS v15,No FM Radio
448,450,Apple iPhone 15 Pro,130990,75.0,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC",Bionic A16,"8 GB RAM, 128 GB inbuilt","6.06 inches, 1170 x 2532 px, 120 Hz Display wi...",50 MP + 12 MP + 12 MP Triple Rear & 12 MP Fron...,Memory Card Not Supported,iOS v15,No FM Radio
628,630,Apple iPhone 12 Pro (512GB),139900,80.0,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC","Bionic A14, Hexa Core, 3.1 GHz Processor","6 GB RAM, 512 GB inbuilt","6.1 inches, 1170 x 2532 px Display with Large ...",12 MP + 12 MP + 12 MP Triple Rear & 12 MP Fron...,Memory Card Not Supported,iOS v14.0,No FM Radio
754,756,Apple iPod Touch (7th Gen),18900,NaN,Wi-Fi,32 GB inbuilt,"4 inches, 640 x 1136 px Display",8 MP Rear & 1.2 MP Front Camera,iOS v12,No FM Radio,Bluetooth,Browser
762,764,Apple iPhone SE 4,49990,60.0,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC","Bionic A15, Hexa Core, 3.22 GHz Processor",64 GB inbuilt,"6.1 inches, 750 x 1580 px Display",12 MP Rear & 10.8 MP Front Camera,Memory Card Not Supported,iOS v16,No FM Radio
853,855,Apple iPhone 12 Pro (256GB),119900,80.0,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC","Bionic A14, Hexa Core, 3.1 GHz Processor","6 GB RAM, 256 GB inbuilt","6.1 inches, 1170 x 2532 px Display with Large ...",12 MP + 12 MP + 12 MP Triple Rear & 12 MP Fron...,Memory Card Not Supported,iOS v14.0,No FM Radio
913,915,Apple iPhone 12 Mini (256GB),55999,75.0,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC","Bionic A14, Hexa Core, 3.1 GHz Processor","4 GB RAM, 256 GB inbuilt","5.4 inches, 1080 x 2340 px Display",12 MP + 12 MP Dual Rear & 12 MP Front Camera,Memory Card Not Supported,iOS v14,No FM Radio
914,916,Apple iPhone 12 (256GB),67999,76.0,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC","Bionic A14, Hexa Core, 3.1 GHz Processor","4 GB RAM, 256 GB inbuilt","6.1 inches, 1170 x 2532 px Display with Large ...",12 MP + 12 MP Dual Rear & 12 MP Front Camera,Memory Card Not Supported,iOS v14,No FM Radio

In [28]:
df1.drop([376,754],inplace=True)

C:\Users\DEEL\AppData\Local\Temp\ipykernel_17040\2579486625.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df1.drop([376,754],inplace=True)

In [29]:
temp_df = df1[df1['index'].isin(battery_rows)]

In [30]:
x = temp_df.iloc[:,7:].shift(1,axis=1).values

In [31]:
df1.loc[temp_df.index,temp_df.columns[7:]] = x

In [32]:
df1[df1['index'].isin(display_rows)]

,index,model,price,rating,sim,processor,ram,battery,display,camera,card,os
439,441,Apple iPhone SE 3 2022,43900,NaN,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC","Bionic A15, Hexa Core, 3.22 GHz Processor",64 GB inbuilt,None,"4.7 inches, 750 x 1334 px Display",12 MP Rear & 7 MP Front Camera,Memory Card Not Supported,iOS v15
448,450,Apple iPhone 15 Pro,130990,75.0,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC",Bionic A16,"8 GB RAM, 128 GB inbuilt",None,"6.06 inches, 1170 x 2532 px, 120 Hz Display wi...",50 MP + 12 MP + 12 MP Triple Rear & 12 MP Fron...,Memory Card Not Supported,iOS v15
628,630,Apple iPhone 12 Pro (512GB),139900,80.0,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC","Bionic A14, Hexa Core, 3.1 GHz Processor","6 GB RAM, 512 GB inbuilt",None,"6.1 inches, 1170 x 2532 px Display with Large ...",12 MP + 12 MP + 12 MP Triple Rear & 12 MP Fron...,Memory Card Not Supported,iOS v14.0
762,764,Apple iPhone SE 4,49990,60.0,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC","Bionic A15, Hexa Core, 3.22 GHz Processor",64 GB inbuilt,None,"6.1 inches, 750 x 1580 px Display",12 MP Rear & 10.8 MP Front Camera,Memory Card Not Supported,iOS v16
913,915,Apple iPhone 12 Mini (256GB),55999,75.0,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC","Bionic A14, Hexa Core, 3.1 GHz Processor","4 GB RAM, 256 GB inbuilt",None,"5.4 inches, 1080 x 2340 px Display",12 MP + 12 MP Dual Rear & 12 MP Front Camera,Memory Card Not Supported,iOS v14
914,916,Apple iPhone 12 (256GB),67999,76.0,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC","Bionic A14, Hexa Core, 3.1 GHz Processor","4 GB RAM, 256 GB inbuilt",None,"6.1 inches, 1170 x 2532 px Display with Large ...",12 MP + 12 MP Dual Rear & 12 MP Front Camera,Memory Card Not Supported,iOS v14

In [33]:
df1[df1['index'].isin(camera_rows)]

,index,model,price,rating,sim,processor,ram,battery,display,camera,card,os
98,100,Vivo X Fold 5G,106990,NaN,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC","Snapdragon 8 Gen1, Octa Core, 3 GHz Processor","12 GB RAM, 256 GB inbuilt",4600 mAh Battery with 66W Fast Charging,"8.03 inches, 1916 x 2160 px, 120 Hz Display",Foldable Display,50 MP Quad Rear & 16 MP Front Camera,Android v12
111,113,Apple iPhone 12,51999,74.0,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC","Bionic A14, Hexa Core, 3.1 GHz Processor","4 GB RAM, 64 GB inbuilt",None,"6.1 inches, 1170 x 2532 px Display with Large ...",12 MP + 12 MP Dual Rear & 12 MP Front Camera,Memory Card Not Supported,iOS v14
149,151,Apple iPhone 12 Mini,40999,74.0,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC","Bionic A14, Hexa Core, 3.1 GHz Processor","4 GB RAM, 64 GB inbuilt",None,"5.4 inches, 1080 x 2340 px Display",12 MP + 12 MP Dual Rear & 12 MP Front Camera,Memory Card Not Supported,iOS v14
155,157,Nokia 2780 Flip,4990,NaN,"Dual Sim, 3G, 4G, Wi-Fi","Snapdragon QM215, Quad Core, 1.3 GHz Processor","4 GB RAM, 512 MB inbuilt",1450 mAh Battery,"2.7 inches, 240 x 320 px Display",Dual Display,5 MP Rear Camera,"Memory Card Supported, upto 32 GB"
159,161,Oppo Find N2 5G,94990,NaN,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC","Snapdragon 8+ Gen1, Octa Core, 3.2 GHz Processor","12 GB RAM, 256 GB inbuilt",4520 mAh Battery with 67W Fast Charging,"7.1 inches, 1792 x 1920 px, 120 Hz Display wit...","Foldable Display, Dual Display",50 MP + 48 MP + 32 MP Triple Rear & 32 MP + 32...,Memory Card Not Supported
236,238,Xiaomi Mix Fold 2 5G,106990,NaN,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC, IR Bl...","Snapdragon 8+ Gen1 , Octa Core, 3.2 GHz Proce...","12 GB RAM, 256 GB inbuilt",4500 mAh Battery with 67W Fast Charging,"8.02 inches, 1914 x 2160 px, 120 Hz Display wi...","Foldable Display, Dual Display",50 MP + 13 MP + 8 MP Triple Rear & 20 MP Front...,Android v12
271,273,Nokia 2720 V Flip,6199,NaN,"Dual Sim, 3G, 4G, VoLTE, Wi-Fi","Snapdragon 205 , Dual Core, 1.1 GHz Processor","512 MB RAM, 4 GB inbuilt",1500 mAh Battery,"2.8 inches, 240 x 320 px Display",Dual Display,2 MP Rear Camera,Memory Card Supported
306,308,Samsung Galaxy Z Flip 3,69999,84.0,"Single Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC","Snapdragon 888, Octa Core, 2.84 GHz Processor","8 GB RAM, 128 GB inbuilt",3300 mAh Battery with 15W Fast Charging,"6.7 inches, 1080 x 2640 px, 120 Hz Display wit...","Foldable Display, Dual Display",12 MP + 12 MP Dual Rear & 10 MP Front Camera,Memory Card Not Supported
307,309,Apple iPhone 12 (128GB),55999,75.0,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC","Bionic A14, Hexa Core, 3.1 GHz Processor","4 GB RAM, 128 GB inbuilt",None,"6.1 inches, 1170 x 2532 px Display with Large ...",12 MP + 12 MP Dual Rear & 12 MP Front Camera,Memory Card Not Supported,iOS v14
321,323,Samsung Galaxy Z Fold 4,154998,NaN,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC","Snapdragon 8+ Gen1, Octa Core, 3.2 GHz Processor","12 GB RAM, 256 GB inbuilt",4400 mAh Battery with 25W Fast Charging,"7.6 inches, 1812 x 2176 px, 120 Hz Display wit...","Foldable Display, Dual Display",50 MP + 12 MP + 10 MP Triple Rear & 10 MP + 4 ...,Android v12
322,324,Royole FlexPai 2,109999,87.0,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi","Snapdragon 865, Octa Core, 2.84 GHz Processor","8 GB RAM, 128 GB inbuilt",4450 mAh Battery,"7.8 inches, 1440 x 1920 px Display","Foldable Display, Dual Display",64 MP + 16 MP + 8 MP Triple Rear & 32 MP Front...,"Memory Card Supported, upto 256 GB"
363,365,Apple iPhone 12 Mini (128GB),45999,75.0,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC","Bionic A14, Hexa Core, 3.1 GHz Processor","4 GB RAM, 128 GB inbuilt",None,"5.4 inches, 1080 x 2340 px Display",12 MP + 12 MP Dual Rear & 12 MP Front Camera,Memory Card Not Supported,iOS v14
365,367,OPPO Find N Flip,89990,88.0,"Single Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC","Dimensity 9000, Octa Core, 3.05 GHz Processor","8 GB RAM, 128 GB inbuilt",4300 mAh Battery with 44W Fast Charging,"6.8 inches, 1200 x 2400 px, 120 Hz Display wit...","Foldable Display, Dual Display",50 MP + 8 MP Dual Rear & 32 MP Front Camera,Memory Card Not Supported
392,394,OPPO Find N2 Flip,70990,88.0,"Single Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC","Dimensity 9000 Plus, Octa Core, 3.2 GHz Processor","8 GB RAM, 256 GB inbuilt",4300 mAh Battery with 44W Fast Charging,"6.8 inches, 1080 x 2520 px, 120 Hz Display wit...","Foldable Display, Dual Display",50 MP + 8 MP Dual Rear & 32 MP Front Camera,Memory Card Not Supported
439,441,Apple iPhone SE 3 2022,43900,NaN,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC","Bionic A15, Hexa Core, 3.22 GHz Processor",64 GB inbuilt,None,"4.7 inches, 750 x 1334 px Display",12 MP Rear & 7 MP Front Camera,Memory Card Not Supported,iOS v15
448,450,Apple iPhone 15 Pro,130990,75.0,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC",Bionic A16,"8 GB RAM, 128 GB inbuilt",None,"6.06 inches, 1170 x 2532 px, 120 Hz Display wi...",50 MP + 12 MP + 12 MP Triple Rear & 12 MP Fron...,Memory Card Not Supported,iOS v15
482,484,Vivo X Fold Plus,113990,NaN,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC","Snapdragon 8+ Gen1, Octa Core, 3.2 GHz Processor","12 GB RAM, 256 GB inbuilt",4730 mAh Battery with 80W Fast Charging,"8.03 inches, 1916 x 2160 px, 120 Hz Display wi...","Foldable Display, Dual Display",50 MP Quad Rear & 16 MP + 16 MP Dual Front Camera,Android v12
504,506,Samsung Galaxy Z Flip 4 5G,89999,88.0,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC","Snapdragon 8+ Gen1, Octa Core, 3.2 GHz Processor","8 GB RAM, 128 GB inbuilt",3700 mAh Battery with 25W Fast Charging,"6.7 inches, 1080 x 2640 px, 120 Hz Display wit...","Foldable Display, Dual Display",12 MP + 12 MP Dual Rear & 10 MP Front Camera,Memory Card Not Supported
569,571,Samsung Galaxy Z Fold 3,110999,89.0,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC","Snapdragon 888, Octa Core, 2.84 GHz Processor","12 GB RAM, 256 GB inbuilt",4400 mAh Battery with 25W Fast Charging,"7.6 inches, 1768 x 2208 px, 120 Hz Display wit...","Foldable Display, Dual Display",12 MP + 12 MP + 12 MP Triple Rear & 10 MP + 4 ...,Android v11
570,572,LG Wing 5G,54999,89.0,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC","Snapdragon 765G , Octa Core, 2.4 GHz Processor","8 GB RAM, 128 GB inbuilt",4000 mAh Battery with Fast Charging,"6.8 inches, 1080 x 2460 px Display",Dual Display,64 MP + 13 MP + 12 MP Triple Rear & 32 MP Fron...,"Memory Card (Hybrid), upto 2 TB"
613,615,Oukitel WP21,22990,82.0,"Dual Sim, 3G, 4G, VoLTE, Wi-Fi","Helio G99, Octa Core, 2.2 GHz Processor","12 GB RAM, 256 GB inbuilt",9800 mAh Battery with 66W Fast Charging,"6.78 inches, 1080 x 2400 px, 120 Hz Display",Dual Display,64 MP + 20 MP + 2 MP Triple Rear & Main Front ...,Memory Card (Hybrid)
628,630,Apple iPhone 12 Pro (512GB),139900,80.0,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC","Bionic A14, Hexa Core, 3.1 GHz Processor","6 GB RAM, 512 GB inbuilt",None,"6.1 inches, 1170 x 2532 px Display with Large ...",12 MP + 12 MP + 12 MP Triple Rear & 12 MP Fron...,Memory Card Not Supported,iOS v14.0
682,684,LG V60 ThinQ,79990,NaN,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC","Snapdragon 865, Octa Core, 2.84 GHz Processor","8 GB RAM, 128 GB inbuilt",5000 mAh Battery with Fast Charging,"6.8 inches, 1080 x 2460 px Display with Punch ...",Dual Display,64 MP + 13 MP + 0.3 MP Triple Rear & 10 MP Fro...,"Memory Card (Hybrid), upto 2 TB"
703,705,Oppo Find N 5G,92249,NaN,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC","Snapdragon 888, Octa Core, 2.84 GHz Processor","8 GB RAM, 256 GB inbuilt",4500 mAh Battery with 33W Fast Charging,"7.1 inches, 1792 x 1920 px, 120 Hz Display wit...","Foldable Display, Dual Display",50 MP + 16 MP + 13 MP Triple Rear & 32 MP Fron...,Android v11
709,711,OPPO X 2021,134999,86.0,"Single Sim, 3G, 4G, VoLTE, Wi-Fi","Snapdragon 865, Octa Core, 2.84 GHz Processor","8 GB RAM, 256 GB inbuilt",4000 mAh Battery with 45W Fast Charging,"7.4 inches, 1440 x 3200 px Display",Dual Display,64 MP + 16 MP + 12 MP Triple Rear & 16 MP Fron...,Android v11
721,723,Asus ROG Phone 6D Ultimate,107990,NaN,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC","Dimensity 9000 Plus, Octa Core, 3.2 GHz Processor","16 GB RAM, 512 GB inbuilt",6000 mAh Battery with 65W Fast Charging,"6.78 inches, 1080 x 2448 px, 165 Hz Display",Dual Display,50 MP + 13 MP + 5 MP Triple Rear & 12 MP Front...,Memory Card Not Supported
726,728,Huawei Mate Xs 2,162990,89.0,"Dual Sim, 3G, 4G, VoLTE, Wi-Fi, NFC, IR Blaster","Snapdragon 888, Octa Core, 2.84 GHz Processor","8 GB RAM, 512 GB inbuilt",4600 mAh Battery with 66W Fast Charging,"7.8 inches, 2200 x 2480 px, 120 Hz Display wit...",Foldable Display,50 MP + 13 MP + 8 MP Triple Rear & 10.7 MP Fro...,"Memory Card (Hybrid), upto 256 GB"
762,764,Apple iPhone SE 4,49990,60.0,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC","Bionic A15, Hexa Core, 3.22 GHz Processor",64 GB inbuilt,None,"6.1 inches, 750 x 1580 px Display",12 MP Rear & 10.8 MP Front Camera,Memory Card Not Supported,iOS v16
790,792,Xiaomi Mi Mix Fold,109990,NaN,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC, IR Bl...","Snapdragon 888 , Octa Core, 2.84 GHz Processor","12 GB RAM, 256 GB inbuilt",5020 mAh Battery with 67W Fast Charging,"8.01 inches, 1860 x 2480 px, 90 Hz Display","Foldable Display, Dual Display",108 MP + 13 MP + 8 MP Triple Rear & 20 MP Fron...,Android v10
844,846,CAT S22 Flip,14999,NaN,"Single Sim, 3G, 4G, VoLTE, Wi-Fi","Qualcomm 215, Quad Core, 1.3 GHz Processor","2 GB RAM, 16 GB inbuilt",2000 mAh Battery,"4 inches, 480 x 640 px Display",Dual Display,5 MP Rear & 2 MP Front Camera,"Memory Card Supported, upto 128 GB"
853,855,Apple iPhone 12 Pro (256GB),119900,80.0,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC","Bionic A14, Hexa Core, 3.1 GHz Processor","6 GB RAM, 256 GB inbuilt",None,"6.1 inches, 1170 x 2532 px Display with Large ...",12 MP + 12 MP + 12 MP Triple Rear & 12 MP Fron...,Memory Card Not Supported,iOS v14.0
856,858,Samsung Galaxy A01 Core,4999,NaN,"Dual Sim, 3G, 4G, VoLTE, Wi-Fi","(28 nm), Quad Core, 1.5 GHz Processor","1 GB RAM, 16 GB inbuilt",3000 mAh Battery,"5.3 inches, 720 x 1480 px Display",8 MP Rear & 5 MP Front Camera,Memory Card Supported,Android v10
894,896,Royole FlexPai 3 5G,149999,87.0,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi","Snapdragon 888, Octa Core, 2.84 GHz Processor","8 GB RAM, 128 GB inbuilt",3360 mAh Battery,"7.2 inches, 1440 x 1920 px Display","Foldable Display, Dual Display",64 MP + 16 MP + 8 MP Triple Rear & 32 MP Front...,"Memory Card Supported, upto 256 GB"
913,915,Apple iPhone 12 Mini (256GB),55999,75.0,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC","Bionic A14, Hexa Core, 3.1 GHz Processor","4 GB RAM, 256 GB inbuilt",None,"5.4 inches, 1080 x 2340 px Display",12 MP + 12 MP Dual Rear & 12 MP Front Camera,Memory Card Not Supported,iOS v14
914,916,Apple iPhone 12 (256GB),67999,76.0,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC","Bionic A14, Hexa Core, 3.1 GHz Processor","4 GB RAM, 256 GB inbuilt",None,"6.1 inches, 1170 x 2532 px Display with Large ...",12 MP + 12 MP Dual Rear & 12 MP Front Camera,Memory Card Not Supported,iOS v14
943,945,Samsung Galaxy Z Fold 4 (12GB RAM + 1TB),163980,NaN,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC","Snapdragon 8+ Gen1, Octa Core, 3.2 GHz Processor","12 GB RAM, 1 TB inbuilt",4400 mAh Battery with 25W Fast Charging,"7.6 inches, 1812 x 2176 px, 120 Hz Display wit...","Foldable Display, Dual Display",50 MP + 12 MP + 10 MP Triple Rear & 10 MP + 4 ...,Android v12
954,956,Vivo X Fold 5G (12GB RAM + 512GB),118990,NaN,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC","Snapdragon 8 Gen1, Octa Core, 3 GHz Processor","12 GB RAM, 512 GB inbuilt",4600 mAh Battery with 66W Fast Charging,"8.03 inches, 1916 x 2160 px, 120 Hz Display",Foldable Display,50 MP Quad Rear & 16 MP Front Camera,Android v12
993,995,Huawei Mate X,169000,NaN,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC, IR Bl...","Kirin 990, Octa Core, 2.86 GHz Processor","8 GB RAM, 512 GB inbuilt",4500 mAh Battery with 55W Fast Charging,"8 inches, 2200 x 2480 px Display",Foldable Display,48 MP Quad Rear Camera,"Memory Card (Hybrid), upto 256 GB"
1014,1016,Vivo X Fold 2,119990,NaN,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC","Snapdragon 8 Gen2, Octa Core, 3.2 GHz Processor","12 GB RAM, 256 GB inbuilt",4800 mAh Battery with 66W Fast Charging,"8.03 inches, 1916 x 2160 px, 120 Hz Display",Foldable Display,50 MP + 50 MP + 10 MP Triple Rear & 32 MP Fron...,Android v12

In [34]:
df1.drop([155,271],inplace=True)

C:\Users\DEEL\AppData\Local\Temp\ipykernel_17040\1298457551.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df1.drop([155,271],inplace=True)

In [35]:
temp_df = df1[df1['index'].isin(camera_rows)]

In [36]:
temp_df = temp_df[~temp_df['camera'].str.contains('MP')]

In [37]:
df1.loc[temp_df.index, 'camera'] = temp_df['card'].values

In [38]:
df1['card'].value_counts()

card
Memory Card Supported, upto 1 TB                                       171
Memory Card Not Supported                                              123
Android v12                                                            107
Memory Card Supported, upto 512 GB                                     105
Memory Card (Hybrid), upto 1 TB                                         91
Memory Card Supported                                                   89
Memory Card Supported, upto 256 GB                                      87
Android v13                                                             46
Android v11                                                             41
Memory Card (Hybrid)                                                    30
Memory Card (Hybrid), upto 256 GB                                       13
Android v10                                                             11
Memory Card (Hybrid), upto 512 GB                                       11
Memory Card Supported, upto 128 GB                                       6
Memory Card Supported, upto 2 TB                                         5
Memory Card Supported, upto 32 GB                                        4
Memory Card (Hybrid), upto 64 GB                                         3
Memory Card (Hybrid), upto 128 GB                                        3
Android v9.0 (Pie)                                                       2
50 MP + 12 MP + 10 MP Triple Rear & 10 MP + 4 MP Dual Front Camera       2
64 MP + 16 MP + 8 MP Triple Rear & 32 MP Front Camera                    2
50 MP + 8 MP Dual Rear & 32 MP Front Camera                              2
12 MP + 12 MP Dual Rear & 10 MP Front Camera                             2
50 MP Quad Rear & 16 MP Front Camera                                     2
64 MP + 13 MP + 0.3 MP Triple Rear & 10 MP Front Camera                  1
48 MP Quad Rear Camera                                                   1
HarmonyOS                                                                1
Memory Card (Hybrid), upto 2 TB                                          1
5 MP Rear & 2 MP Front Camera                                            1
108 MP + 13 MP + 8 MP Triple Rear & 20 MP Front Camera                   1
HarmonyOS v2.0                                                           1
50 MP + 13 MP + 8 MP Triple Rear & 10.7 MP Front Camera                  1
50 MP + 13 MP + 5 MP Triple Rear & 12 MP Front Camera                    1
64 MP + 16 MP + 12 MP Triple Rear & 16 MP Front Camera                   1
50 MP + 16 MP + 13 MP Triple Rear & 32 MP Front Camera                   1
iOS v13                                                                  1
50 MP + 13 MP + 8 MP Triple Rear & 20 MP Front Camera                    1
Android v10.0                                                            1
64 MP + 20 MP + 2 MP Triple Rear & Main Front Camera                     1
iOS v10                                                                  1
64 MP + 13 MP + 12 MP Triple Rear & 32 MP Front Camera                   1
12 MP + 12 MP + 12 MP Triple Rear & 10 MP + 4 MP Dual Front Camera       1
Memory Card Supported, upto 1000 GB                                      1
50 MP Quad Rear & 16 MP + 16 MP Dual Front Camera                        1
64 MP + 10 MP + 8 MP Triple Rear & 32 MP Front Camera                    1
Android v12.1                                                            1
50 MP + 48 MP + 32 MP Triple Rear & 32 MP + 32 MP Dual Front Camera      1
50 MP + 50 MP + 10 MP Triple Rear & 32 MP Front Camera                   1
Name: count, dtype: int64

In [39]:
temp_df = df1[df1['card'].str.contains('MP')]

In [40]:
df1.loc[temp_df.index,'card'] = 'Memory Card Not Supported'

In [41]:
df1['card'].value_counts()

card
Memory Card Supported, upto 1 TB       171
Memory Card Not Supported              149
Android v12                            107
Memory Card Supported, upto 512 GB     105
Memory Card (Hybrid), upto 1 TB         91
Memory Card Supported                   89
Memory Card Supported, upto 256 GB      87
Android v13                             46
Android v11                             41
Memory Card (Hybrid)                    30
Memory Card (Hybrid), upto 256 GB       13
Memory Card (Hybrid), upto 512 GB       11
Android v10                             11
Memory Card Supported, upto 128 GB       6
Memory Card Supported, upto 2 TB         5
Memory Card Supported, upto 32 GB        4
Memory Card (Hybrid), upto 64 GB         3
Memory Card (Hybrid), upto 128 GB        3
Android v9.0 (Pie)                       2
Android v12.1                            1
Memory Card Supported, upto 1000 GB      1
iOS v10                                  1
Android v10.0                            1
iOS v13                                  1
HarmonyOS v2.0                           1
Memory Card (Hybrid), upto 2 TB          1
HarmonyOS                                1
Name: count, dtype: int64

In [42]:
pd.set_option('display.max_rows', None)

In [43]:
temp_df = df1[~df1['card'].str.contains('Memory Card')]

In [44]:
df1.loc[temp_df.index,'os'] = temp_df['card'].values

In [45]:
df1.loc[temp_df.index,'card'] = 'Memory Card Not Supported'

In [46]:
df1['card'].value_counts()

card
Memory Card Not Supported              362
Memory Card Supported, upto 1 TB       171
Memory Card Supported, upto 512 GB     105
Memory Card (Hybrid), upto 1 TB         91
Memory Card Supported                   89
Memory Card Supported, upto 256 GB      87
Memory Card (Hybrid)                    30
Memory Card (Hybrid), upto 256 GB       13
Memory Card (Hybrid), upto 512 GB       11
Memory Card Supported, upto 128 GB       6
Memory Card Supported, upto 2 TB         5
Memory Card Supported, upto 32 GB        4
Memory Card (Hybrid), upto 128 GB        3
Memory Card (Hybrid), upto 64 GB         3
Memory Card Supported, upto 1000 GB      1
Memory Card (Hybrid), upto 2 TB          1
Name: count, dtype: int64

In [47]:
temp_df = df1[df1['os'] == 'Bluetooth']

In [48]:
df1.loc[temp_df.index,'os'] = np.nan

In [49]:
df1.head()

,index,model,price,rating,sim,processor,ram,battery,display,camera,card,os
0,2,OnePlus 11 5G,54999,89.0,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC","Snapdragon 8 Gen2, Octa Core, 3.2 GHz Processor","12 GB RAM, 256 GB inbuilt",5000 mAh Battery with 100W Fast Charging,"6.7 inches, 1440 x 3216 px, 120 Hz Display wit...",50 MP + 48 MP + 32 MP Triple Rear & 16 MP Fron...,Memory Card Not Supported,Android v13
1,3,OnePlus Nord CE 2 Lite 5G,19989,81.0,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi","Snapdragon 695, Octa Core, 2.2 GHz Processor","6 GB RAM, 128 GB inbuilt",5000 mAh Battery with 33W Fast Charging,"6.59 inches, 1080 x 2412 px, 120 Hz Display wi...",64 MP + 2 MP + 2 MP Triple Rear & 16 MP Front ...,"Memory Card (Hybrid), upto 1 TB",Android v12
2,4,Samsung Galaxy A14 5G,16499,75.0,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi","Exynos 1330, Octa Core, 2.4 GHz Processor","4 GB RAM, 64 GB inbuilt",5000 mAh Battery with 15W Fast Charging,"6.6 inches, 1080 x 2408 px, 90 Hz Display with...",50 MP + 2 MP + 2 MP Triple Rear & 13 MP Front ...,"Memory Card Supported, upto 1 TB",Android v13
3,5,Motorola Moto G62 5G,14999,81.0,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi","Snapdragon 695, Octa Core, 2.2 GHz Processor","6 GB RAM, 128 GB inbuilt",5000 mAh Battery with Fast Charging,"6.55 inches, 1080 x 2400 px, 120 Hz Display wi...",50 MP + 8 MP + 2 MP Triple Rear & 16 MP Front ...,"Memory Card (Hybrid), upto 1 TB",Android v12
4,6,Realme 10 Pro Plus,24999,82.0,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi","Dimensity 1080, Octa Core, 2.6 GHz Processor","6 GB RAM, 128 GB inbuilt",5000 mAh Battery with 67W Fast Charging,"6.7 inches, 1080 x 2412 px, 120 Hz Display wit...",108 MP + 8 MP + 2 MP Triple Rear & 16 MP Front...,Memory Card Not Supported,Android v13

In [50]:
df1['display'].value_counts()

display
6.67 inches, 1080 x 2400 px, 120 Hz Display with Punch Hole          54
6.5 inches, 720 x 1600 px Display with Water Drop Notch              36
6.7 inches, 1080 x 2412 px, 120 Hz Display with Punch Hole           25
6.52 inches, 720 x 1600 px Display with Water Drop Notch             23
6.5 inches, 1080 x 2400 px, 90 Hz Display with Punch Hole            22
6.51 inches, 720 x 1600 px Display with Water Drop Notch             21
6.43 inches, 1080 x 2400 px, 90 Hz Display with Punch Hole           19
6.43 inches, 1080 x 2400 px Display with Punch Hole                  16
6.62 inches, 1080 x 2400 px, 120 Hz Display with Punch Hole          15
6.53 inches, 720 x 1600 px Display with Water Drop Notch             14
6.4 inches, 1080 x 2400 px, 90 Hz Display with Punch Hole            14
6.55 inches, 1080 x 2400 px, 120 Hz Display with Punch Hole          11
6.7 inches, 1440 x 3216 px, 120 Hz Display with Punch Hole           10
6.58 inches, 1080 x 2408 px, 120 Hz Display with Water Drop Notch    10
6.5 inches, 720 x 1600 px, 90 Hz Display with Water Drop Notch       10
6.6 inches, 1080 x 2400 px, 90 Hz Display with Punch Hole            10
6.7 inches, 1080 x 2400 px, 120 Hz Display with Punch Hole           10
6.5 inches, 1080 x 2400 px, 120 Hz Display with Punch Hole           10
6.67 inches, 1080 x 2400 px Display with Punch Hole                   9
6.6 inches, 1080 x 2408 px Display with Water Drop Notch              9
6.55 inches, 1080 x 2400 px, 90 Hz Display with Punch Hole            9
6.6 inches, 1080 x 2408 px, 90 Hz Display with Water Drop Notch       9
6.78 inches, 1080 x 2400 px, 120 Hz Display with Punch Hole           9
6.7 inches, 1080 x 2400 px Display with Punch Hole                    8
6.58 inches, 1080 x 2408 px, 90 Hz Display with Water Drop Notch      8
6.5 inches, 720 x 1600 px, 90 Hz Display with Punch Hole              7
6.59 inches, 1080 x 2412 px, 120 Hz Display with Punch Hole           7
6.6 inches, 1080 x 2408 px, 120 Hz Display with Water Drop Notch      7
6.53 inches, 1080 x 2340 px Display with Water Drop Notch             7
6.6 inches, 1080 x 2412 px, 120 Hz Display with Punch Hole            7
6.58 inches, 1080 x 2400 px, 90 Hz Display with Water Drop Notch      7
6.58 inches, 1080 x 2408 px Display with Water Drop Notch             7
6.67 inches, 1080 x 2400 px, 144 Hz Display with Punch Hole           7
6.1 inches, 1170 x 2532 px Display with Small Notch                   6
6.73 inches, 1440 x 3200 px, 120 Hz Display with Punch Hole           6
6.4 inches, 1080 x 2400 px, 90 Hz Display with Water Drop Notch       6
6.44 inches, 1080 x 2400 px Display with Water Drop Notch             6
6.1 inches, 1170 x 2532 px Display with Large Notch                   5
6.6 inches, 1080 x 2460 px, 144 Hz Display with Punch Hole            5
6.5 inches, 720 x 1560 px Display with Water Drop Notch               5
6.4 inches, 1080 x 2340 px Display with Water Drop Notch              5
6.4 inches, 1080 x 2400 px Display with Punch Hole                    5
6.67 inches, 1440 x 3200 px, 120 Hz Display with Punch Hole           5
6.8 inches, 1080 x 2400 px, 120 Hz Display with Punch Hole            5
6.44 inches, 1080 x 2404 px, 90 Hz Display with Water Drop Notch      5
6.56 inches, 720 x 1612 px, 90 Hz Display with Water Drop Notch       5
6.67 inches, 1080 x 2460 px, 120 Hz Display with Punch Hole           5
6.56 inches, 720 x 1612 px Display with Water Drop Notch              5
6.6 inches, 720 x 1612 px, 90 Hz Display with Water Drop Notch        4
6.6 inches, 1080 x 2400 px, 120 Hz Display with Punch Hole            4
6.7 inches, 720 x 1600 px Display with Water Drop Notch               4
6.7 inches, 1290 x 2796 px, 120 Hz Display                            4
6.56 inches, 1080 x 2376 px, 120 Hz Display with Punch Hole           4
6.67 inches, 2400 x 1080 px, 120 Hz Display with Punch Hole           4
6.5 inches, 1600 x 720 px Display with Water Drop Notch               4
6.56 inches, 720 x 1600 px Display with Water Drop Notch              4
6.7 inches, 1080 x 2400 px Display with Water Drop Notch              4
6.35 inches, 720 x 1544 px Display with Water Drop Notch              4
6.78 inches, 1440 x 3200 px, 120 Hz Display with Punch Hole           4
6.78 inches, 1080 x 2448 px, 165 Hz Display                           4
6.2 inches, 720 x 1520 px Display with Water Drop Notch               3
6.4 inches, 1080 x 2400 px, 120 Hz Display with Punch Hole            3
6.78 inches, 1080 x 2460 px, 120 Hz Display with Punch Hole           3
6.6 inches, 2460 x 1080 px, 90 Hz Display with Punch Hole             3
6.7 inches, 1284 x 2778 px, 120 Hz Display with Small Notch           3
6.73 inches, 1080 x 2412 px, 120 Hz Display with Punch Hole           3
6.1 inches, 1170 x 2532 px, 120 Hz Display with Large Notch           3
4.7 inches, 750 x 1334 px Display                                     3
5 inches, 854 x 480 px Display                                        3
6.8 inches, 1080 x 2460 px Display with Punch Hole                    3
6.44 inches, 1080 x 2408 px, 90 Hz Display with Water Drop Notch      3
6.6 inches, 720 x 1600 px Display with Water Drop Notch               3
6.8 inches, 1116 x 2480 px, 120 Hz Display                            3
6.8 inches, 1080 x 2460 px, 120 Hz Display with Punch Hole            3
6.7 inches, 2400 x 1080 px Display with Punch Hole                    3
6.6 inches, 720 x 1600 px, 90 Hz Display with Water Drop Notch        3
5.4 inches, 1080 x 2340 px Display                                    3
6.44 inches, 1080 x 2400 px, 120 Hz Display with Water Drop Notch     3
6.43 inches, 1080 x 2400 px, 120 Hz Display with Punch Hole           3
6.6 inches, 1080 x 2408 px, 90 Hz Display with Punch Hole             3
7.1 inches, 1792 x 1920 px, 120 Hz Display with Punch Hole            3
6.6 inches, 1080 x 2412 px, 90 Hz Display with Punch Hole             3
6.78 inches, 1440 x 3200 px, 144 Hz Display with Punch Hole           3
8.03 inches, 1916 x 2160 px, 120 Hz Display                           3
6.1 inches, 1179 x 2556 px, 120 Hz Display                            3
6.6 inches, 1080 x 2340 px, 120 Hz Display with Punch Hole            3
6.1 inches, 1080 x 2340 px, 120 Hz Display with Punch Hole            3
6.7 inches, 1284 x 2778 px Display with Small Notch                   3
6.44 inches, 1080 x 2408 px Display with Water Drop Notch             3
6.51 inches, 1600 x 720 px Display with Punch Hole                    3
6.59 inches, 1080 x 2412 px, 90 Hz Display with Punch Hole            3
6.47 inches, 1080 x 2400 px Display with Punch Hole                   3
6.44 inches, 1080 x 2400 px, 90 Hz Display with Water Drop Notch      3
6.8 inches, 1440 x 3080 px, 120 Hz Display with Punch Hole            3
6.22 inches, 1520 x 720 px Display with Water Drop Notch              2
6.1 inches, 1080 x 2520 px, 120 Hz Display                            2
6.6 inches, 1080 x 2412 px, 144 Hz Display with Punch Hole            2
5.45 inches, 720 x 1440 px Display                                    2
6.5 inches, 1080 x 2400 px Display with Water Drop Notch              2
6 inches, 1080 x 2160 px Display                                      2
6.67 inches, 1220 x 2712 px, 120 Hz Display with Punch Hole           2
6.8 inches, 1440 x 3200 px, 120 Hz Display with Punch Hole            2
6.5 inches, 1644 x 3840 px, 120 Hz Display                            2
6.44 inches, 1080 x 2400 px Display with Small Notch                  2
6.3 inches, 1080 x 2340 px Display with Water Drop Notch              2
6.5 inches, 720 x 1560 px Display with Small Notch                    2
6.73 inches, 1080 x 2400 px, 120 Hz Display with Punch Hole           2
6.28 inches, 1080 x 2400 px, 120 Hz Display with Punch Hole           2
6.8 inches, 1440 x 3040 px Display with Punch Hole                    2
5.5 inches, 1080 x 1920 px Display                                    2
6.5 inches, 1080 x 2400 px Display with Punch Hole                    2
6.4 inches, 1080 x 2340 px Display with Punch Hole                    2
6.22 inches, 720 x 1520 px Display with Water Drop Notch              2
6.6 inches, 1612 x 720 px Display with Water Drop Notch               2
6.18 inches, 1080 x 2246 px Display with Large Notch                  2
6.71 inches, 1440 x 3200 px, 120 Hz Display with Punch Hole           2
6.4 inches, 720 x 1600 px, 90 Hz Display with Water Drop Notch        2
6.58 inches, 1080 x 2408 px, 90 Hz Display with Punch Hole            2
6.71 inches, 720 x 1650 px Display with Water Drop Notch              2
6.7 inches, 1080 x 2388 px, 90 Hz Display with Punch Hole             2
6.57 inches, 1080 x 2340 px, 120 Hz Display with Punch Hole           2
6.5 inches, 720 x 1600 px Display with Punch Hole                     2
6.8 inches, 1080 x 2460 px Display                                    2
6 inches, 720 x 1440 px Display                                       2
6.51 inches, 720 x 1600 px Display with Punch Hole                    2
6.44 inches, 1080 x 2400 px, 90 Hz Display with Dual Punch Hole       2
6.49 inches, 1080 x 2400 px, 90 Hz Display with Punch Hole            2
7.6 inches, 1812 x 2176 px, 120 Hz Display with Punch Hole            2
6.7 inches, 1080 x 2340 px, 90 Hz Display with Punch Hole             2
6.55 inches, 720 x 1612 px Display with Water Drop Notch              2
6.7 inches, 1080 x 2400 px, 144 Hz Display with Punch Hole            2
6.6 inches, 1080 x 2400 px, 120 Hz Display with Water Drop Notch      2
6.56 inches, 720 x 1600 px, 90 Hz Display with Water Drop Notch       2
6.56 inches, 1080 x 2376 px, 90 Hz Display with Small Notch           2
6.78 inches, 1260 x 2800 px, 120 Hz Display with Punch Hole           2
6.72 inches, 1080 x 2400 px, 120 Hz Display with Punch Hole           2
6.4 inches, 1080 x 2340 px, 120 Hz Display with Punch Hole            2
6.1 inches, 828 x 1792 px Display with Large Notch                    2
6.44 inches, 1080 x 2400 px, 90 Hz Display with Small Notch           2
6.71 inches, 1440 x 3120 px, 120 Hz Display with Punch Hole           2
6.82 inches, 720 x 1600 px, 90 Hz Display with Water Drop Notch       2
6.6 inches, 2408 x 1080 px Display with Water Drop Notch              2
6.58 inches, 1080 x 2400 px, 120 Hz Display with Punch Hole           2
6.7 inches, 1080 x 2640 px, 120 Hz Display with Punch Hole            2
6.73 inches, 1080 x 2400 px, 144 Hz Display with Punch Hole           2
6.5 inches, 1080 x 2400 px, 144 Hz Display with Punch Hole            2
6.6 inches, 1080 x 2400 px Display with Water Drop Notch              2
6.78 inches, 1080 x 2480 px, 90 Hz Display with Punch Hole            1
6 inches, 720 x 1600 px Display                                       1
6.7 inches, 1440 x 3200 px, 120 Hz Display with Punch Hole            1
6.71 inches, 1080 x 2400 px Display with Punch Hole                   1
6.6 inches, 1080 x 2400 px, 90 Hz Display with Dual Punch Hole        1
6.58 inches, 1200 x 2640 px, 90 Hz Display with Dual Punch Hole       1
6.39 inches, 1080 x 2316 px Display                                   1
6.3 inches, 1080 x 2280 px Display                                    1
4 inches, 480 x 640 px Display                                        1
6.2 inches, 1440 x 2960 px Display                                    1
6.6 inches, 1260 x 2730 px, 240 Hz Display with Punch Hole            1
6.78 inches, 1080 x 2460 px Display with Water Drop Notch             1
6.73 inches, 1080 x 2408 px, 120 Hz Display with Punch Hole           1
6.8 inches, 1080 x 2400 px, 90 Hz Display with Punch Hole             1
8.01 inches, 1860 x 2480 px, 90 Hz Display                            1
6.51 inches, 1600 x 720 px, 90 Hz Display with Water Drop Notch       1
6.5 inches, 1080 x 2400 px, 144 Hz Display                            1
6.8 inches, 720 x 1600 px Display with Punch Hole                     1
6.67 inches, 1220 x 2712 px, 144 Hz Display with Punch Hole           1
6.5 inches, 1080 x 2412 px, 144 Hz Display                            1
6.43 inches, 1080 x 2340 px, 90 Hz Display with Punch Hole            1
6.06 inches, 1170 x 2532 px Display with Punch Hole                   1
6.82 inches, 720 x 1600 px Display with Water Drop Notch              1
7.4 inches, 1440 x 3200 px Display                                    1
6.26 inches, 720 x 1600 px Display with Large Notch                   1
6.43 inches, 1080 x 2400 px Display with Dual Punch Hole              1
6.38 inches, 1080 x 2340 px Display with Water Drop Notch             1
6.67 inches, 1080 x 2408 px, 120 Hz Display with Water Drop Notch     1
6.76 inches, 1440 x 3200 px, 120 Hz Display with Small Notch          1
7.8 inches, 2200 x 2480 px, 120 Hz Display with Punch Hole            1
6.62 inches, 1080 x 2412 px, 144 Hz Display with Water Drop Notch     1
6.95 inches, 1080 x 2460 px, 120 Hz Display with Punch Hole           1
6.67 inches, 1080 x 2400 px, 90 Hz Display with Punch Hole            1
6.5 inches, 720 x 1600 px, 90 Hz Display                              1
6.1 inches, 720 x 1520 px Display with Water Drop Notch               1
6.6 inches, 1288 x 2700 px, 120 Hz Display with Punch Hole            1
6.7 inches, 1080 x 2520 px, 90 Hz Display with Punch Hole             1
6.44 inches, 1080 x 2400 px Display with Dual Punch Hole              1
6.2 inches, 1440 x 3200 px Display with Punch Hole                    1
6.78 inches, 1200 x 2652 px, 120 Hz Display with Punch Hole           1
6.1 inches, 750 x 1580 px Display                                     1
7 inches, 1440 x 3080 px, 120 Hz Display with Punch Hole              1
5.3 inches, 720 x 1480 px Display                                     1
6.6 inches, 1600 x 720 px Display with Punch Hole                     1
6 inches, 1080 x 2520 px, 90 Hz Display                               1
6.56 inches, 1080 x 2400 px, 120 Hz Display with Punch Hole           1
6.58 inches, 1080 x 2412 px, 120 Hz Display with Water Drop Notch     1
6.8 inches, 1080 x 2400 px, 165 Hz Display                            1
6.51 inches, 1080 x 2400 px, 144 Hz Display with Punch Hole           1
6.4 inches, 720 x 1600 px Display with Water Drop Notch               1
6.34 inches, 1080 x 2400 px Display with Punch Hole                   1
6.5 inches, 1600 x 720 px, 90 Hz Display with Punch Hole              1
6.09 inches, 1520 x 720 px Display with Water Drop Notch              1
6.67 inches, 1080 x 2340 px, 90 Hz Display with Punch Hole            1
6.5 inches, 720 x 1544 px Display with Water Drop Notch               1
6.5 inches, 1440 x 3168 px Display with Water Drop Notch              1
6.53 inches, 1176 x 2400 px Display with Large Notch                  1
6.4 inches, 720 x 1560 px Display with Punch Hole                     1
6.1 inches, 1560 x 720 px Display with Water Drop Notch               1
8 inches, 2200 x 2480 px Display                                      1
6 inches, 2220 x 1080 px Display                                      1
5.2 inches, 720 x 1280 px Display                                     1
6.1 inches, 720 x 1560 px Display with Punch Hole                     1
6.75 inches, 720 x 1600 px, 90 Hz Display with Water Drop Notch       1
6.82 inches, 720 x 1560 px Display with Punch Hole                    1
5.86 inches, 720 x 1520 px Display with Large Notch                   1
6.43 inches, 1440 x 3200 px, 120 Hz Display with Punch Hole           1
6.6 inches, 1080 x 2400 px, 144 Hz Display                            1
6.73 inches, 1440 x 3120 px, 120 Hz Display with Punch Hole           1
6.67 inches, 1080 x 2412 px, 120 Hz Display with Punch Hole           1
6.67 inches, 1080 x 2340 px, 144 Hz Display with Punch Hole           1
6.9 inches, 1080 x 2460 px, 120 Hz Display                            1
6.8 inches, 1080 x 2460 px, 90 Hz Display with Punch Hole             1
6.4 inches, 1080 x 2408 px Display with Water Drop Notch              1
6.53 inches, 1080 x 2340 px Display with Punch Hole                   1
6.8 inches, 1440 x 3088 px, 120 Hz Display with Punch Hole            1
5.9 inches, 1080 x 2340 px Display with Water Drop Notch              1
6.7 inches, 1440 x 3040 px Display                                    1
5.84 inches, 1080 x 2280 px Display with Small Notch                  1
6.67 inches, 1080 x 2412 px, 120 Hz Display with Water Drop Notch     1
6.43 inches, 1080 x 2412 px, 120 Hz Display with Punch Hole           1
6.52 inches, 1080 x 2400 px, 90 Hz Display with Punch Hole            1
7.2 inches, 1440 x 1920 px Display                                    1
6.62 inches, 2400 x 1080 px, 120 Hz Display with Punch Hole           1
6.6 inches, 720 x 1612 px Display with Water Drop Notch               1
6 inches, 1080 x 2520 px Display                                      1
6.95 inches, 1080 x 2460 px Display with Punch Hole                   1
6.53 inches, 1080 x 2400 px, 90 Hz Display with Punch Hole            1
6.3 inches, 1080 x 2400 px Display with Punch Hole                    1
6.52 inches, 720 x 1600 px, 90 Hz Display with Punch Hole             1
6.7 inches, 1440 x 3200 px Display with Punch Hole                    1
6.39 inches, 1080 x 2340 px Display                                   1
5 inches, 1080 x 1920 px Display                                      1
6.71 inches, 1284 x 2778 px, 120 Hz Display with Small Notch          1
6.83 inches, 1080 x 2460 px, 120 Hz Display with Punch Hole           1
6.91 inches, 1080 x 2460 px Display with Punch Hole                   1
6.8 inches, 1080 x 2460 px Display with Water Drop Notch              1
6.56 inches, 1080 x 2400 px, 90 Hz Display with Water Drop Notch      1
6.9 inches, 1400 x 3200 px, 120 Hz Display with Punch Hole            1
6.8 inches, 1080 x 2448 px, 165 Hz Display                            1
6.95 inches, 1080 x 2460 px, 90 Hz Display with Punch Hole            1
6.7 inches, 1440 x 3120 px, 120 Hz Display with Punch Hole            1
6.5 inches, 1600 x 720 px, 90 Hz Display with Water Drop Notch        1
6.81 inches, 1080 x 2400 px Display with Punch Hole                   1
4.7 inches, 1080 x 1920 px Display                                    1
6.6 inches, 1440 x 3200 px, 120 Hz Display with Punch Hole            1
6.55 inches, 1080 x 2400 px, 144 Hz Display with Punch Hole           1
6.06 inches, 1170 x 2532 px, 120 Hz Display with Punch Hole           1
6.82 inches, 720 x 1640 px, 90 Hz Display with Water Drop Notch       1
6.67 inches, 1080 x 2412 px, 90 Hz Display with Punch Hole            1
6.73 inches, 1290 x 2796 px, 120 Hz Display                           1
5.9 inches, 1080 x 2400 px, 120 Hz Display with Punch Hole            1
6.2 inches, 720 x 1680 px Display                                     1
3.54 inches, 640 x 960 px Display                                     1
6.1 inches, 720 x 1560 px Display with Water Drop Notch               1
7.92 inches, 2088 x 2250 px Display                                   1
6.52 inches, 720 x 1600 px, 90 Hz Display with Water Drop Notch       1
6.82 inches, 1640 x 720 px, 90 Hz Display with Punch Hole             1
6.5 inches, 720 x 1600 px Display with Small Notch                    1
6.7 inches, 1080 x 2400 px, 165 Hz Display                            1
4.5 inches, 480 x 854 px Display                                      1
6.71 inches, 1440 x 3214 px, 120 Hz Display with Punch Hole           1
6.7 inches, 720 x 1650 px Display with Punch Hole                     1
6.54 inches, 720 x 1560 px Display with Small Notch                   1
6.55 inches, 1612 x 720 px, 90 Hz Display with Water Drop Notch       1
6.81 inches, 1080 x 2388 px Display                                   1
7.8 inches, 1440 x 1920 px Display                                    1
6.36 inches, 1080 x 2400 px, 120 Hz Display with Punch Hole           1
6.82 inches, 720 x 1640 px, 90 Hz Display with Punch Hole             1
5.42 inches, 1080 x 2340 px Display with Punch Hole                   1

In [51]:
df1['sim'].value_counts()

sim
Dual Sim, 3G, 4G, VoLTE, Wi-Fi                               317
Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC                      268
Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi                           155
Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, IR Blaster                54
Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC, IR Blaster           52
Dual Sim, 3G, 4G, VoLTE, Wi-Fi, NFC                           46
Dual Sim, 3G, 4G, VoLTE, Wi-Fi, IR Blaster                    46
Dual Sim, 3G, 4G, Wi-Fi                                        7
Dual Sim, 3G, 4G, 5G, VoLTE, Vo5G, Wi-Fi, NFC                  7
Single Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC                      7
Dual Sim, 3G, 4G, VoLTE, Wi-Fi, NFC, IR Blaster                5
Single Sim, 3G, 4G, VoLTE, Wi-Fi, NFC                          4
Single Sim, 3G, 4G, VoLTE, Wi-Fi                               3
Dual Sim, 3G, 4G, 5G, VoLTE, Vo5G, Wi-Fi                       3
Dual Sim, 3G, 4G, Wi-Fi, NFC                                   2
Single Sim, 3G, 4G, Wi-Fi, NFC                                 1
Single Sim, 3G, 4G, 5G, VoLTE, Wi-Fi                           1
Dual Sim, 3G, 4G, VoLTE                                        1
Dual Sim, 3G, Wi-Fi                                            1
Dual Sim, 3G, 4G, 5G, VoLTE, Vo5G, Wi-Fi, IR Blaster           1
Dual Sim, 3G, 4G, 5G, VoLTE, Vo5G, Wi-Fi, NFC, IR Blaster      1
Name: count, dtype: int64

In [52]:
df1.head()

,index,model,price,rating,sim,processor,ram,battery,display,camera,card,os
0,2,OnePlus 11 5G,54999,89.0,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC","Snapdragon 8 Gen2, Octa Core, 3.2 GHz Processor","12 GB RAM, 256 GB inbuilt",5000 mAh Battery with 100W Fast Charging,"6.7 inches, 1440 x 3216 px, 120 Hz Display wit...",50 MP + 48 MP + 32 MP Triple Rear & 16 MP Fron...,Memory Card Not Supported,Android v13
1,3,OnePlus Nord CE 2 Lite 5G,19989,81.0,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi","Snapdragon 695, Octa Core, 2.2 GHz Processor","6 GB RAM, 128 GB inbuilt",5000 mAh Battery with 33W Fast Charging,"6.59 inches, 1080 x 2412 px, 120 Hz Display wi...",64 MP + 2 MP + 2 MP Triple Rear & 16 MP Front ...,"Memory Card (Hybrid), upto 1 TB",Android v12
2,4,Samsung Galaxy A14 5G,16499,75.0,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi","Exynos 1330, Octa Core, 2.4 GHz Processor","4 GB RAM, 64 GB inbuilt",5000 mAh Battery with 15W Fast Charging,"6.6 inches, 1080 x 2408 px, 90 Hz Display with...",50 MP + 2 MP + 2 MP Triple Rear & 13 MP Front ...,"Memory Card Supported, upto 1 TB",Android v13
3,5,Motorola Moto G62 5G,14999,81.0,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi","Snapdragon 695, Octa Core, 2.2 GHz Processor","6 GB RAM, 128 GB inbuilt",5000 mAh Battery with Fast Charging,"6.55 inches, 1080 x 2400 px, 120 Hz Display wi...",50 MP + 8 MP + 2 MP Triple Rear & 16 MP Front ...,"Memory Card (Hybrid), upto 1 TB",Android v12
4,6,Realme 10 Pro Plus,24999,82.0,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi","Dimensity 1080, Octa Core, 2.6 GHz Processor","6 GB RAM, 128 GB inbuilt",5000 mAh Battery with 67W Fast Charging,"6.7 inches, 1080 x 2412 px, 120 Hz Display wit...",108 MP + 8 MP + 2 MP Triple Rear & 16 MP Front...,Memory Card Not Supported,Android v13

In [53]:
brand_name=df1['model'].str.split(' ').str.get(0)

In [54]:
df1.insert(1,'brand_name',brand_name)

In [55]:
df1['brand_name'] = df1['brand_name'].str.lower()

C:\Users\DEEL\AppData\Local\Temp\ipykernel_17040\3193801224.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df1['brand_name'] = df1['brand_name'].str.lower()

In [56]:
df1.head()

,index,brand_name,model,price,rating,sim,processor,ram,battery,display,camera,card,os
0,2,oneplus,OnePlus 11 5G,54999,89.0,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC","Snapdragon 8 Gen2, Octa Core, 3.2 GHz Processor","12 GB RAM, 256 GB inbuilt",5000 mAh Battery with 100W Fast Charging,"6.7 inches, 1440 x 3216 px, 120 Hz Display wit...",50 MP + 48 MP + 32 MP Triple Rear & 16 MP Fron...,Memory Card Not Supported,Android v13
1,3,oneplus,OnePlus Nord CE 2 Lite 5G,19989,81.0,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi","Snapdragon 695, Octa Core, 2.2 GHz Processor","6 GB RAM, 128 GB inbuilt",5000 mAh Battery with 33W Fast Charging,"6.59 inches, 1080 x 2412 px, 120 Hz Display wi...",64 MP + 2 MP + 2 MP Triple Rear & 16 MP Front ...,"Memory Card (Hybrid), upto 1 TB",Android v12
2,4,samsung,Samsung Galaxy A14 5G,16499,75.0,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi","Exynos 1330, Octa Core, 2.4 GHz Processor","4 GB RAM, 64 GB inbuilt",5000 mAh Battery with 15W Fast Charging,"6.6 inches, 1080 x 2408 px, 90 Hz Display with...",50 MP + 2 MP + 2 MP Triple Rear & 13 MP Front ...,"Memory Card Supported, upto 1 TB",Android v13
3,5,motorola,Motorola Moto G62 5G,14999,81.0,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi","Snapdragon 695, Octa Core, 2.2 GHz Processor","6 GB RAM, 128 GB inbuilt",5000 mAh Battery with Fast Charging,"6.55 inches, 1080 x 2400 px, 120 Hz Display wi...",50 MP + 8 MP + 2 MP Triple Rear & 16 MP Front ...,"Memory Card (Hybrid), upto 1 TB",Android v12
4,6,realme,Realme 10 Pro Plus,24999,82.0,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi","Dimensity 1080, Octa Core, 2.6 GHz Processor","6 GB RAM, 128 GB inbuilt",5000 mAh Battery with 67W Fast Charging,"6.7 inches, 1080 x 2412 px, 120 Hz Display wit...",108 MP + 8 MP + 2 MP Triple Rear & 16 MP Front...,Memory Card Not Supported,Android v13

In [57]:
has_5g = df1['sim'].str.contains('5G')
has_nfc = df1['sim'].str.contains('NFC')
has_ir_blaster = df1['sim'].str.contains('IR Blaster')

In [58]:
df1.insert(6,'has_5g',has_5g)
df1.insert(7,'has_nfc',has_nfc)
df1.insert(8,'has_ir_blaster',has_ir_blaster)

In [59]:
df1.head()

,index,brand_name,model,price,rating,sim,has_5g,has_nfc,has_ir_blaster,processor,ram,battery,display,camera,card,os
0,2,oneplus,OnePlus 11 5G,54999,89.0,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC",True,True,False,"Snapdragon 8 Gen2, Octa Core, 3.2 GHz Processor","12 GB RAM, 256 GB inbuilt",5000 mAh Battery with 100W Fast Charging,"6.7 inches, 1440 x 3216 px, 120 Hz Display wit...",50 MP + 48 MP + 32 MP Triple Rear & 16 MP Fron...,Memory Card Not Supported,Android v13
1,3,oneplus,OnePlus Nord CE 2 Lite 5G,19989,81.0,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi",True,False,False,"Snapdragon 695, Octa Core, 2.2 GHz Processor","6 GB RAM, 128 GB inbuilt",5000 mAh Battery with 33W Fast Charging,"6.59 inches, 1080 x 2412 px, 120 Hz Display wi...",64 MP + 2 MP + 2 MP Triple Rear & 16 MP Front ...,"Memory Card (Hybrid), upto 1 TB",Android v12
2,4,samsung,Samsung Galaxy A14 5G,16499,75.0,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi",True,False,False,"Exynos 1330, Octa Core, 2.4 GHz Processor","4 GB RAM, 64 GB inbuilt",5000 mAh Battery with 15W Fast Charging,"6.6 inches, 1080 x 2408 px, 90 Hz Display with...",50 MP + 2 MP + 2 MP Triple Rear & 13 MP Front ...,"Memory Card Supported, upto 1 TB",Android v13
3,5,motorola,Motorola Moto G62 5G,14999,81.0,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi",True,False,False,"Snapdragon 695, Octa Core, 2.2 GHz Processor","6 GB RAM, 128 GB inbuilt",5000 mAh Battery with Fast Charging,"6.55 inches, 1080 x 2400 px, 120 Hz Display wi...",50 MP + 8 MP + 2 MP Triple Rear & 16 MP Front ...,"Memory Card (Hybrid), upto 1 TB",Android v12
4,6,realme,Realme 10 Pro Plus,24999,82.0,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi",True,False,False,"Dimensity 1080, Octa Core, 2.6 GHz Processor","6 GB RAM, 128 GB inbuilt",5000 mAh Battery with 67W Fast Charging,"6.7 inches, 1080 x 2412 px, 120 Hz Display wit...",108 MP + 8 MP + 2 MP Triple Rear & 16 MP Front...,Memory Card Not Supported,Android v13

In [60]:
processor_name = df1['processor'].str.split(',').str.get(0)

In [61]:
num_cores = df1['processor'].str.split(',').str.get(1)

In [62]:
processor_speed = df1['processor'].str.split(',').str.get(2)

In [63]:
df1.insert(10,'processor_name',processor_name)
df1.insert(11,'num_cores',num_cores)
df1.insert(12,'processor_speed',processor_speed)

In [64]:
df1['processor_name'] = df1['processor_name'].str.strip()

C:\Users\DEEL\AppData\Local\Temp\ipykernel_17040\1632474951.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df1['processor_name'] = df1['processor_name'].str.strip()

In [65]:
temp_df = df1[df1['processor_name'].str.contains('Core')][['processor_name', 'num_cores',	'processor_speed']].shift(1,axis=1)

In [66]:
temp_df.shape

(20, 3)

In [67]:
df1.loc[temp_df.index,['processor_name', 'num_cores',	'processor_speed']] = temp_df.values

In [68]:
df1.loc[856,'processor_name'] = 'Mediatek MT6739'

In [69]:
df1.loc[856]

index                                                858
brand_name                                       samsung
model                            Samsung Galaxy A01 Core
price                                               4999
rating                                               NaN
sim                       Dual Sim, 3G, 4G, VoLTE, Wi-Fi
has_5g                                             False
has_nfc                                            False
has_ir_blaster                                     False
processor          (28 nm), Quad Core, 1.5 GHz Processor
processor_name                           Mediatek MT6739
num_cores                                      Quad Core
processor_speed                        1.5 GHz Processor
ram                              1 GB RAM, 16 GB inbuilt
battery                                 3000 mAh Battery
display                5.3 inches, 720 x 1480 px Display
camera                     8 MP Rear & 5 MP Front Camera
card                               Memory Card Supported
os                                           Android v10
Name: 856, dtype: object

In [70]:
processor_brand = df1['processor_name'].str.split(' ').str.get(0)

In [71]:
df1.insert(11,'processor_brand',processor_brand)

In [72]:
df1.head()

,index,brand_name,model,price,rating,sim,has_5g,has_nfc,has_ir_blaster,processor,processor_name,processor_brand,num_cores,processor_speed,ram,battery,display,camera,card,os
0,2,oneplus,OnePlus 11 5G,54999,89.0,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC",True,True,False,"Snapdragon 8 Gen2, Octa Core, 3.2 GHz Processor",Snapdragon 8 Gen2,Snapdragon,Octa Core,3.2 GHz Processor,"12 GB RAM, 256 GB inbuilt",5000 mAh Battery with 100W Fast Charging,"6.7 inches, 1440 x 3216 px, 120 Hz Display wit...",50 MP + 48 MP + 32 MP Triple Rear & 16 MP Fron...,Memory Card Not Supported,Android v13
1,3,oneplus,OnePlus Nord CE 2 Lite 5G,19989,81.0,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi",True,False,False,"Snapdragon 695, Octa Core, 2.2 GHz Processor",Snapdragon 695,Snapdragon,Octa Core,2.2 GHz Processor,"6 GB RAM, 128 GB inbuilt",5000 mAh Battery with 33W Fast Charging,"6.59 inches, 1080 x 2412 px, 120 Hz Display wi...",64 MP + 2 MP + 2 MP Triple Rear & 16 MP Front ...,"Memory Card (Hybrid), upto 1 TB",Android v12
2,4,samsung,Samsung Galaxy A14 5G,16499,75.0,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi",True,False,False,"Exynos 1330, Octa Core, 2.4 GHz Processor",Exynos 1330,Exynos,Octa Core,2.4 GHz Processor,"4 GB RAM, 64 GB inbuilt",5000 mAh Battery with 15W Fast Charging,"6.6 inches, 1080 x 2408 px, 90 Hz Display with...",50 MP + 2 MP + 2 MP Triple Rear & 13 MP Front ...,"Memory Card Supported, upto 1 TB",Android v13
3,5,motorola,Motorola Moto G62 5G,14999,81.0,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi",True,False,False,"Snapdragon 695, Octa Core, 2.2 GHz Processor",Snapdragon 695,Snapdragon,Octa Core,2.2 GHz Processor,"6 GB RAM, 128 GB inbuilt",5000 mAh Battery with Fast Charging,"6.55 inches, 1080 x 2400 px, 120 Hz Display wi...",50 MP + 8 MP + 2 MP Triple Rear & 16 MP Front ...,"Memory Card (Hybrid), upto 1 TB",Android v12
4,6,realme,Realme 10 Pro Plus,24999,82.0,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi",True,False,False,"Dimensity 1080, Octa Core, 2.6 GHz Processor",Dimensity 1080,Dimensity,Octa Core,2.6 GHz Processor,"6 GB RAM, 128 GB inbuilt",5000 mAh Battery with 67W Fast Charging,"6.7 inches, 1080 x 2412 px, 120 Hz Display wit...",108 MP + 8 MP + 2 MP Triple Rear & 16 MP Front...,Memory Card Not Supported,Android v13

In [73]:
df1['num_cores'].value_counts()

num_cores
 Octa Core              866
 Hexa Core               31
 Quad Core               31
 Octa Core Processor     19
Octa Core Processor       9
 Hexa Core Processor      8
Quad Core                 6
Octa Core                 5
Name: count, dtype: int64

In [74]:
df1['num_cores'] = df1['num_cores'].str.strip()

C:\Users\DEEL\AppData\Local\Temp\ipykernel_17040\2483753889.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df1['num_cores'] = df1['num_cores'].str.strip()

In [75]:
df1['num_cores'].value_counts()

num_cores
Octa Core              871
Quad Core               37
Hexa Core               31
Octa Core Processor     28
Hexa Core Processor      8
Name: count, dtype: int64

In [76]:
df1['num_cores'] = df1['num_cores'].str.replace('Octa Core Processor','Octa Core').str.replace('Hexa Core Processor','Hexa Core')

C:\Users\DEEL\AppData\Local\Temp\ipykernel_17040\3285793486.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df1['num_cores'] = df1['num_cores'].str.replace('Octa Core Processor','Octa Core').str.replace('Hexa Core Processor','Hexa Core')

In [77]:
df1.head()

,index,brand_name,model,price,rating,sim,has_5g,has_nfc,has_ir_blaster,processor,processor_name,processor_brand,num_cores,processor_speed,ram,battery,display,camera,card,os
0,2,oneplus,OnePlus 11 5G,54999,89.0,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC",True,True,False,"Snapdragon 8 Gen2, Octa Core, 3.2 GHz Processor",Snapdragon 8 Gen2,Snapdragon,Octa Core,3.2 GHz Processor,"12 GB RAM, 256 GB inbuilt",5000 mAh Battery with 100W Fast Charging,"6.7 inches, 1440 x 3216 px, 120 Hz Display wit...",50 MP + 48 MP + 32 MP Triple Rear & 16 MP Fron...,Memory Card Not Supported,Android v13
1,3,oneplus,OnePlus Nord CE 2 Lite 5G,19989,81.0,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi",True,False,False,"Snapdragon 695, Octa Core, 2.2 GHz Processor",Snapdragon 695,Snapdragon,Octa Core,2.2 GHz Processor,"6 GB RAM, 128 GB inbuilt",5000 mAh Battery with 33W Fast Charging,"6.59 inches, 1080 x 2412 px, 120 Hz Display wi...",64 MP + 2 MP + 2 MP Triple Rear & 16 MP Front ...,"Memory Card (Hybrid), upto 1 TB",Android v12
2,4,samsung,Samsung Galaxy A14 5G,16499,75.0,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi",True,False,False,"Exynos 1330, Octa Core, 2.4 GHz Processor",Exynos 1330,Exynos,Octa Core,2.4 GHz Processor,"4 GB RAM, 64 GB inbuilt",5000 mAh Battery with 15W Fast Charging,"6.6 inches, 1080 x 2408 px, 90 Hz Display with...",50 MP + 2 MP + 2 MP Triple Rear & 13 MP Front ...,"Memory Card Supported, upto 1 TB",Android v13
3,5,motorola,Motorola Moto G62 5G,14999,81.0,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi",True,False,False,"Snapdragon 695, Octa Core, 2.2 GHz Processor",Snapdragon 695,Snapdragon,Octa Core,2.2 GHz Processor,"6 GB RAM, 128 GB inbuilt",5000 mAh Battery with Fast Charging,"6.55 inches, 1080 x 2400 px, 120 Hz Display wi...",50 MP + 8 MP + 2 MP Triple Rear & 16 MP Front ...,"Memory Card (Hybrid), upto 1 TB",Android v12
4,6,realme,Realme 10 Pro Plus,24999,82.0,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi",True,False,False,"Dimensity 1080, Octa Core, 2.6 GHz Processor",Dimensity 1080,Dimensity,Octa Core,2.6 GHz Processor,"6 GB RAM, 128 GB inbuilt",5000 mAh Battery with 67W Fast Charging,"6.7 inches, 1080 x 2412 px, 120 Hz Display wit...",108 MP + 8 MP + 2 MP Triple Rear & 16 MP Front...,Memory Card Not Supported,Android v13

In [78]:
df1['processor_speed'] = df1['processor_speed'].str.strip().str.split(' ').str.get(0).str.replace('\u2009',' ').str.split(' ').str.get(0).astype(float)

C:\Users\DEEL\AppData\Local\Temp\ipykernel_17040\825004774.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df1['processor_speed'] = df1['processor_speed'].str.strip().str.split(' ').str.get(0).str.replace('\u2009',' ').str.split(' ').str.get(0).astype(float)

In [79]:
df1.head()

,index,brand_name,model,price,rating,sim,has_5g,has_nfc,has_ir_blaster,processor,processor_name,processor_brand,num_cores,processor_speed,ram,battery,display,camera,card,os
0,2,oneplus,OnePlus 11 5G,54999,89.0,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC",True,True,False,"Snapdragon 8 Gen2, Octa Core, 3.2 GHz Processor",Snapdragon 8 Gen2,Snapdragon,Octa Core,3.2,"12 GB RAM, 256 GB inbuilt",5000 mAh Battery with 100W Fast Charging,"6.7 inches, 1440 x 3216 px, 120 Hz Display wit...",50 MP + 48 MP + 32 MP Triple Rear & 16 MP Fron...,Memory Card Not Supported,Android v13
1,3,oneplus,OnePlus Nord CE 2 Lite 5G,19989,81.0,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi",True,False,False,"Snapdragon 695, Octa Core, 2.2 GHz Processor",Snapdragon 695,Snapdragon,Octa Core,2.2,"6 GB RAM, 128 GB inbuilt",5000 mAh Battery with 33W Fast Charging,"6.59 inches, 1080 x 2412 px, 120 Hz Display wi...",64 MP + 2 MP + 2 MP Triple Rear & 16 MP Front ...,"Memory Card (Hybrid), upto 1 TB",Android v12
2,4,samsung,Samsung Galaxy A14 5G,16499,75.0,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi",True,False,False,"Exynos 1330, Octa Core, 2.4 GHz Processor",Exynos 1330,Exynos,Octa Core,2.4,"4 GB RAM, 64 GB inbuilt",5000 mAh Battery with 15W Fast Charging,"6.6 inches, 1080 x 2408 px, 90 Hz Display with...",50 MP + 2 MP + 2 MP Triple Rear & 13 MP Front ...,"Memory Card Supported, upto 1 TB",Android v13
3,5,motorola,Motorola Moto G62 5G,14999,81.0,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi",True,False,False,"Snapdragon 695, Octa Core, 2.2 GHz Processor",Snapdragon 695,Snapdragon,Octa Core,2.2,"6 GB RAM, 128 GB inbuilt",5000 mAh Battery with Fast Charging,"6.55 inches, 1080 x 2400 px, 120 Hz Display wi...",50 MP + 8 MP + 2 MP Triple Rear & 16 MP Front ...,"Memory Card (Hybrid), upto 1 TB",Android v12
4,6,realme,Realme 10 Pro Plus,24999,82.0,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi",True,False,False,"Dimensity 1080, Octa Core, 2.6 GHz Processor",Dimensity 1080,Dimensity,Octa Core,2.6,"6 GB RAM, 128 GB inbuilt",5000 mAh Battery with 67W Fast Charging,"6.7 inches, 1080 x 2412 px, 120 Hz Display wit...",108 MP + 8 MP + 2 MP Triple Rear & 16 MP Front...,Memory Card Not Supported,Android v13

In [80]:
ram_capacity = df1['ram'].str.strip().str.split(',').str.get(0).str.findall(r'\b(\d+)\b').str.get(0)

In [81]:
df1.insert(16,'ram_capacity',ram_capacity)

In [82]:
ram_capacity

0        12
1         6
2         4
3         6
4         6
5         6
6         6
7         8
8         8
9         8
10        6
11        8
12        6
13        6
14        8
15        4
16        3
17       16
18        8
19        4
20        8
21        8
22        6
23        4
24       12
25        8
26        8
27        6
28        8
29        8
30        8
31        6
32        8
33        4
34        6
35        8
36        8
37       12
38        6
39        8
40        6
41        6
42        6
43        8
44        8
45        6
46        4
47        3
48        4
49        8
50        6
51        8
52        4
53        6
54        4
55        4
56        6
57        6
58        8
59        4
60        6
61        8
62        6
63        6
64        6
65        8
66        8
67       12
68        4
69        8
70        3
71       12
72        4
73        8
74        6
75        4
76        6
77        8
78        6
79        4
80        6
81        8
82        4
83        8
84        6
85        6
86        6
87        8
88        6
89        8
90        4
91        8
92        8
93       12
94        4
95        4
96        4
97        8
98       12
99        4
100       6
101       6
102       8
103       8
104       8
105       8
106      12
107       8
108       6
109      12
110       8
111       4
112       6
113       6
114       2
115       8
116       8
117       6
118      16
119       8
120       8
121      12
122       6
123       8
124       8
125       8
126       4
127       8
128       6
129       6
130       4
131       4
132       4
133       8
134       6
135       8
136       4
137       6
138       6
139       8
140       4
141      16
142       4
143       2
144       4
145       4
146       8
147       6
148       4
149       4
150       6
151       4
152       8
153       8
154       8
156       2
157       8
158       6
159      12
160       6
161       4
162       6
163      12
164       8
165       4
166       6
167       8
168       8
169       4
170       4
171       6
172       6
173       6
174       3
175       6
176       6
177       4
178       8
179      12
180       6
181       8
182       3
183       8
184       4
185       8
186       8
187       8
188       4
189       8
190       3
191       4
192       6
193      12
194       8
195       4
196      12
197       6
198       8
199       4
200       8
201       4
202       8
203      12
204       6
205       4
206      12
207       6
208       8
209       8
210       6
211      12
212       6
213       6
214       4
215       8
216      12
217       4
218       8
219       3
220       8
221       6
222       6
223       8
224       6
225       3
226       4
227       6
228       6
229      12
230      12
231       8
232       4
233       8
234       6
235       4
236      12
237       3
238       8
239       8
240       8
241       4
242       8
243       8
244       8
245       6
246       8
247       6
248       8
249       8
250       4
251      12
252       8
253       6
254       6
255       8
256       8
257       8
258       6
259       4
260       6
261       8
262       3
263       4
264       8
265       6
266      12
267       8
268       6
269       8
270       8
272      12
273       4
274       6
275       8
276       8
277       4
278       6
279       4
280      18
281       8
282       6
283       4
284       8
285       8
286       8
287       8
288       8
289       6
290       6
291       6
292       8
293       8
294       4
295       8
296      12
297       8
298       8
299       3
300       2
301       8
302       3
303       4
304       6
305       6
306       8
307       4
308      16
309       4
310       8
311       8
312       8
313      12
314       6
315       2
316       8
317       4
318       8
319       8
320      16
321      12
322       8
323       6
324       8
325       6
326       8
327       6
328      12
329       4
330       6
331       8
332       8
333       8
334       8
335       6
336       4
337       2
338       6
339       8
340       6
341       4
342       8
343       4
344       6
345       6
346       4
347      12
348       8
349       4
350       4
351       4
352       2
353       4
354       8
355       2
356       8
357       4
358       6
359      12
360       8
361       8
362       8
363       4
364      12
365       8
366      12
367       4
368       8
369       8
370      12
371       8
372       6
373       8
374       6
375       8
377       6
378       8
379       8
380       8
381       8
382       3
383       4
384       4
385       8
386       6
387       8
388       4
389       6
390       8
391       6
392       8
393       4
394       8
395       8
396       6
397       4
398       4
399       1
401       8
402       8
403       2
404      12
405       4
406       6
407      12
408      12
409       6
410      18
411       6
412       6
413       3
414       4
415       6
416       8
417      12
418       6
419       6
420       6
421       6
422       8
423       8
424      12
425      12
426      12
427       6
428       8
429       6
430       4
431       2
432       6
433       8
434       8
435       8
436       3
437       4
438       8
439      64
440       8
441       6
442       2
443       6
444       4
445      16
446       6
447       2
448       8
449       4
450       4
451       8
452       8
453       8
454       4
455       4
456       8
457       4
458      12
459       4
460       4
461       4
462      12
463      16
464       8
465       4
466       4
467       4
468       8
469       8
470       8
471       2
472       8
474       4
475       6
476       6
477       1
478       3
479       2
480       2
481       2
482      12
483     512
484       6
485       6
486     512
487       8
488       4
489      12
490       8
491       8
492       4
493      12
494       4
495      12
496       6
497       8
498       4
499       6
500       8
501       4
502       3
503       6
504       8
505       8
506       4
507       2
508       8
509       6
510       3
511       6
512       6
513       6
514       4
515       8
516      12
517       8
518       4
519       8
520       8
521       4
522       6
523       8
524       2
525       6
526       8
527       6
528       8
529       4
530       8
531       4
534       8
535      12
536       3
537       8
538       4
539       4
540       8
541      12
542       8
543       8
544       8
545      12
546       4
547       6
548       8
549       6
550       8
552       4
553       6
554      12
555       4
556       8
557       8
558       3
559       8
560       8
561       8
562       4
563       8
564       4
565       8
566       8
567       6
568      12
569      12
570       8
571       6
572       6
574       3
576       3
577       8
578       8
579       8
580       6
581       4
583       8
584       6
585      12
586       6
587       6
588       4
589       4
590       4
591       8
592       6
593       8
594       8
595       4
596       6
597       3
598       4
599       4
600       4
601       6
602       8
603       8
604       8
605      12
606       4
607       3
609       8
610       4
612       4
613      12
614       8
615       8
616       6
617       8
618       8
619       6
620       8
621       6
622       4
623       6
624       3
625       4
626       8
627      64
628       6
629       8
630      12
631       8
632       4
633       6
634       8
635       4
636       6
637       8
638       8
639       8
641       8
642       8
643      12
644       4
646       6
648       8
649       8
650       4
651      12
652       8
653       4
654       6
655       4
656       3
658       6
659       8
660       8
661       8
662       8
663       6
664       4
666       3
667       8
668       4
669      12
670       4
671       2
672       4
673       6
674       6
675       6
676       8
677       6
678       6
679       6
680       6
681       6
682       8
683       6
684      12
686       8
687       4
688       4
689       2
690       2
691       4
692       8
693      12
694       6
695       6
696       4
697       3
698       8
700       8
701       4
702       6
703       8
704       6
705       4
706       6
707       4
708       8
709       8
710       6
711       6
712       6
713       8
714       6
715       4
716      12
717       4
718       8
719       8
720       8
721      16
722       8
723       8
724       8
725       4
726       8
727       6
728       6
729       8
730       4
731       6
732      12
733       6
734       8
735       1
736       8
737       8
738       2
739       6
740       8
741       6
742      12
743       6
744       1
745       8
746       8
747       8
749       8
750       4
751       8
752       4
753       3
755       6
756       3
758       4
759       8
760      12
761      12
762      64
763       4
764       6
765       8
766       8
767       4
768       8
769      12
770      12
771       3
772       6
773       4
774       8
775       8
776       8
777       8
778       2
779       3
780       2
781       6
782       3
783       8
784       6
785      12
786       3
787       3
788       4
789       4
790      12
791       6
792       4
793       4
794       1
795       4
796       8
797       4
798       8
799       6
800       8
801       3
802       8
803       4
804       4
805       6
806       8
807       4
808       4
809      12
810       8
811       8
812       8
813       6
814       6
815       6
816       6
818       4
819       4
820       6
821       3
822       8
823       3
824       6
825       8
826       6
827      12
828       6
829       8
830       4
831       8
832       4
833       6
834       4
836       8
837       4
838       3
839       4
840       4
841       4
842       8
843       8
844       2
845       8
847       4
848       8
849      16
850       6
851       4
853       6
854       4
855       6
856       1
858       8
859       6
860       4
861       2
862       8
863       4
864       6
865       4
866       4
867       4
868       4
869       4
870       8
871       4
872       4
874      12
875       4
876       8
877       8
878       6
879       6
880       6
883       3
884       8
885       8
886       8
887       8
888       8
889       4
890       8
891      12
892       6
893       8
894       8
895       4
896       8
897       4
898       8
899       6
900       3
901       4
902       6
903       4
904       8
905       8
906       8
907       1
908      12
909       8
910       4
911       4
912       4
913       4
914       4
915       3
916       4
918       3
919       8
920       8
921       8
922       6
923       2
924       3
926       3
928       8
929       4
931       4
933       6
934       8
935       4
936       3
937       3
938       3
939       6
940       4
941       8
942       3
943      12
944       6
945       8
946      12
947       8
948       8
949       4
950       8
951       8
952       4
953       8
954      12
955       8
956       3
957       8
958       6
959       8
960       8
961       6
962       8
963       6
964       6
965       3
966       6
967       6
968       6
969       6
970       4
971       8
972       2
973       6
974       8
975       6
976       4
977       6
978       6
979       6
980       8
981       6
982       4
983       3
984       2
985       8
986       4
987       8
989      12
990      12
991       2
992       2
993       8
994       6
995       4
996       3
997       4
998       4
999       6
1001      6
1002      8
1003      3
1004      8
1005      4
1006      6
1007     12
1008      8
1009      8
1010      4
1011      8
1012      2
1013     12
1014     12
1015      8
1016      6
1017      8
1018      6
1019      8
Name: ram, dtype: object

In [83]:
internal_memory = df1['ram'].str.strip().str.split(',').str.get(1).str.strip().str.findall(r'\b(\d+)\b').str.get(0)

In [84]:
df1.insert(17,'internal_memory',internal_memory)

In [85]:
df1.head()

,index,brand_name,model,price,rating,sim,has_5g,has_nfc,has_ir_blaster,processor,...,num_cores,processor_speed,ram,battery,ram_capacity,internal_memory,display,camera,card,os
0,2,oneplus,OnePlus 11 5G,54999,89.0,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC",True,True,False,"Snapdragon 8 Gen2, Octa Core, 3.2 GHz Processor",...,Octa Core,3.2,"12 GB RAM, 256 GB inbuilt",5000 mAh Battery with 100W Fast Charging,12,256,"6.7 inches, 1440 x 3216 px, 120 Hz Display wit...",50 MP + 48 MP + 32 MP Triple Rear & 16 MP Fron...,Memory Card Not Supported,Android v13
1,3,oneplus,OnePlus Nord CE 2 Lite 5G,19989,81.0,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi",True,False,False,"Snapdragon 695, Octa Core, 2.2 GHz Processor",...,Octa Core,2.2,"6 GB RAM, 128 GB inbuilt",5000 mAh Battery with 33W Fast Charging,6,128,"6.59 inches, 1080 x 2412 px, 120 Hz Display wi...",64 MP + 2 MP + 2 MP Triple Rear & 16 MP Front ...,"Memory Card (Hybrid), upto 1 TB",Android v12
2,4,samsung,Samsung Galaxy A14 5G,16499,75.0,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi",True,False,False,"Exynos 1330, Octa Core, 2.4 GHz Processor",...,Octa Core,2.4,"4 GB RAM, 64 GB inbuilt",5000 mAh Battery with 15W Fast Charging,4,64,"6.6 inches, 1080 x 2408 px, 90 Hz Display with...",50 MP + 2 MP + 2 MP Triple Rear & 13 MP Front ...,"Memory Card Supported, upto 1 TB",Android v13
3,5,motorola,Motorola Moto G62 5G,14999,81.0,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi",True,False,False,"Snapdragon 695, Octa Core, 2.2 GHz Processor",...,Octa Core,2.2,"6 GB RAM, 128 GB inbuilt",5000 mAh Battery with Fast Charging,6,128,"6.55 inches, 1080 x 2400 px, 120 Hz Display wi...",50 MP + 8 MP + 2 MP Triple Rear & 16 MP Front ...,"Memory Card (Hybrid), upto 1 TB",Android v12
4,6,realme,Realme 10 Pro Plus,24999,82.0,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi",True,False,False,"Dimensity 1080, Octa Core, 2.6 GHz Processor",...,Octa Core,2.6,"6 GB RAM, 128 GB inbuilt",5000 mAh Battery with 67W Fast Charging,6,128,"6.7 inches, 1080 x 2412 px, 120 Hz Display wit...",108 MP + 8 MP + 2 MP Triple Rear & 16 MP Front...,Memory Card Not Supported,Android v13

In [86]:
df1['ram_capacity'] = df1['ram_capacity'].astype(float)

C:\Users\DEEL\AppData\Local\Temp\ipykernel_17040\2073605403.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df1['ram_capacity'] = df1['ram_capacity'].astype(float)

In [87]:
df1.drop([486,627],inplace=True)

C:\Users\DEEL\AppData\Local\Temp\ipykernel_17040\2098217776.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df1.drop([486,627],inplace=True)

In [88]:
df1.loc[[483], ['ram_capacity','internal_memory']] = [12.0,'512']

In [89]:
df1['ram_capacity'].value_counts()

ram_capacity
8.0     339
6.0     234
4.0     215
12.0     86
3.0      54
2.0      32
16.0      9
1.0       7
18.0      2
64.0      2
Name: count, dtype: int64

In [90]:
df1['internal_memory'] = df1['internal_memory'].astype(float)

C:\Users\DEEL\AppData\Local\Temp\ipykernel_17040\3988935729.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df1['internal_memory'] = df1['internal_memory'].astype(float)

In [91]:
df1[df1['internal_memory'] == 1]

,index,brand_name,model,price,rating,sim,has_5g,has_nfc,has_ir_blaster,processor,...,num_cores,processor_speed,ram,battery,ram_capacity,internal_memory,display,camera,card,os
290,292,apple,Apple iPhone 14 Pro Max (1TB),182999,78.0,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC",True,True,False,"Bionic A16, Hexa Core Processor",...,Hexa Core,NaN,"6 GB RAM, 1 TB inbuilt",4323 mAh Battery with Fast Charging,6.0,1.0,"6.7 inches, 1290 x 2796 px, 120 Hz Display",48 MP + 12 MP + 12 MP Triple Rear & 12 MP Fron...,Memory Card Not Supported,iOS v16
781,783,apple,Apple iPhone 13 Pro Max (1TB),179900,86.0,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC",True,True,False,"Bionic A15, Hexa Core, 3.22 GHz Processor",...,Hexa Core,3.22,"6 GB RAM, 1 TB inbuilt",4352 mAh Battery with Fast Charging,6.0,1.0,"6.7 inches, 1284 x 2778 px, 120 Hz Display wit...",12 MP + 12 MP + 12 MP Triple Rear & 12 MP Fron...,Memory Card Not Supported,iOS v15
814,816,apple,Apple iPhone 14 Pro (1TB),172999,77.0,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC",True,True,False,"Bionic A16, Hexa Core Processor",...,Hexa Core,NaN,"6 GB RAM, 1 TB inbuilt",3200 mAh Battery with Fast Charging,6.0,1.0,"6.1 inches, 1179 x 2556 px, 120 Hz Display",48 MP + 12 MP + 12 MP Triple Rear & 12 MP Fron...,Memory Card Not Supported,iOS v16
943,945,samsung,Samsung Galaxy Z Fold 4 (12GB RAM + 1TB),163980,NaN,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC",True,True,False,"Snapdragon 8+ Gen1, Octa Core, 3.2 GHz Processor",...,Octa Core,3.20,"12 GB RAM, 1 TB inbuilt",4400 mAh Battery with 25W Fast Charging,12.0,1.0,"7.6 inches, 1812 x 2176 px, 120 Hz Display wit...",50 MP + 12 MP + 10 MP Triple Rear & 10 MP + 4 ...,Memory Card Not Supported,Android v12
961,963,apple,Apple iPhone 13 Pro (1TB),147900,84.0,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC",True,True,False,"Bionic A15, Hexa Core, 3.22 GHz Processor",...,Hexa Core,3.22,"6 GB RAM, 1 TB inbuilt",3095 mAh Battery with Fast Charging,6.0,1.0,"6.1 inches, 1170 x 2532 px, 120 Hz Display wit...",12 MP + 12 MP + 12 MP Triple Rear & 12 MP Fron...,Memory Card Not Supported,iOS v15.0

In [92]:
df1.loc[temp_df.index,'internal_memory'] = 1024

In [93]:
df1['internal_memory'].value_counts()

internal_memory
128.0     517
64.0      183
256.0     157
32.0       63
512.0      21
1024.0     20
16.0       11
1.0         5
8.0         1
Name: count, dtype: int64

In [94]:
battery_capacity = df1['battery'].str.strip().str.split('with').str.get(0).str.strip().str.findall(r'\b(\d+)\b').str.get(0).astype(float)

In [95]:
df1.columns

Index(['index', 'brand_name', 'model', 'price', 'rating', 'sim', 'has_5g',
       'has_nfc', 'has_ir_blaster', 'processor', 'processor_name',
       'processor_brand', 'num_cores', 'processor_speed', 'ram', 'battery',
       'ram_capacity', 'internal_memory', 'display', 'camera', 'card', 'os'],
      dtype='object')

In [96]:
df1.insert(16,'battery_capacity',battery_capacity)

In [97]:
df1['battery'].str.strip().str.split('with').str.get(1).str.strip().str.findall(r'\d{2,3}')

0       [100]
1        [33]
2        [15]
3          []
4        [67]
5        [25]
6          []
7       [120]
8        [33]
9        [80]
10       [33]
11       [33]
12       [67]
13       [18]
14       [45]
15         []
16       [10]
17       [80]
18       [80]
19       [18]
20      [100]
21       [66]
22       [67]
23       [33]
24      [100]
25         []
26       [33]
27         []
28       [44]
29      [100]
30       [33]
31       [67]
32       [67]
33        NaN
34       [25]
35       [25]
36       [66]
37       [45]
38      [210]
39       [67]
40       [67]
41       [67]
42       [30]
43       [67]
44       [44]
45       [25]
46       [33]
47        NaN
48       [10]
49       [33]
50       [15]
51      [120]
52       [18]
53       [30]
54       [33]
55       [18]
56         []
57       [33]
58       [45]
59       [33]
60       [67]
61       [66]
62       [25]
63       [18]
64       [33]
65       [66]
66       [80]
67      [120]
68       [25]
69       [67]
70        NaN
71       [44]
72       [18]
73      [150]
74       [18]
75        NaN
76         []
77       [67]
78       [33]
79        NaN
80       [33]
81       [15]
82       [18]
83       [18]
84       [15]
85       [33]
86       [25]
87       [33]
88       [33]
89       [25]
90       [18]
91         []
92         []
93       [80]
94        NaN
95       [33]
96         []
97      [120]
98       [66]
99       [18]
100        []
101      [33]
102      [68]
103      [33]
104      [50]
105     [120]
106     [120]
107      [25]
108      [44]
109      [80]
110      [45]
111      None
112      [67]
113      [25]
114      [10]
115      [80]
116      [25]
117      [66]
118     [120]
119      [25]
120      [68]
121      [80]
122        []
123      [33]
124      [25]
125      [44]
126      [20]
127      [33]
128      [25]
129        []
130      [18]
131      [18]
132       NaN
133      [33]
134      [67]
135      [67]
136       NaN
137      [18]
138      [33]
139      [80]
140      [18]
141      [67]
142      [33]
143       NaN
144      [18]
145      [15]
146      [66]
147      [25]
148      [18]
149      None
150      [33]
151      [33]
152      [25]
153      [67]
154      [33]
156       NaN
157      [33]
158      [65]
159      [67]
160      [33]
161      [33]
162        []
163      [80]
164     [120]
165      [15]
166      [33]
167      [33]
168      [66]
169      [18]
170       NaN
171      [67]
172      [33]
173      [18]
174        []
175      [18]
176      [33]
177      [33]
178      [18]
179      [44]
180      [33]
181     [180]
182      [10]
183     [125]
184      [25]
185      [33]
186     [120]
187      [30]
188       NaN
189      [10]
190       NaN
191       NaN
192      [25]
193      [65]
194      [68]
195      [18]
196      [80]
197      [33]
198      [67]
199      [15]
200      [33]
201      [25]
202     [125]
203     [120]
204      [33]
205      [18]
206      [33]
207      [25]
208      [18]
209      [67]
210        []
211      [66]
212      [18]
213      [33]
214       NaN
215      [40]
216      [30]
217      [33]
218      [44]
219       NaN
220      [67]
221      [60]
222      [18]
223      [33]
224      [33]
225      [10]
226       NaN
227      [33]
228      [80]
229      [80]
230      [80]
231     [200]
232      [18]
233      [18]
234      [33]
235      [44]
236      [67]
237      [10]
238      [33]
239      [44]
240     [120]
241      [33]
242      [67]
243      [66]
244      [30]
245      [33]
246      [33]
247        []
248      [30]
249      [80]
250      [20]
251      [45]
252      [45]
253      [18]
254      [67]
255      [67]
256      [33]
257      [45]
258      [18]
259      [30]
260      [18]
261      [18]
262       NaN
263        []
264      [25]
265      [33]
266      [65]
267     [100]
268      [67]
269      [66]
270      [15]
272      [30]
273      [33]
274      [18]
275      [67]
276     [120]
277        []
278      [33]
279       NaN
280      [65]
281      [44]
282        []
283      [18]
284     [120]
285      [25]
286      [67]
287      [67]
288      [33]
289      [18]
290        []
291      [15]
292      [33]
293      [33]
294       NaN
295      [25]
296     [125]
297      [33]
298      [67]
299       NaN
300      [10]
301      [67]
302       NaN
303       NaN
304      [18]
305      [33]
306      [15]
307      None
308     [150]
309      [25]
310      [65]
311        []
312      [25]
313      [45]
314      [33]
315       NaN
316      [66]
317      [15]
318      [80]
319      [66]
320     [120]
321      [25]
322       NaN
323        []
324      [25]
325       NaN
326      [30]
327      [33]
328      [25]
329      [18]
330      [18]
331      [33]
332      [66]
333      [25]
334      [30]
335      [67]
336      [33]
337       NaN
338      [20]
339      [65]
340      [33]
341       NaN
342      [33]
343        []
344      [33]
345      [33]
346        []
347     [120]
348     [120]
349      [10]
350      [20]
351      [10]
352       NaN
353       NaN
354     [120]
355      [10]
356      [18]
357      [33]
358       NaN
359      [67]
360      [33]
361     [120]
362     [120]
363      None
364      [45]
365      [44]
366     [150]
367       NaN
368      [25]
369      [33]
370      [30]
371      [33]
372      [33]
373      [25]
374        []
375      [15]
377      [66]
378      [33]
379      [65]
380      [25]
381      [25]
382      [10]
383       NaN
384       NaN
385      [18]
386      [66]
387      [60]
388      [15]
389      [33]
390      [18]
391      [33]
392      [44]
393      [15]
394      [33]
395      [33]
396      [18]
397      [15]
398      [33]
399       NaN
401     [240]
402        []
403      [10]
404      [67]
405      [33]
406      [33]
407      [80]
408      [65]
409      [67]
410     [120]
411      [33]
412      [30]
413      [15]
414      [18]
415      [33]
416      [65]
417      [65]
418       NaN
419      [67]
420        []
421      [33]
422     [125]
423      [67]
424      [66]
425      [80]
426      [44]
427      [18]
428     [120]
429      [33]
430      [33]
431       NaN
432      [15]
433      [33]
434      [67]
435        []
436       NaN
437      [10]
438      [33]
439      None
440      [25]
441      [33]
442       NaN
443      [15]
444      [10]
445      [65]
446     [120]
447       NaN
448      None
449      [18]
450      [18]
451      [80]
452      [19]
453      [33]
454      [15]
455       NaN
456      [30]
457        []
458      [66]
459      [33]
460      [18]
461       NaN
462      [40]
463     [120]
464      [80]
465      [15]
466      [10]
467      [18]
468      [80]
469      [33]
470      [33]
471       NaN
472      [45]
474      [15]
475      [25]
476        []
477       NaN
478       NaN
479      [10]
480       NaN
481       NaN
482      [80]
483      [66]
484      [33]
485      [44]
487      [21]
488        []
489      [30]
490      [45]
491      [66]
492      [18]
493     [135]
494      [18]
495      [80]
496        []
497      [67]
498      [33]
499      [80]
500      [66]
501      [18]
502       NaN
503      [20]
504      [25]
505       NaN
506        []
507      [10]
508      [66]
509      [33]
510       NaN
511      [15]
512      [15]
513      [60]
514      [18]
515      [18]
516     [150]
517     [210]
518      [15]
519      [80]
520        []
521      [44]
522      [33]
523      [60]
524       NaN
525      [33]
526      [65]
527        []
528      [33]
529      [25]
530      [33]
531      [18]
534      [80]
535      [30]
536      [10]
537      [18]
538      [18]
539      [18]
540      [65]
541     [120]
542      [33]
543      [66]
544      [25]
545      [68]
546      [18]
547      [18]
548      [33]
549      [33]
550      [44]
552      [33]
553      [33]
554      [66]
555      [30]
556      [25]
557      [67]
558      [18]
559      [80]
560      [65]
561      [67]
562       NaN
563      [33]
564      [18]
565      [65]
566      [65]
567      [15]
568     [165]
569      [25]
570        []
571      [33]
572      [25]
574       NaN
576       NaN
577       NaN
578      [66]
579     [120]
580      [20]
581      [33]
583     [125]
584      [67]
585      [66]
586      [18]
587      [25]
588       NaN
589      [18]
590      [18]
591      [80]
592     [120]
593      [80]
594     [120]
595       NaN
596       NaN
597       NaN
598      [18]
599      [18]
600      [18]
601      [15]
602      [33]
603      [65]
604      [30]
605      [45]
606      [18]
607       NaN
609      [33]
610       NaN
612      [33]
613      [66]
614      [80]
615      [67]
616      [67]
617      [33]
618      [44]
619      [33]
620      [30]
621      [18]
622      [18]
623      [18]
624       NaN
625       NaN
626      [33]
628      None
629      [21]
630      [18]
631      [25]
632      [15]
633      [67]
634      [80]
635      [10]
636        []
637     [120]
638      [33]
639      [33]
641      [45]
642     [120]
643     [120]
644       NaN
646      [25]
648      [18]
649      [66]
650       NaN
651      [65]
652      [50]
653      [18]
654       NaN
655       NaN
656      [18]
658      [10]
659     [120]
660      [44]
661      [33]
662      [44]
663      [18]
664      [33]
666      [18]
667      [33]
668      [18]
669     [120]
670      [18]
671       NaN
672      [18]
673      [15]
674      [18]
675      [67]
676      [33]
677      [33]
678      [33]
679      [33]
680      [25]
681      [18]
682        []
683      [25]
684        []
686     [120]
687      [15]
688      [15]
689      [10]
690      [18]
691      [18]
692     [120]
693      [33]
694      [15]
695     [120]
696       NaN
697       NaN
698      [30]
700      [80]
701      [18]
702      [67]
703      [33]
704        []
705      [18]
706      [33]
707      [15]
708      [30]
709      [45]
710      [30]
711       NaN
712      [18]
713      [30]
714      [20]
715      [15]
716      [45]
717       NaN
718      [18]
719      [80]
720      [33]
721      [65]
722      [68]
723     [120]
724      [66]
725       NaN
726      [66]
727      [67]
728        []
729      [33]
730       NaN
731       NaN
732     [120]
733      [18]
734      [66]
735       NaN
736      [66]
737      [67]
738       NaN
739      [30]
740      [65]
741      [20]
742      [65]
743      [18]
744       NaN
745      [33]
746      [33]
747      [33]
749      [25]
750      [18]
751      [30]
752      [20]
753       NaN
755        []
756      [10]
758       NaN
759      [67]
760     [120]
761     [100]
762      None
763      [18]
764        []
765      [67]
766      [44]
767      [33]
768      [67]
769      [80]
770      [65]
771       NaN
772      [22]
773      [15]
774      [45]
775      [18]
776      [67]
777      [80]
778       NaN
779      [18]
780       NaN
781        []
782       NaN
783      [44]
784       NaN
785      [67]
786       NaN
787      [15]
788        []
789      [18]
790      [67]
791      [18]
792        []
793       NaN
794       NaN
795      [18]
796      [25]
797      [33]
798      [25]
799      [30]
800      [40]
801       NaN
802        []
803       NaN
804       NaN
805        []
806     [120]
807      [15]
808        []
809        []
810     [120]
811      [18]
812      [80]
813        []
814        []
815      [18]
816      [18]
818       NaN
819      [33]
820      [18]
821      [10]
822     [120]
823      [33]
824      [33]
825        []
826        []
827      [80]
828        []
829      [33]
830       NaN
831      [67]
832      [18]
833      [67]
834      [18]
836      [18]
837      [18]
838       NaN
839      [18]
840        []
841       NaN
842      [65]
843      [67]
844       NaN
845      [33]
847      [18]
848      [33]
849     [120]
850        []
851      [18]
853      None
854      [10]
855      [30]
856       NaN
858      [65]
859       NaN
860      [18]
861       NaN
862      [40]
863      [18]
864      [18]
865      [22]
866      [18]
867      [10]
868      [18]
869      [15]
870      [25]
871       NaN
872       NaN
874      [33]
875      [22]
876      [45]
877      [80]
878      [18]
879      [33]
880       NaN
883       NaN
884      [66]
885      [40]
886        []
887     [120]
888      [80]
889      [18]
890     [150]
891     [120]
892      [33]
893      [33]
894       NaN
895      [18]
896      [44]
897       NaN
898      [65]
899      [30]
900       NaN
901      [18]
902      [67]
903      [20]
904      [65]
905      [30]
906      [30]
907       NaN
908      [25]
909      [65]
910      [65]
911      [15]
912      [18]
913      None
914      None
915       NaN
916      [18]
918       NaN
919      [65]
920      [25]
921      [27]
922      [18]
923       NaN
924       NaN
926       NaN
928        []
929      [18]
931       NaN
933      [33]
934      [80]
935      [10]
936      [10]
937       NaN
938       NaN
939      [55]
940      [10]
941      [67]
942      [10]
943      [25]
944      [33]
945     [125]
946     [150]
947     [100]
948        []
949      [18]
950      [33]
951     [150]
952      [18]
953      [44]
954      [66]
955      [80]
956       NaN
957      [55]
958      [33]
959     [120]
960      [15]
961        []
962      [30]
963       NaN
964      [33]
965       NaN
966      [18]
967      [67]
968      [66]
969        []
970      [18]
971      [66]
972       NaN
973      [15]
974      [65]
975      [18]
976      [15]
977      [15]
978       NaN
979       NaN
980      [33]
981      [18]
982      [18]
983       NaN
984       NaN
985      [30]
986       NaN
987      [30]
989        []
990        []
991      [15]
992       NaN
993      [55]
994        []
995       NaN
996       NaN
997       NaN
998      [10]
999      [22]
1001     [10]
1002     [33]
1003      NaN
1004     [68]
1005      NaN
1006      NaN
1007     [67]
1008     [68]
1009     [80]
1010     [10]
1011    [120]
1012      NaN
1013     [67]
1014     [66]
1015     [68]
1016     [22]
1017     [67]
1018       []
1019       []
Name: battery, dtype: object

In [98]:
fast_charging = df1['battery'].str.strip().str.split('with').str.get(1).str.strip().str.findall(r'\d{2,3}')

In [99]:
df1.insert(17,'fast_charging',fast_charging)

In [100]:
fast_charging

0       [100]
1        [33]
2        [15]
3          []
4        [67]
5        [25]
6          []
7       [120]
8        [33]
9        [80]
10       [33]
11       [33]
12       [67]
13       [18]
14       [45]
15         []
16       [10]
17       [80]
18       [80]
19       [18]
20      [100]
21       [66]
22       [67]
23       [33]
24      [100]
25         []
26       [33]
27         []
28       [44]
29      [100]
30       [33]
31       [67]
32       [67]
33        NaN
34       [25]
35       [25]
36       [66]
37       [45]
38      [210]
39       [67]
40       [67]
41       [67]
42       [30]
43       [67]
44       [44]
45       [25]
46       [33]
47        NaN
48       [10]
49       [33]
50       [15]
51      [120]
52       [18]
53       [30]
54       [33]
55       [18]
56         []
57       [33]
58       [45]
59       [33]
60       [67]
61       [66]
62       [25]
63       [18]
64       [33]
65       [66]
66       [80]
67      [120]
68       [25]
69       [67]
70        NaN
71       [44]
72       [18]
73      [150]
74       [18]
75        NaN
76         []
77       [67]
78       [33]
79        NaN
80       [33]
81       [15]
82       [18]
83       [18]
84       [15]
85       [33]
86       [25]
87       [33]
88       [33]
89       [25]
90       [18]
91         []
92         []
93       [80]
94        NaN
95       [33]
96         []
97      [120]
98       [66]
99       [18]
100        []
101      [33]
102      [68]
103      [33]
104      [50]
105     [120]
106     [120]
107      [25]
108      [44]
109      [80]
110      [45]
111      None
112      [67]
113      [25]
114      [10]
115      [80]
116      [25]
117      [66]
118     [120]
119      [25]
120      [68]
121      [80]
122        []
123      [33]
124      [25]
125      [44]
126      [20]
127      [33]
128      [25]
129        []
130      [18]
131      [18]
132       NaN
133      [33]
134      [67]
135      [67]
136       NaN
137      [18]
138      [33]
139      [80]
140      [18]
141      [67]
142      [33]
143       NaN
144      [18]
145      [15]
146      [66]
147      [25]
148      [18]
149      None
150      [33]
151      [33]
152      [25]
153      [67]
154      [33]
156       NaN
157      [33]
158      [65]
159      [67]
160      [33]
161      [33]
162        []
163      [80]
164     [120]
165      [15]
166      [33]
167      [33]
168      [66]
169      [18]
170       NaN
171      [67]
172      [33]
173      [18]
174        []
175      [18]
176      [33]
177      [33]
178      [18]
179      [44]
180      [33]
181     [180]
182      [10]
183     [125]
184      [25]
185      [33]
186     [120]
187      [30]
188       NaN
189      [10]
190       NaN
191       NaN
192      [25]
193      [65]
194      [68]
195      [18]
196      [80]
197      [33]
198      [67]
199      [15]
200      [33]
201      [25]
202     [125]
203     [120]
204      [33]
205      [18]
206      [33]
207      [25]
208      [18]
209      [67]
210        []
211      [66]
212      [18]
213      [33]
214       NaN
215      [40]
216      [30]
217      [33]
218      [44]
219       NaN
220      [67]
221      [60]
222      [18]
223      [33]
224      [33]
225      [10]
226       NaN
227      [33]
228      [80]
229      [80]
230      [80]
231     [200]
232      [18]
233      [18]
234      [33]
235      [44]
236      [67]
237      [10]
238      [33]
239      [44]
240     [120]
241      [33]
242      [67]
243      [66]
244      [30]
245      [33]
246      [33]
247        []
248      [30]
249      [80]
250      [20]
251      [45]
252      [45]
253      [18]
254      [67]
255      [67]
256      [33]
257      [45]
258      [18]
259      [30]
260      [18]
261      [18]
262       NaN
263        []
264      [25]
265      [33]
266      [65]
267     [100]
268      [67]
269      [66]
270      [15]
272      [30]
273      [33]
274      [18]
275      [67]
276     [120]
277        []
278      [33]
279       NaN
280      [65]
281      [44]
282        []
283      [18]
284     [120]
285      [25]
286      [67]
287      [67]
288      [33]
289      [18]
290        []
291      [15]
292      [33]
293      [33]
294       NaN
295      [25]
296     [125]
297      [33]
298      [67]
299       NaN
300      [10]
301      [67]
302       NaN
303       NaN
304      [18]
305      [33]
306      [15]
307      None
308     [150]
309      [25]
310      [65]
311        []
312      [25]
313      [45]
314      [33]
315       NaN
316      [66]
317      [15]
318      [80]
319      [66]
320     [120]
321      [25]
322       NaN
323        []
324      [25]
325       NaN
326      [30]
327      [33]
328      [25]
329      [18]
330      [18]
331      [33]
332      [66]
333      [25]
334      [30]
335      [67]
336      [33]
337       NaN
338      [20]
339      [65]
340      [33]
341       NaN
342      [33]
343        []
344      [33]
345      [33]
346        []
347     [120]
348     [120]
349      [10]
350      [20]
351      [10]
352       NaN
353       NaN
354     [120]
355      [10]
356      [18]
357      [33]
358       NaN
359      [67]
360      [33]
361     [120]
362     [120]
363      None
364      [45]
365      [44]
366     [150]
367       NaN
368      [25]
369      [33]
370      [30]
371      [33]
372      [33]
373      [25]
374        []
375      [15]
377      [66]
378      [33]
379      [65]
380      [25]
381      [25]
382      [10]
383       NaN
384       NaN
385      [18]
386      [66]
387      [60]
388      [15]
389      [33]
390      [18]
391      [33]
392      [44]
393      [15]
394      [33]
395      [33]
396      [18]
397      [15]
398      [33]
399       NaN
401     [240]
402        []
403      [10]
404      [67]
405      [33]
406      [33]
407      [80]
408      [65]
409      [67]
410     [120]
411      [33]
412      [30]
413      [15]
414      [18]
415      [33]
416      [65]
417      [65]
418       NaN
419      [67]
420        []
421      [33]
422     [125]
423      [67]
424      [66]
425      [80]
426      [44]
427      [18]
428     [120]
429      [33]
430      [33]
431       NaN
432      [15]
433      [33]
434      [67]
435        []
436       NaN
437      [10]
438      [33]
439      None
440      [25]
441      [33]
442       NaN
443      [15]
444      [10]
445      [65]
446     [120]
447       NaN
448      None
449      [18]
450      [18]
451      [80]
452      [19]
453      [33]
454      [15]
455       NaN
456      [30]
457        []
458      [66]
459      [33]
460      [18]
461       NaN
462      [40]
463     [120]
464      [80]
465      [15]
466      [10]
467      [18]
468      [80]
469      [33]
470      [33]
471       NaN
472      [45]
474      [15]
475      [25]
476        []
477       NaN
478       NaN
479      [10]
480       NaN
481       NaN
482      [80]
483      [66]
484      [33]
485      [44]
487      [21]
488        []
489      [30]
490      [45]
491      [66]
492      [18]
493     [135]
494      [18]
495      [80]
496        []
497      [67]
498      [33]
499      [80]
500      [66]
501      [18]
502       NaN
503      [20]
504      [25]
505       NaN
506        []
507      [10]
508      [66]
509      [33]
510       NaN
511      [15]
512      [15]
513      [60]
514      [18]
515      [18]
516     [150]
517     [210]
518      [15]
519      [80]
520        []
521      [44]
522      [33]
523      [60]
524       NaN
525      [33]
526      [65]
527        []
528      [33]
529      [25]
530      [33]
531      [18]
534      [80]
535      [30]
536      [10]
537      [18]
538      [18]
539      [18]
540      [65]
541     [120]
542      [33]
543      [66]
544      [25]
545      [68]
546      [18]
547      [18]
548      [33]
549      [33]
550      [44]
552      [33]
553      [33]
554      [66]
555      [30]
556      [25]
557      [67]
558      [18]
559      [80]
560      [65]
561      [67]
562       NaN
563      [33]
564      [18]
565      [65]
566      [65]
567      [15]
568     [165]
569      [25]
570        []
571      [33]
572      [25]
574       NaN
576       NaN
577       NaN
578      [66]
579     [120]
580      [20]
581      [33]
583     [125]
584      [67]
585      [66]
586      [18]
587      [25]
588       NaN
589      [18]
590      [18]
591      [80]
592     [120]
593      [80]
594     [120]
595       NaN
596       NaN
597       NaN
598      [18]
599      [18]
600      [18]
601      [15]
602      [33]
603      [65]
604      [30]
605      [45]
606      [18]
607       NaN
609      [33]
610       NaN
612      [33]
613      [66]
614      [80]
615      [67]
616      [67]
617      [33]
618      [44]
619      [33]
620      [30]
621      [18]
622      [18]
623      [18]
624       NaN
625       NaN
626      [33]
628      None
629      [21]
630      [18]
631      [25]
632      [15]
633      [67]
634      [80]
635      [10]
636        []
637     [120]
638      [33]
639      [33]
641      [45]
642     [120]
643     [120]
644       NaN
646      [25]
648      [18]
649      [66]
650       NaN
651      [65]
652      [50]
653      [18]
654       NaN
655       NaN
656      [18]
658      [10]
659     [120]
660      [44]
661      [33]
662      [44]
663      [18]
664      [33]
666      [18]
667      [33]
668      [18]
669     [120]
670      [18]
671       NaN
672      [18]
673      [15]
674      [18]
675      [67]
676      [33]
677      [33]
678      [33]
679      [33]
680      [25]
681      [18]
682        []
683      [25]
684        []
686     [120]
687      [15]
688      [15]
689      [10]
690      [18]
691      [18]
692     [120]
693      [33]
694      [15]
695     [120]
696       NaN
697       NaN
698      [30]
700      [80]
701      [18]
702      [67]
703      [33]
704        []
705      [18]
706      [33]
707      [15]
708      [30]
709      [45]
710      [30]
711       NaN
712      [18]
713      [30]
714      [20]
715      [15]
716      [45]
717       NaN
718      [18]
719      [80]
720      [33]
721      [65]
722      [68]
723     [120]
724      [66]
725       NaN
726      [66]
727      [67]
728        []
729      [33]
730       NaN
731       NaN
732     [120]
733      [18]
734      [66]
735       NaN
736      [66]
737      [67]
738       NaN
739      [30]
740      [65]
741      [20]
742      [65]
743      [18]
744       NaN
745      [33]
746      [33]
747      [33]
749      [25]
750      [18]
751      [30]
752      [20]
753       NaN
755        []
756      [10]
758       NaN
759      [67]
760     [120]
761     [100]
762      None
763      [18]
764        []
765      [67]
766      [44]
767      [33]
768      [67]
769      [80]
770      [65]
771       NaN
772      [22]
773      [15]
774      [45]
775      [18]
776      [67]
777      [80]
778       NaN
779      [18]
780       NaN
781        []
782       NaN
783      [44]
784       NaN
785      [67]
786       NaN
787      [15]
788        []
789      [18]
790      [67]
791      [18]
792        []
793       NaN
794       NaN
795      [18]
796      [25]
797      [33]
798      [25]
799      [30]
800      [40]
801       NaN
802        []
803       NaN
804       NaN
805        []
806     [120]
807      [15]
808        []
809        []
810     [120]
811      [18]
812      [80]
813        []
814        []
815      [18]
816      [18]
818       NaN
819      [33]
820      [18]
821      [10]
822     [120]
823      [33]
824      [33]
825        []
826        []
827      [80]
828        []
829      [33]
830       NaN
831      [67]
832      [18]
833      [67]
834      [18]
836      [18]
837      [18]
838       NaN
839      [18]
840        []
841       NaN
842      [65]
843      [67]
844       NaN
845      [33]
847      [18]
848      [33]
849     [120]
850        []
851      [18]
853      None
854      [10]
855      [30]
856       NaN
858      [65]
859       NaN
860      [18]
861       NaN
862      [40]
863      [18]
864      [18]
865      [22]
866      [18]
867      [10]
868      [18]
869      [15]
870      [25]
871       NaN
872       NaN
874      [33]
875      [22]
876      [45]
877      [80]
878      [18]
879      [33]
880       NaN
883       NaN
884      [66]
885      [40]
886        []
887     [120]
888      [80]
889      [18]
890     [150]
891     [120]
892      [33]
893      [33]
894       NaN
895      [18]
896      [44]
897       NaN
898      [65]
899      [30]
900       NaN
901      [18]
902      [67]
903      [20]
904      [65]
905      [30]
906      [30]
907       NaN
908      [25]
909      [65]
910      [65]
911      [15]
912      [18]
913      None
914      None
915       NaN
916      [18]
918       NaN
919      [65]
920      [25]
921      [27]
922      [18]
923       NaN
924       NaN
926       NaN
928        []
929      [18]
931       NaN
933      [33]
934      [80]
935      [10]
936      [10]
937       NaN
938       NaN
939      [55]
940      [10]
941      [67]
942      [10]
943      [25]
944      [33]
945     [125]
946     [150]
947     [100]
948        []
949      [18]
950      [33]
951     [150]
952      [18]
953      [44]
954      [66]
955      [80]
956       NaN
957      [55]
958      [33]
959     [120]
960      [15]
961        []
962      [30]
963       NaN
964      [33]
965       NaN
966      [18]
967      [67]
968      [66]
969        []
970      [18]
971      [66]
972       NaN
973      [15]
974      [65]
975      [18]
976      [15]
977      [15]
978       NaN
979       NaN
980      [33]
981      [18]
982      [18]
983       NaN
984       NaN
985      [30]
986       NaN
987      [30]
989        []
990        []
991      [15]
992       NaN
993      [55]
994        []
995       NaN
996       NaN
997       NaN
998      [10]
999      [22]
1001     [10]
1002     [33]
1003      NaN
1004     [68]
1005      NaN
1006      NaN
1007     [67]
1008     [68]
1009     [80]
1010     [10]
1011    [120]
1012      NaN
1013     [67]
1014     [66]
1015     [68]
1016     [22]
1017     [67]
1018       []
1019       []
Name: battery, dtype: object

In [101]:
df1.insert(16,'fast_charging ',fast_charging )

In [102]:
def fast_charging_extractor(item):

  if type(item) == list:
    if len(item) == 1:
      return item[0]
    else:
      return 0
  else:
    return -1

In [103]:
df1['fast_charging'] = df1['fast_charging'].apply(fast_charging_extractor).astype(int)

C:\Users\DEEL\AppData\Local\Temp\ipykernel_17040\3894870647.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df1['fast_charging'] = df1['fast_charging'].apply(fast_charging_extractor).astype(int)

In [104]:
screen_size = df1['display'].str.strip().str.split(',').str.get(0).str.strip().str.split(' ').str.get(0).astype(float)

In [105]:
df1.insert(21,'screen_size',screen_size)

In [106]:
resolution = df1['display'].str.strip().str.split(',').str.get(1).str.strip().str.split('px').str.get(0)

In [107]:
df1.insert(22,'resolution',resolution)

In [108]:
refresh_rate = df1['display'].str.strip().str.split(',').str.get(2).str.strip().str.findall(r'\d{2,3}').str.get(0).apply(lambda x: 60 if pd.isna(x) else x).astype(int)

In [109]:
df1.insert(22,'refresh_rate',refresh_rate)

In [110]:
df1.head()

,index,brand_name,model,price,rating,sim,has_5g,has_nfc,has_ir_blaster,processor,...,fast_charging,ram_capacity,internal_memory,screen_size,refresh_rate,resolution,display,camera,card,os
0,2,oneplus,OnePlus 11 5G,54999,89.0,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC",True,True,False,"Snapdragon 8 Gen2, Octa Core, 3.2 GHz Processor",...,100,12.0,256.0,6.70,120,1440 x 3216,"6.7 inches, 1440 x 3216 px, 120 Hz Display wit...",50 MP + 48 MP + 32 MP Triple Rear & 16 MP Fron...,Memory Card Not Supported,Android v13
1,3,oneplus,OnePlus Nord CE 2 Lite 5G,19989,81.0,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi",True,False,False,"Snapdragon 695, Octa Core, 2.2 GHz Processor",...,33,6.0,128.0,6.59,120,1080 x 2412,"6.59 inches, 1080 x 2412 px, 120 Hz Display wi...",64 MP + 2 MP + 2 MP Triple Rear & 16 MP Front ...,"Memory Card (Hybrid), upto 1 TB",Android v12
2,4,samsung,Samsung Galaxy A14 5G,16499,75.0,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi",True,False,False,"Exynos 1330, Octa Core, 2.4 GHz Processor",...,15,4.0,64.0,6.60,90,1080 x 2408,"6.6 inches, 1080 x 2408 px, 90 Hz Display with...",50 MP + 2 MP + 2 MP Triple Rear & 13 MP Front ...,"Memory Card Supported, upto 1 TB",Android v13
3,5,motorola,Motorola Moto G62 5G,14999,81.0,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi",True,False,False,"Snapdragon 695, Octa Core, 2.2 GHz Processor",...,0,6.0,128.0,6.55,120,1080 x 2400,"6.55 inches, 1080 x 2400 px, 120 Hz Display wi...",50 MP + 8 MP + 2 MP Triple Rear & 16 MP Front ...,"Memory Card (Hybrid), upto 1 TB",Android v12
4,6,realme,Realme 10 Pro Plus,24999,82.0,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi",True,False,False,"Dimensity 1080, Octa Core, 2.6 GHz Processor",...,67,6.0,128.0,6.70,120,1080 x 2412,"6.7 inches, 1080 x 2412 px, 120 Hz Display wit...",108 MP + 8 MP + 2 MP Triple Rear & 16 MP Front...,Memory Card Not Supported,Android v13

In [111]:
def camera_extractor(text):

  if 'Quad' in text:
    return '4'
  elif 'Triple' in text:
    return '3'
  elif 'Dual' in text:
    return '2'
  elif 'Missing' in text:
    return 'Missing'
  else:
    return '1'

In [112]:
num_rear_cameras = df1['camera'].str.strip().str.split('&').str.get(0).apply(camera_extractor)

In [113]:
df1.insert(25,'num_rear_cameras',num_rear_cameras)

In [114]:
num_front_cameras = df1['camera'].str.strip().str.split('&').str.get(1).str.strip().fillna('Missing').apply(camera_extractor)

In [115]:
df1.insert(26,'num_front_cameras',num_front_cameras)

In [116]:
df1[df1['num_front_cameras'] == 'Missing']

,index,brand_name,model,price,rating,sim,has_5g,has_nfc,has_ir_blaster,processor,...,internal_memory,screen_size,refresh_rate,resolution,display,num_rear_cameras,num_front_cameras,camera,card,os
69,71,oppo,Oppo Find N Fold,99990,NaN,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC",True,True,False,"Snapdragon 8+ Gen1, Octa Core, 3.2 GHz Processor",...,256.0,7.10,120,1792 x 1920,"7.1 inches, 1792 x 1920 px, 120 Hz Display wit...",2,Missing,"Foldable Display, Dual Display",Memory Card Not Supported,Android v12
462,464,xiaomi,Xiaomi Mi Mix Alpha,199990,NaN,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi",True,False,False,"Snapdragon 855+, Octa Core, 2.96 GHz Processor",...,512.0,7.92,60,2088 x 2250,"7.92 inches, 2088 x 2250 px Display",3,Missing,108 MP + 20 MP + 12 MP Triple Rear Camera,Memory Card Not Supported,Android v10
993,995,huawei,Huawei Mate X,169000,NaN,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC, IR Bl...",True,True,True,"Kirin 990, Octa Core, 2.86 GHz Processor",...,512.0,8.00,60,2200 x 2480,"8 inches, 2200 x 2480 px Display",4,Missing,48 MP Quad Rear Camera,Memory Card Not Supported,"Memory Card (Hybrid), upto 256 GB"
1012,1014,itel,itel A23s,4787,NaN,"Dual Sim, 3G, 4G, Wi-Fi",False,False,False,"Spreadtrum SC9832E, Quad Core, 1.4 GHz Processor",...,32.0,5.00,60,854 x 480,"5 inches, 854 x 480 px Display",1,Missing,2 MP Rear Camera,Memory Card Not Supported,Android v11

In [117]:
pd.set_option('display.max_columns',None)

In [118]:
#df1[df1['camera'] == 'Foldable Display, Dual Display']
df1.loc[69,'camera'] == '50 MP'

False

In [119]:
temp_df = df1[df1['camera'] == 'Foldable Display, Dual Display']

In [120]:
df1.loc[temp_df.index, 'camera'] = '50 MP'

In [121]:
df1['primary_camera_rear'] = df1['camera'].str.split(' ').str.get(0).str.replace('\u2009',' ').str.split(' ').str.get(0)

C:\Users\DEEL\AppData\Local\Temp\ipykernel_17040\3974806889.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df1['primary_camera_rear'] = df1['camera'].str.split(' ').str.get(0).str.replace('\u2009',' ').str.split(' ').str.get(0)

In [122]:
df1['primary_camera_front'] = df1['camera'].str.split('&').str.get(1).str.strip().str.split(' ').str.get(0).str.replace('\u2009',' ').str.split(' ').str.get(0)

C:\Users\DEEL\AppData\Local\Temp\ipykernel_17040\1434923224.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df1['primary_camera_front'] = df1['camera'].str.split('&').str.get(1).str.strip().str.split(' ').str.get(0).str.replace('\u2009',' ').str.split(' ').str.get(0)

In [123]:
df1[df1['card'] == 'Memory Card (Hybrid)']

,index,brand_name,model,price,rating,sim,has_5g,has_nfc,has_ir_blaster,processor,processor_name,processor_brand,num_cores,processor_speed,ram,battery,fast_charging,battery_capacity,fast_charging,ram_capacity,internal_memory,screen_size,refresh_rate,resolution,display,num_rear_cameras,num_front_cameras,camera,card,os,primary_camera_rear,primary_camera_front
25,27,samsung,Samsung Galaxy S20 FE 5G,31239,88.0,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC",True,True,False,"Snapdragon 865, Octa Core, 2.84 GHz Processor",Snapdragon 865,Snapdragon,Octa Core,2.84,"8 GB RAM, 128 GB inbuilt",4500 mAh Battery with Fast Charging,[],4500.0,0,8.0,128.0,6.50,120,1080 x 2400,"6.5 inches, 1080 x 2400 px, 120 Hz Display wit...",3,1,12 MP + 12 MP + 8 MP Triple Rear & 32 MP Front...,Memory Card (Hybrid),Android v10,12,32
80,82,motorola,Motorola Moto G72 4G,15999,83.0,"Dual Sim, 3G, 4G, VoLTE, Wi-Fi, NFC",False,True,False,"Helio G99, Octa Core, 2.2 GHz Processor",Helio G99,Helio,Octa Core,2.20,"6 GB RAM, 128 GB inbuilt",5000 mAh Battery with 33W Fast Charging,[33],5000.0,33,6.0,128.0,6.55,120,1080 x 2400,"6.55 inches, 1080 x 2400 px, 120 Hz Display wi...",3,1,108 MP + 8 MP + 2 MP Triple Rear & 16 MP Front...,Memory Card (Hybrid),Android v12,108,16
147,149,samsung,Samsung Galaxy M34 5G,16999,84.0,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC",True,True,False,"Exynos 1200, Octa Core, 2.4 GHz Processor",Exynos 1200,Exynos,Octa Core,2.40,"6 GB RAM, 128 GB inbuilt",6000 mAh Battery with 25W Fast Charging,[25],6000.0,25,6.0,128.0,6.50,120,1080 x 2400,"6.5 inches, 1080 x 2400 px, 120 Hz Display wit...",4,1,64 MP Quad Rear & 32 MP Front Camera,Memory Card (Hybrid),Android v12,64,32
151,153,motorola,Motorola Moto G52,11999,75.0,"Dual Sim, 3G, 4G, VoLTE, Wi-Fi, NFC",False,True,False,"Snapdragon 680, Octa Core, 2.4 GHz Processor",Snapdragon 680,Snapdragon,Octa Core,2.40,"4 GB RAM, 64 GB inbuilt",5000 mAh Battery with 33W Fast Charging,[33],5000.0,33,4.0,64.0,6.60,90,2460 x 1080,"6.6 inches, 2460 x 1080 px, 90 Hz Display with...",3,1,50 MP + 8 MP + 2 MP Triple Rear & 16 MP Front ...,Memory Card (Hybrid),Android v12,50,16
178,180,vivo,Vivo Y75 5G,21990,82.0,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi",True,False,False,"Dimensity 700 5G, Octa Core, 2.2 GHz Processor",Dimensity 700 5G,Dimensity,Octa Core,2.20,"8 GB RAM, 128 GB inbuilt",5000 mAh Battery with 18W Fast Charging,[18],5000.0,18,8.0,128.0,6.58,60,1080 x 2408,"6.58 inches, 1080 x 2408 px Display with Water...",3,1,50 MP + 2 MP + 2 MP Triple Rear & 16 MP Front ...,Memory Card (Hybrid),Android v12,50,16
204,206,motorola,Motorola Moto G52 (6GB RAM + 128GB),12999,79.0,"Dual Sim, 3G, 4G, VoLTE, Wi-Fi, NFC",False,True,False,"Snapdragon 680, Octa Core, 2.4 GHz Processor",Snapdragon 680,Snapdragon,Octa Core,2.40,"6 GB RAM, 128 GB inbuilt",5000 mAh Battery with 33W Fast Charging,[33],5000.0,33,6.0,128.0,6.60,90,2460 x 1080,"6.6 inches, 2460 x 1080 px, 90 Hz Display with...",3,1,50 MP + 8 MP + 2 MP Triple Rear & 16 MP Front ...,Memory Card (Hybrid),Android v12,50,16
248,250,motorola,Motorola Moto G73,25999,85.0,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC",True,True,False,"Dimensity 930, Octa Core, 2.2 GHz Processor",Dimensity 930,Dimensity,Octa Core,2.20,"8 GB RAM, 256 GB inbuilt",5000 mAh Battery with 30W Fast Charging,[30],5000.0,30,8.0,256.0,6.50,120,1080 x 2400,"6.5 inches, 1080 x 2400 px, 120 Hz Display wit...",2,1,50 MP + 8 MP Dual Rear & 16 MP Front Camera,Memory Card (Hybrid),Android v13,50,16
254,256,xiaomi,Xiaomi Redmi Note 11 Pro 5G,17990,81.0,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, IR Blaster",True,False,True,"Snapdragon 695, Octa Core, 2.2 GHz Processor",Snapdragon 695,Snapdragon,Octa Core,2.20,"6 GB RAM, 64 GB inbuilt",5000 mAh Battery with 67W Fast Charging,[67],5000.0,67,6.0,64.0,6.67,120,1080 x 2400,"6.67 inches, 1080 x 2400 px, 120 Hz Display wi...",3,1,108 MP + 8 MP + 2 MP Triple Rear & 16 MP Front...,Memory Card (Hybrid),Android v11,108,16
281,283,vivo,Vivo V23e 5G,21994,84.0,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi",True,False,False,"Dimensity 810 5G, Octa Core, 2.4 GHz Processor",Dimensity 810 5G,Dimensity,Octa Core,2.40,"8 GB RAM, 128 GB inbuilt",4050 mAh Battery with 44W Fast Charging,[44],4050.0,44,8.0,128.0,6.44,60,1080 x 2400,"6.44 inches, 1080 x 2400 px Display with Water...",3,1,50 MP + 8 MP + 2 MP Triple Rear & 44 MP Front ...,Memory Card (Hybrid),Android v12,50,44
305,307,xiaomi,Xiaomi Mi 11 Lite NE 5G,21890,83.0,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC, IR Bl...",True,True,True,"Snapdragon 778G , Octa Core, 2.4 GHz Processor",Snapdragon 778G,Snapdragon,Octa Core,2.40,"6 GB RAM, 128 GB inbuilt",4250 mAh Battery with 33W Fast Charging,[33],4250.0,33,6.0,128.0,6.55,90,1080 x 2400,"6.55 inches, 1080 x 2400 px, 90 Hz Display wit...",3,1,64 MP + 8 MP + 5 MP Triple Rear & 20 MP Front ...,Memory Card (Hybrid),Android v11,64,20
441,443,poco,Poco X3 Pro,19650,82.0,"Dual Sim, 3G, 4G, VoLTE, Wi-Fi, IR Blaster",False,False,True,"Snapdragon 860, Octa Core, 2.96 GHz Processor",Snapdragon 860,Snapdragon,Octa Core,2.96,"6 GB RAM, 128 GB inbuilt",5160 mAh Battery with 33W Fast Charging,[33],5160.0,33,6.0,128.0,6.67,120,1080 x 2400,"6.67 inches, 1080 x 2400 px, 120 Hz Display wi...",4,1,48 MP Quad Rear & 20 MP Front Camera,Memory Card (Hybrid),Android v11,48,20
470,472,xiaomi,Xiaomi Mi 11 Lite NE 5G (8GB RAM + 128GB),22999,86.0,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC, IR Bl...",True,True,True,"Snapdragon 778G , Octa Core, 2.4 GHz Processor",Snapdragon 778G,Snapdragon,Octa Core,2.40,"8 GB RAM, 128 GB inbuilt",4250 mAh Battery with 33W Fast Charging,[33],4250.0,33,8.0,128.0,6.55,90,1080 x 2400,"6.55 inches, 1080 x 2400 px, 90 Hz Display wit...",3,1,64 MP + 8 MP + 5 MP Triple Rear & 20 MP Front ...,Memory Card (Hybrid),Android v11,64,20
487,489,sony,Sony Xperia 5 II,69990,86.0,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC",True,True,False,"Snapdragon 865 , Octa Core, 2.84 GHz Processor",Snapdragon 865,Snapdragon,Octa Core,2.84,"8 GB RAM, 128 GB inbuilt",4000 mAh Battery with 21W Fast Charging,[21],4000.0,21,8.0,128.0,6.10,120,1080 x 2520,"6.1 inches, 1080 x 2520 px, 120 Hz Display",3,1,12 MP + 12 MP + 12 MP Triple Rear & 8 MP Front...,Memory Card (Hybrid),Android v10,12,8
489,491,sony,Sony Xperia 1 IV (12GB RAM + 512GB),92980,NaN,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC",True,True,False,"Snapdragon 8 Gen1, Octa Core, 3 GHz Processor",Snapdragon 8 Gen1,Snapdragon,Octa Core,3.00,"12 GB RAM, 512 GB inbuilt",5000 mAh Battery with 30W Fast Charging,[30],5000.0,30,12.0,512.0,6.50,120,1644 x 3840,"6.5 inches, 1644 x 3840 px, 120 Hz Display",4,1,12 MP Quad Rear & 12 MP Front Camera,Memory Card (Hybrid),Android v12,12,12
513,515,realme,Realme Q5 5G,14990,78.0,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi",True,False,False,"Snapdragon 695, Octa Core, 2.2 GHz Processor",Snapdragon 695,Snapdragon,Octa Core,2.20,"6 GB RAM, 128 GB inbuilt",5000 mAh Battery with 60W Fast Charging,[60],5000.0,60,6.0,128.0,6.60,120,1080 x 2412,"6.6 inches, 1080 x 2412 px, 120 Hz Display wit...",3,1,50 MP + 2 MP + 2 MP Triple Rear & 16 MP Front ...,Memory Card (Hybrid),Android v12,50,16
580,582,nokia,Nokia G60,28498,81.0,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC",True,True,False,"Snapdragon 695, Octa Core, 2.2 GHz Processor",Snapdragon 695,Snapdragon,Octa Core,2.20,"6 GB RAM, 128 GB inbuilt",4500 mAh Battery with 20W Fast Charging,[20],4500.0,20,6.0,128.0,6.58,120,1080 x 2400,"6.58 inches, 1080 x 2400 px, 120 Hz Display wi...",3,1,50 MP + 5 MP + 2 MP Triple Rear & 8 MP Front C...,Memory Card (Hybrid),Android v12,50,8
602,604,vivo,Vivo V21,24999,83.0,"Dual Sim, 3G, 4G, VoLTE, Wi-Fi",False,False,False,"Dimensity 800U, Octa Core, 2.4 GHz Processor",Dimensity 800U,Dimensity,Octa Core,2.40,"8 GB RAM, 128 GB inbuilt",4000 mAh Battery with 33W Fast Charging,[33],4000.0,33,8.0,128.0,6.44,90,1080 x 2400,"6.44 inches, 1080 x 2400 px, 90 Hz Display wit...",3,1,64 MP + 8 MP + 2 MP Triple Rear & 44 MP Front ...,Memory Card (Hybrid),Android v11,64,44
626,628,vivo,Vivo V21 5G,23994,85.0,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi",True,False,False,"Dimensity 800U, Octa Core, 2.4 GHz Processor",Dimensity 800U,Dimensity,Octa Core,2.40,"8 GB RAM, 128 GB inbuilt",4000 mAh Battery with 33W Fast Charging,[33],4000.0,33,8.0,128.0,6.44,90,1080 x 2400,"6.44 inches, 1080 x 2400 px, 90 Hz Display wit...",3,1,64 MP + 8 MP + 2 MP Triple Rear & 44 MP Front ...,Memory Card (Hybrid),Android v11,64,44
629,631,sony,Sony Xperia 1 II,69999,89.0,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC",True,True,False,"Snapdragon 865 , Octa Core, 2.84 GHz Processor",Snapdragon 865,Snapdragon,Octa Core,2.84,"8 GB RAM, 256 GB inbuilt",4000 mAh Battery with 21W Fast Charging,[21],4000.0,21,8.0,256.0,6.50,60,1644 x 3840,"6.5 inches, 1644 x 3840 px Display",4,1,12 MP Quad Rear & 8 MP Front Camera,Memory Card (Hybrid),Android v10,12,8
662,664,vivo,Vivo V25e,19990,84.0,"Dual Sim, 3G, 4G, VoLTE, Wi-Fi",False,False,False,"Helio G99, Octa Core, 2.2 GHz Processor",Helio G99,Helio,Octa Core,2.20,"8 GB RAM, 256 GB inbuilt",4500 mAh Battery with 44W Fast Charging,[44],4500.0,44,8.0,256.0,6.44,90,1080 x 2400,"6.44 inches, 1080 x 2400 px, 90 Hz Display wit...",3,1,64 MP + 2 MP + 2 MP Triple Rear & 32 MP Front ...,Memory Card (Hybrid),Android v12,64,32
680,682,lg,LG Velvet 5G,54999,85.0,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC",True,True,False,"Snapdragon 765G, Octa Core, 2.4 GHz Processor",Snapdragon 765G,Snapdragon,Octa Core,2.40,"6 GB RAM, 128 GB inbuilt",4300 mAh Battery with 25W Fast Charging,[25],4300.0,25,6.0,128.0,6.80,60,1080 x 2460,"6.8 inches, 1080 x 2460 px Display with Water ...",3,1,48 MP + 8 MP + 5 MP Triple Rear & 16 MP Front ...,Memory Card (Hybrid),Android v10,48,16
696,698,honor,Honor Play 30,9999,68.0,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi",True,False,False,"Snapdragon 480+, Octa Core, 2.2 GHz Processor",Snapdragon 480+,Snapdragon,Octa Core,2.20,"4 GB RAM, 128 GB inbuilt",5000 mAh Battery,NaN,5000.0,-1,4.0,128.0,6.50,60,720 x 1600,"6.5 inches, 720 x 1600 px Display with Water D...",1,1,13 MP Rear & 5 MP Front Camera,Memory Card (Hybrid),Android v11,13,5
698,700,sony,Sony Xperia 5 IV 5G,82199,89.0,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC",True,True,False,"Snapdragon 8 Gen1, Octa Core, 3 GHz Processor",Snapdragon 8 Gen1,Snapdragon,Octa Core,3.00,"8 GB RAM, 256 GB inbuilt",5000 mAh Battery with 30W Fast Charging,[30],5000.0,30,8.0,256.0,6.10,120,1080 x 2520,"6.1 inches, 1080 x 2520 px, 120 Hz Display",3,1,12 MP + 12 MP + 12 MP Triple Rear & 12 MP Fron...,Memory Card (Hybrid),Android v12,12,12
720,722,vivo,Vivo V21s,29999,86.0,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC",True,True,False,"Dimensity 800U , Octa Core, 2.4 GHz Processor",Dimensity 800U,Dimensity,Octa Core,2.40,"8 GB RAM, 128 GB inbuilt",4000 mAh Battery with 33W Fast Charging,[33],4000.0,33,8.0,128.0,6.44,90,1080 x 2400,"6.44 inches, 1080 x 2400 px, 90 Hz Display wit...",3,1,64 MP + 8 MP + 2 MP Triple Rear & 44 MP Front ...,Memory Card (Hybrid),Android v12,64,44
767,769,motorola,Motorola Moto G52 5G,16999,76.0,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC",True,True,False,"Snapdragon 695, Octa Core, 2.2 GHz Processor",Snapdragon 695,Snapdragon,Octa Core,2.20,"4 GB RAM, 64 GB inbuilt",5000 mAh Battery with 33W Fast Charging,[33],5000.0,33,4.0,64.0,6.60,90,2460 x 1080,"6.6 inches, 2460 x 1080 px, 90 Hz Display with...",3,1,50 MP + 8 MP + 2 MP Triple Rear & 16 MP Front ...,Memory Card (Hybrid),Android v12,50,16
860,862,sony,Sony Xperia 10 II,27999,75.0,"Dual Sim, 3G, 4G, VoLTE, Wi-Fi, NFC",False,True,False,"Snapdragon 665, Octa Core, 2 GHz Processor",Snapdragon 665,Snapdragon,Octa Core,2.00,"4 GB RAM, 128 GB inbuilt",3600 mAh Battery with 18W Fast Charging,[18],3600.0,18,4.0,128.0,6.00,90,1080 x 2520,"6 inches, 1080 x 2520 px, 90 Hz Display",3,1,12 MP + 8 MP + 8 MP Triple Rear & 8 MP Front C...,Memory Card (Hybrid),Android v10.0,12,8
875,877,huawei,Huawei Nova Y61,21990,63.0,"Dual Sim, 3G, 4G, VoLTE, Wi-Fi",False,False,False,Octa Core Processor,None,None,Octa Core,NaN,"4 GB RAM, 64 GB inbuilt",5000 mAh Battery with 22.5W Fast Charging,[22],5000.0,22,4.0,1024.0,6.52,60,720 x 1600,"6.52 inches, 720 x 1600 px Display with Water ...",3,1,50 MP + 2 MP Triple Rear & 5 MP Front Camera,Memory Card (Hybrid),EMUI v12,50,5
939,941,zte,ZTE Axon 30S,19999,82.0,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC",True,True,False,"Snapdragon 870 , Octa Core, 3.2 GHz Processor",Snapdragon 870,Snapdragon,Octa Core,3.20,"6 GB RAM, 128 GB inbuilt",4200 mAh Battery with 55W Fast Charging,[55],4200.0,55,6.0,128.0,6.90,120,1080 x 2460,"6.9 inches, 1080 x 2460 px, 120 Hz Display",4,1,50 MP Quad Rear & 16 MP Front Camera,Memory Card (Hybrid),Android v12,50,16
940,942,honor,Honor X6,13999,71.0,"Dual Sim, 3G, 4G, VoLTE, Wi-Fi",False,False,False,"Helio G25, Octa Core, 2 GHz Processor",Helio G25,Helio,Octa Core,2.00,"4 GB RAM, 64 GB inbuilt",5000 mAh Battery with 10W Fast Charging,[10],5000.0,10,4.0,64.0,6.50,60,720 x 1600,"6.5 inches, 720 x 1600 px Display with Water D...",3,1,50 MP + 2 MP + 2 MP Triple Rear & 5 MP Front C...,Memory Card (Hybrid),Android v12,50,5
942,944,tcl,TCL Ion X,8990,60.0,"Dual Sim, 3G, 4G, VoLTE, Wi-Fi",False,False,False,"Helio G25, Octa Core, 2 GHz Processor",Helio G25,Helio,Octa Core,2.00,"3 GB RAM, 32 GB inbuilt",3000 mAh Battery with 10W Fast Charging,[10],3000.0,10,3.0,32.0,6.00,60,720 x 1440,"6 inches, 720 x 1440 px Display",1,1,13 MP Rear & 5 MP Front Camera,Memory Card (Hybrid),Android,13,5

In [124]:
df1.loc[temp_df.index, 'card'] = 'Not Specified'

In [125]:
df1['extended_memory'] = df1['card'].apply(lambda x:'0' if 'Not' in x else x.split('upto')).str.get(-1).str.strip().str.replace('Memory Card Supported','Not Specified')

C:\Users\DEEL\AppData\Local\Temp\ipykernel_17040\1471866915.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df1['extended_memory'] = df1['card'].apply(lambda x:'0' if 'Not' in x else x.split('upto')).str.get(-1).str.strip().str.replace('Memory Card Supported','Not Specified')

In [126]:
df1[df1['os'].str.contains('Memory Card')]

,index,brand_name,model,price,rating,sim,has_5g,has_nfc,has_ir_blaster,processor,processor_name,processor_brand,num_cores,processor_speed,ram,battery,fast_charging,battery_capacity,fast_charging,ram_capacity,internal_memory,screen_size,refresh_rate,resolution,display,num_rear_cameras,num_front_cameras,camera,card,os,primary_camera_rear,primary_camera_front,extended_memory
159,161,oppo,Oppo Find N2 5G,94990,NaN,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC",True,True,False,"Snapdragon 8+ Gen1, Octa Core, 3.2 GHz Processor",Snapdragon 8+ Gen1,Snapdragon,Octa Core,3.20,"12 GB RAM, 256 GB inbuilt",4520 mAh Battery with 67W Fast Charging,[67],4520.0,67,12.0,256.0,7.10,120,1792 x 1920,"7.1 inches, 1792 x 1920 px, 120 Hz Display wit...",3,2,50 MP + 48 MP + 32 MP Triple Rear & 32 MP + 32...,Memory Card Not Supported,Memory Card Not Supported,50,32,0
306,308,samsung,Samsung Galaxy Z Flip 3,69999,84.0,"Single Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC",True,True,False,"Snapdragon 888, Octa Core, 2.84 GHz Processor",Snapdragon 888,Snapdragon,Octa Core,2.84,"8 GB RAM, 128 GB inbuilt",3300 mAh Battery with 15W Fast Charging,[15],3300.0,15,8.0,128.0,6.70,120,1080 x 2640,"6.7 inches, 1080 x 2640 px, 120 Hz Display wit...",2,1,12 MP + 12 MP Dual Rear & 10 MP Front Camera,Memory Card Not Supported,Memory Card Not Supported,12,10,0
322,324,royole,Royole FlexPai 2,109999,87.0,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi",True,False,False,"Snapdragon 865, Octa Core, 2.84 GHz Processor",Snapdragon 865,Snapdragon,Octa Core,2.84,"8 GB RAM, 128 GB inbuilt",4450 mAh Battery,NaN,4450.0,-1,8.0,128.0,7.80,60,1440 x 1920,"7.8 inches, 1440 x 1920 px Display",3,1,64 MP + 16 MP + 8 MP Triple Rear & 32 MP Front...,Memory Card Not Supported,"Memory Card Supported, upto 256 GB",64,32,0
365,367,oppo,OPPO Find N Flip,89990,88.0,"Single Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC",True,True,False,"Dimensity 9000, Octa Core, 3.05 GHz Processor",Dimensity 9000,Dimensity,Octa Core,3.05,"8 GB RAM, 128 GB inbuilt",4300 mAh Battery with 44W Fast Charging,[44],4300.0,44,8.0,128.0,6.80,120,1200 x 2400,"6.8 inches, 1200 x 2400 px, 120 Hz Display wit...",2,1,50 MP + 8 MP Dual Rear & 32 MP Front Camera,Memory Card Not Supported,Memory Card Not Supported,50,32,0
392,394,oppo,OPPO Find N2 Flip,70990,88.0,"Single Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC",True,True,False,"Dimensity 9000 Plus, Octa Core, 3.2 GHz Processor",Dimensity 9000 Plus,Dimensity,Octa Core,3.20,"8 GB RAM, 256 GB inbuilt",4300 mAh Battery with 44W Fast Charging,[44],4300.0,44,8.0,256.0,6.80,120,1080 x 2520,"6.8 inches, 1080 x 2520 px, 120 Hz Display wit...",2,1,50 MP + 8 MP Dual Rear & 32 MP Front Camera,Memory Card Not Supported,Memory Card Not Supported,50,32,0
504,506,samsung,Samsung Galaxy Z Flip 4 5G,89999,88.0,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC",True,True,False,"Snapdragon 8+ Gen1, Octa Core, 3.2 GHz Processor",Snapdragon 8+ Gen1,Snapdragon,Octa Core,3.20,"8 GB RAM, 128 GB inbuilt",3700 mAh Battery with 25W Fast Charging,[25],3700.0,25,8.0,128.0,6.70,120,1080 x 2640,"6.7 inches, 1080 x 2640 px, 120 Hz Display wit...",2,1,12 MP + 12 MP Dual Rear & 10 MP Front Camera,Memory Card Not Supported,Memory Card Not Supported,12,10,0
570,572,lg,LG Wing 5G,54999,89.0,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC",True,True,False,"Snapdragon 765G , Octa Core, 2.4 GHz Processor",Snapdragon 765G,Snapdragon,Octa Core,2.40,"8 GB RAM, 128 GB inbuilt",4000 mAh Battery with Fast Charging,[],4000.0,0,8.0,128.0,6.80,60,1080 x 2460,"6.8 inches, 1080 x 2460 px Display",3,1,64 MP + 13 MP + 12 MP Triple Rear & 32 MP Fron...,Memory Card Not Supported,"Memory Card (Hybrid), upto 2 TB",64,32,0
613,615,oukitel,Oukitel WP21,22990,82.0,"Dual Sim, 3G, 4G, VoLTE, Wi-Fi",False,False,False,"Helio G99, Octa Core, 2.2 GHz Processor",Helio G99,Helio,Octa Core,2.20,"12 GB RAM, 256 GB inbuilt",9800 mAh Battery with 66W Fast Charging,[66],9800.0,66,12.0,256.0,6.78,120,1080 x 2400,"6.78 inches, 1080 x 2400 px, 120 Hz Display",3,1,64 MP + 20 MP + 2 MP Triple Rear & Main Front ...,Memory Card Not Supported,Memory Card (Hybrid),64,Main,0
682,684,lg,LG V60 ThinQ,79990,NaN,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC",True,True,False,"Snapdragon 865, Octa Core, 2.84 GHz Processor",Snapdragon 865,Snapdragon,Octa Core,2.84,"8 GB RAM, 128 GB inbuilt",5000 mAh Battery with Fast Charging,[],5000.0,0,8.0,128.0,6.80,60,1080 x 2460,"6.8 inches, 1080 x 2460 px Display with Punch ...",3,1,64 MP + 13 MP + 0.3 MP Triple Rear & 10 MP Fro...,Memory Card Not Supported,"Memory Card (Hybrid), upto 2 TB",64,10,0
721,723,asus,Asus ROG Phone 6D Ultimate,107990,NaN,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC",True,True,False,"Dimensity 9000 Plus, Octa Core, 3.2 GHz Processor",Dimensity 9000 Plus,Dimensity,Octa Core,3.20,"16 GB RAM, 512 GB inbuilt",6000 mAh Battery with 65W Fast Charging,[65],6000.0,65,16.0,512.0,6.78,165,1080 x 2448,"6.78 inches, 1080 x 2448 px, 165 Hz Display",3,1,50 MP + 13 MP + 5 MP Triple Rear & 12 MP Front...,Memory Card Not Supported,Memory Card Not Supported,50,12,0
726,728,huawei,Huawei Mate Xs 2,162990,89.0,"Dual Sim, 3G, 4G, VoLTE, Wi-Fi, NFC, IR Blaster",False,True,True,"Snapdragon 888, Octa Core, 2.84 GHz Processor",Snapdragon 888,Snapdragon,Octa Core,2.84,"8 GB RAM, 512 GB inbuilt",4600 mAh Battery with 66W Fast Charging,[66],4600.0,66,8.0,512.0,7.80,120,2200 x 2480,"7.8 inches, 2200 x 2480 px, 120 Hz Display wit...",3,1,50 MP + 13 MP + 8 MP Triple Rear & 10.7 MP Fro...,Memory Card Not Supported,"Memory Card (Hybrid), upto 256 GB",50,10.7,0
844,846,cat,CAT S22 Flip,14999,NaN,"Single Sim, 3G, 4G, VoLTE, Wi-Fi",False,False,False,"Qualcomm 215, Quad Core, 1.3 GHz Processor",Qualcomm 215,Qualcomm,Quad Core,1.30,"2 GB RAM, 16 GB inbuilt",2000 mAh Battery,NaN,2000.0,-1,2.0,16.0,4.00,60,480 x 640,"4 inches, 480 x 640 px Display",1,1,5 MP Rear & 2 MP Front Camera,Memory Card Not Supported,"Memory Card Supported, upto 128 GB",5,2,0
894,896,royole,Royole FlexPai 3 5G,149999,87.0,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi",True,False,False,"Snapdragon 888, Octa Core, 2.84 GHz Processor",Snapdragon 888,Snapdragon,Octa Core,2.84,"8 GB RAM, 128 GB inbuilt",3360 mAh Battery,NaN,3360.0,-1,8.0,128.0,7.20,60,1440 x 1920,"7.2 inches, 1440 x 1920 px Display",3,1,64 MP + 16 MP + 8 MP Triple Rear & 32 MP Front...,Memory Card Not Supported,"Memory Card Supported, upto 256 GB",64,32,0
993,995,huawei,Huawei Mate X,169000,NaN,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC, IR Bl...",True,True,True,"Kirin 990, Octa Core, 2.86 GHz Processor",Kirin 990,Kirin,Octa Core,2.86,"8 GB RAM, 512 GB inbuilt",4500 mAh Battery with 55W Fast Charging,[55],4500.0,55,8.0,512.0,8.00,60,2200 x 2480,"8 inches, 2200 x 2480 px Display",4,Missing,48 MP Quad Rear Camera,Memory Card Not Supported,"Memory Card (Hybrid), upto 256 GB",48,NaN,0

In [127]:
df1.loc[temp_df.index, 'os'] = 'Not Specified'

In [128]:
df1['os'].value_counts()

os
Android v12                           393
Android v11                           274
Android v13                            91
Android v10                            69
Android v9.0 (Pie)                     29
Android v10.0                          23
iOS v16                                15
iOS v15                                12
Android v8.1 (Oreo)                    10
Memory Card Not Supported               6
iOS v14                                 6
Android v8.0 (Oreo)                     4
Android v11.0                           4
iOS v13                                 4
iOS v15.0                               3
Android v6.0 (Marshmallow)              2
Memory Card (Hybrid), upto 256 GB       2
Memory Card (Hybrid), upto 2 TB         2
HarmonyOS v2.0                          2
Android v5.1.1 (Lollipop)               2
Harmony v2.0                            2
Memory Card Supported, upto 256 GB      2
EMUI v12                                2
Android v12.1                           2
iOS v14.0                               2
HarmonyOS                               1
Memory Card Supported, upto 128 GB      1
Android v7.1 (Nougat)                   1
Hongmeng OS v4.0                        1
Android                                 1
Android v4.4.2 (KitKat)                 1
Memory Card (Hybrid)                    1
iOS v10                                 1
Pragati OS (Powered by Android)         1
Hongmeng OS v3.0                        1
Android v5.1 (Lollipop)                 1
iOS v17                                 1
iOS v12.3                               1
iOS v13.0                               1
HarmonyOS v2                            1
Not Specified                           1
Android v9 (Pie)                        1
Name: count, dtype: int64

In [129]:
def os_extractor(text):

  if 'Android' in text:
    return 'android'
  elif 'iOS' in text:
    return 'ios'
  elif 'Not Specified':
    return text
  elif 'Harmony' in text or 'Hongmeng' in text or 'EMUI' in text:
    return 'other'

In [130]:
df1['os'] = df1['os'].apply(os_extractor)

C:\Users\DEEL\AppData\Local\Temp\ipykernel_17040\2877873123.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df1['os'] = df1['os'].apply(os_extractor)

In [131]:
df1.drop(columns=['index','sim','processor','ram','battery','display','camera','card'])

     brand_name                                              model   price  \
0       oneplus                                      OnePlus 11 5G   54999
1       oneplus                          OnePlus Nord CE 2 Lite 5G   19989
2       samsung                              Samsung Galaxy A14 5G   16499
3      motorola                               Motorola Moto G62 5G   14999
4        realme                                 Realme 10 Pro Plus   24999
5       samsung            Samsung Galaxy F23 5G (6GB RAM + 128GB)   16999
6         apple                                    Apple iPhone 14   65999
7        xiaomi                      Xiaomi Redmi Note 12 Pro Plus   29999
8       nothing                                    Nothing Phone 1   26749
9       oneplus                                 OnePlus Nord 2T 5G   28999
10       realme                                      Realme 10 Pro   18999
11         oppo                                           Oppo A78   18999
12       xiaomi                        Xiaomi Redmi Note 12 Pro 5G   24762
13         vivo                       Vivo T1 5G (6GB RAM + 128GB)   16990
14      samsung                        Samsung Galaxy S23 Ultra 5G  114990
15        apple                                    Apple iPhone 13   62999
16         vivo                                           Vivo Y16    9999
17         oppo                               OPPO Reno 9 Pro Plus   45999
18      oneplus                                     OnePlus 10R 5G   32999
19         vivo                                           Vivo Y22   14499
20      oneplus                                        OnePlus 11R   39999
21         vivo                                    Vivo V25 Pro 5G   35999
22         poco                                     Poco X4 Pro 5G   14999
23       xiaomi                               Xiaomi Redmi Note 12   17859
24         vivo                                       Vivo V26 Pro   42990
25      samsung                           Samsung Galaxy S20 FE 5G   31239
26      oneplus        OnePlus Nord CE 2 Lite 5G (8GB RAM + 128GB)   21995
27        apple                            Apple iPhone 14 Pro Max  129990
28         vivo                                        Vivo V25 5G   27999
29      oneplus                                     OnePlus 11 Pro   69999
30       realme                    Realme 10 Pro (8GB RAM + 128GB)   19999
31         poco                                        Poco X5 Pro   20999
32         vivo                                           Vivo V27   27990
33        apple                                    Apple iPhone 11   38999
34      samsung                              Samsung Galaxy M53 5G   23790
35      samsung                           Samsung Galaxy S21 FE 5G   39999
36         oppo                                       Oppo Reno 8T   29990
37      samsung                        Samsung Galaxy S22 Ultra 5G   91999
38       xiaomi                    Xiaomi Redmi Note 12 Pro Max 5G   32999
39         oppo                                     OPPO Reno 9 5G   28499
40      oneplus                               OnePlus Nord CE 3 5G   21999
41       xiaomi                   Xiaomi Redmi Note 11 Pro Plus 5G   19999
42     motorola                         Motorola Edge 20 Fusion 5G   18999
43       realme               Realme 10 Pro Plus (8GB RAM + 256GB)   27999
44         vivo                                           Vivo Y35   18499
45      samsung                              Samsung Galaxy M33 5G   17478
46       xiaomi                               Xiaomi Redmi Note 11   11936
47       realme                                         Realme C33    8950
48         vivo                          Vivo Y16 (4GB RAM + 64GB)   12489
49      samsung                              Samsung Galaxy A74 5G   42999
50      samsung            Samsung Galaxy A14 5G (6GB RAM + 128GB)   18999
51         iqoo                                      iQOO Neo 7 5G   29999
52          jio                                    Jio JioPhone 5G   11990
53     motorola                               Motorola Moto G82 5G   18999
54       realme                                          Realme 10   13999
55       realme                                       Realme 9i 5G   14965
56        apple                               Apple iPhone 14 Plus   74999
57       xiaomi                              Xiaomi Redmi Note 10S   10999
58      samsung                            Samsung Galaxy S23 Plus   84990
59     motorola                                  Motorola Moto G32   10499
60       xiaomi                        Xiaomi Redmi Note 13 Pro 5G   17990
61         vivo                                           Vivo S16   29990
62      samsung                                 Samsung Galaxy A23   18499
63         vivo                         Vivo Y22 (6GB RAM + 128GB)   16499
64         poco                   Poco M4 Pro 5G (6GB RAM + 128GB)   14999
65         vivo                                       Vivo S16 Pro   35499
66      oneplus                                  OnePlus 10 Pro 5G   60999
67       xiaomi   Xiaomi Redmi Note 12 Pro Plus (12GB RAM + 256GB)   32999
68      samsung                              Samsung Galaxy F23 5G   15999
69         oppo                                   Oppo Find N Fold   99990
70         oppo                                          OPPO A17K    9499
71         vivo                     Vivo V23 5G (12GB RAM + 256GB)   27994
72         iqoo                                    iQOO Z6 Lite 5G   13989
73      oneplus                                        OnePlus 10T   44999
74       xiaomi          Xiaomi Redmi Note 10T 5G (6GB RAM +128GB)   13999
75       gionee                                     Gionee G13 Pro    6190
76        apple                                Apple iPhone 13 Pro  119900
77         oppo                                       OPPO F22 Pro   27660
78      samsung                              Samsung Galaxy A34 5G   24999
79       xiaomi                  Xiaomi Redmi 10A (4GB RAM + 64GB)    8388
80     motorola                               Motorola Moto G72 4G   15999
81      samsung            Samsung Galaxy A14 5G (8GB RAM + 128GB)   20999
82       realme                                        Realme 9 5G   13999
83         vivo                       Vivo T1 5G (8GB RAM + 128GB)   19990
84      samsung                              Samsung Galaxy M13 5G   13999
85     motorola                                Motorola Edge 30 5G   22999
86      samsung                              Samsung Galaxy A23 5G   22999
87         oppo                                        OPPO K10 5G   16999
88       xiaomi             Xiaomi Redmi Note 11 (6GB RAM + 128GB)   14290
89      samsung                              Samsung Galaxy A73 5G   41999
90         vivo                                      Vivo Y21 2021   13489
91      oneplus                      OnePlus Ace Racing Edition 5G   22990
92     motorola                Motorola Moto G62 (8GB RAM + 128GB)   16499
93         vivo                               Vivo X90 Pro Plus 5G   73999
94       realme                        Realme C33 (4GB RAM + 64GB)    9999
95       realme                                          Realme 9i   12499
96         oppo                                           OPPO A17   12499
97         iqoo                                         iQOO 11 5G   59999
98         vivo                                     Vivo X Fold 5G  106990
99         vivo                                         Vivo T1 5G   15990
100       apple                                Apple iPhone 14 Pro  119990
101      xiaomi                    Xiaomi Redmi Note 11 Pro Max 5G   19999
102    motorola                              Motorola Moto S30 Pro   23990
103      realme                                         Realme 10s   12999
104        oppo                               OPPO F19 Pro Plus 5G   19990
105      xiaomi                                   Xiaomi 13 Pro 5G   58990
106        vivo                                       Vivo V27 Pro   43999
107     samsung                              Samsung Galaxy S22 5G   49999
108        vivo                      Vivo T1 44W (6GB RAM + 128GB)   15999
109     oneplus                  OnePlus 10R 5G (12GB RAM + 256GB)   36999
110       tecno                                   Tecno Phantom X2   39999
111       apple                                    Apple iPhone 12   51999
112      xiaomi                               Xiaomi Redmi K50i 5G   22999
113     samsung                              Samsung Galaxy A53 5G   31999
114      xiaomi                                    Xiaomi Redmi A1    6171
115        oppo                                      OPPO Reno8 5G   29340
116     samsung            Samsung Galaxy M53 5G (8GB RAM + 128GB)   25289
117        iqoo                                     iQOO Z6 Pro 5G   21788
118       tesla                                     Tesla Pi Phone   69999
119     samsung                                 Samsung Galaxy S23   70990
120    motorola                            Motorola Edge 30 Pro 5G   34999
121     oneplus                 OnePlus Nord 2T (12GB RAM + 256GB)   33900
122      google                                    Google Pixel 6A   29999
123     infinix                             Infinix Note 12 Pro 5G   18999
124     samsung            Samsung Galaxy M33 5G (8GB RAM + 128GB)   19499
125        vivo                                        Vivo V23 5G   24994
126    motorola                                  Motorola Moto G42   10999
127     oneplus        OnePlus Nord CE 2 Lite 5G (8GB RAM + 256GB)   24999
128     samsung                              Samsung Galaxy A33 5G   25999
129      google                                    Google Pixel 7A   34990
130      xiaomi                           Xiaomi Redmi 11 Prime 5G   13466
131      xiaomi                          Xiaomi Redmi Note 10 Lite    9999
132    motorola                                  Motorola Moto E40    7999
133     nothing                  Nothing Phone 1 (8GB RAM + 256GB)   28249
134        poco                   Poco X4 Pro 5G (6GB RAM + 128GB)   16499
135      xiaomi  Xiaomi Redmi Note 11 Pro Plus 5G (8GB RAM + 25...   22999
136       apple                            Apple iPhone 11 (128GB)   46999
137      realme                       Realme C35 (6GB RAM + 128GB)   13999
138        oppo                                           OPPO K10   13490
139        iqoo                                      iQOO Neo 6 5G   28999
140        iqoo                                         iQOO Z6 5G   15499
141        oppo                                 OPPO Reno 9 Pro 5G   39999
142        poco                                     Poco M4 Pro 5G   12999
143         jio                                        Jio Phone 3    4499
144     oneplus                                     OnePlus Clover   14999
145     samsung                                 Samsung Galaxy F04    8499
146        iqoo                                             iQOO 7   24990
147     samsung                              Samsung Galaxy M34 5G   16999
148      xiaomi                                    Xiaomi Redmi 10    9589
149       apple                               Apple iPhone 12 Mini   40999
150      xiaomi             Xiaomi Redmi Note 12 (6GB RAM + 128GB)   19988
151    motorola                                  Motorola Moto G52   11999
152       apple                            Apple iPhone 15 Pro Max  142990
153        oppo                                           Oppo A98   30990
154     infinix                               Infinix Zero 5G 2023   19499
156      realme                                         Realme C30    5299
157        oppo                                    OPPO F21 Pro 5G   25969
158      realme                                      Realme 11 Pro   28999
159        oppo                                    Oppo Find N2 5G   94990
160      realme                                        Realme 9 4G   14999
161        cola                                         Cola Phone   14999
162       apple                            Apple iPhone 13 Pro Max  129900
163        oppo                              Oppo Reno 10 Pro Plus   58990
164        vivo                                        Vivo X90 5G   41990
165     samsung                                 Samsung Galaxy F13   10999
166      xiaomi            Xiaomi Redmi Note 10S (6GB RAM + 128GB)   11999
167      realme                        Realme 10 (8GB RAM + 128GB)   16999
168        iqoo                                       iQOO 9 SE 5G   30990
169     infinix                                     Infinix Hot 20   17999
170        letv                                        Letv Y1 Pro    5499
171      xiaomi                    Xiaomi Redmi Note 13 Pro Max 5G   20499
172      realme                             Realme Narzo 50 Pro 5G   20490
173        oppo                                        OPPO A74 5G   15490
174       apple                                     Apple iPhone 9   29990
175        iqoo                     iQOO Z6 Lite (6GB RAM + 128GB)   15499
176      xiaomi                             Xiaomi Redmi Note 11SE   11999
177      realme                                    Realme Narzo 50   10999
178        vivo                                        Vivo Y75 5G   21990
179        vivo                        Vivo V25 (12GB RAM + 256GB)   31999
180        poco                                     POCO M4 Pro 4G   11999
181     infinix                                 Infinix Zero Ultra   36999
182       tecno                                Tecno Spark Go 2023    6999
183    motorola                                  Motorola Moto X40   39999
184     samsung                              Samsung Galaxy F24 5G   14999
185      realme                                       Realme 10 5G   14499
186     oneplus                                  OnePlus Nord 3 5G   27999
187    motorola                Motorola Moto G82 (8GB RAM + 128GB)   20499
188       ikall                                      iKall Z19 Pro    8099
189       leeco                                       LeEco S1 Pro   10999
190      realme                                         Realme C2s    3499
191      duoqin                                     Duoqin F22 Pro    9990
192     samsung                              Samsung Galaxy M54 5G   34999
193       nokia                                       Nokia N73 5G   46999
194    motorola                         Motorola Edge 30 Fusion 5G   39999
195      realme                                         Realme C35   11828
196        oppo            OPPO Reno 8 Pro House of Dragon Edition   45999
197     oneplus                          OnePlus Nord CE 3 Lite 5G   18999
198        poco                   Poco X4 Pro 5G (8GB RAM + 128GB)   17999
199     samsung                                 Samsung Galaxy M04    8499
200        oppo                                          OPPO A77s   17999
201     samsung                                 Samsung Galaxy A13   14450
202    motorola                             Motorola Edge 30 Ultra   54999
203      xiaomi                                 Xiaomi 13 Ultra 5G   71999
204    motorola                Motorola Moto G52 (6GB RAM + 128GB)   12999
205        poco                                         Poco M4 5G   11499
206     nothing                 Nothing Phone 1 (12GB RAM + 256GB)   35999
207     samsung                              Samsung Galaxy A54 5G   34999
208       tecno                                       Tecno Pova 4   11999
209      xiaomi         Xiaomi Redmi Note 12 Pro (8GB RAM + 256GB)   27994
210       apple                    Apple iPhone 14 Pro Max (256GB)  139990
211        vivo                    Vivo V25 Pro (12GB RAM + 256GB)   39999
212      realme                      Realme 9 5G (6GB RAM + 128GB)   15499
213      realme                                    Realme 9 Pro 5G   18999
214        lava                                      Lava Blaze 5G   10999
215       honor                                          Honor X9a   27999
216      google                              Google Pixel 7 Pro 5G   81999
217       tecno                                       Tecno Pova 3    9999
218        vivo                                    Vivo V23 Pro 5G   31994
219     samsung                                Samsung Galaxy A04e    9299
220      xiaomi                                   Xiaomi Redmi K60   29990
221      realme                               Realme 9 Pro Plus 5G   25900
222      realme                     Realme 9i 5G (6GB RAM + 128GB)   16999
223    motorola              Motorola Edge 30 5G (8GB RAM + 128GB)   24999
224      xiaomi              Xiaomi Redmi Note 11 (6GB RAM + 64GB)   12188
225        vivo                                           Vivo Y02    8999
226        poco                          POCO C31 (4GB RAM + 64GB)    7499
227      realme                                 Realme Narzo 50 5G   17999
228      realme                                   Realme GT Neo 3T   24999
229        oppo                                 OPPO Reno 8 Pro 5G   45999
230     oneplus               OnePlus 10 Pro 5G (12GB RAM + 256GB)   65499
231        iqoo                                     iQOO 11 Pro 5G   58990
232        vivo                                        Vivo T1x 4G   11999
233      xiaomi                              Xiaomi Redmi 10 Power   11999
234        oppo                                           OPPO A58   18990
235        vivo                                        Vivo T1 44W   14499
236      xiaomi                               Xiaomi Mix Fold 2 5G  106990
237        vivo                          Vivo Y16 (3GB RAM + 64GB)   10499
238        oppo                                      OPPO Reno 8 Z   26990
239        vivo                                        Vivo Y75 4G   19990
240      xiaomi                      Xiaomi Redmi Note 12 Explorer   24999
241        oppo                      OPPO A57 4G (4GB RAM + 64 GB)   13969
242     samsung                              Samsung Galaxy A75 5G   44999
243        vivo                   Vivo T1 Pro 5G (8GB RAM + 128GB)   24999
244      google                                  Google Pixel 7 5G   53100
245      xiaomi         Xiaomi Redmi Note 11T 5G (6GB RAM + 128GB)   16999
246        oppo                                   OPPO F21s Pro 4G   21899
247       apple                            Apple iPhone 14 (256GB)   75999
248    motorola                                  Motorola Moto G73   25999
249       nubia                           Nubia Red Magic 8 Pro 5G   46990
250    motorola                                  Motorola Moto G31    9999
251       tecno                               Tecno Phantom X2 Pro   49999
252     infinix                                    Infinix Zero 20   17999
253        iqoo                       iQOO Z6 5G (6GB RAM + 128GB)   16940
254      xiaomi                        Xiaomi Redmi Note 11 Pro 5G   17990
255        oppo                                        OPPO A1 Pro   20990
256     samsung                           Samsung Galaxy S22 FE 5G   51999
257     samsung                         Samsung Galaxy S22 Plus 5G   64449
258        vivo                                           Vivo U3x    8990
259    motorola                                  Motorola Moto G23   19999
260        poco                       Poco M4 5G (6GB RAM + 128GB)   13499
261       tecno                                      Tecno Pova 5G   15499
262        poco                                           POCO C31    6499
263       apple                                   Apple iPhone XR2   71999
264     samsung               Samsung Galaxy A53 (8GB RAM + 256GB)   36499
265     infinix                                 Infinix Note 12 5G   15999

In [132]:
export_df = df1.drop(columns=['index','sim','processor','ram','battery','display','camera','card'])

In [133]:
export_df.to_csv('smartphone_cleaned_v2.csv',index=False)

In [134]:
df1.shape

(980, 33)

In [135]:
df1.columns

Index(['index', 'brand_name', 'model', 'price', 'rating', 'sim', 'has_5g',
       'has_nfc', 'has_ir_blaster', 'processor', 'processor_name',
       'processor_brand', 'num_cores', 'processor_speed', 'ram', 'battery',
       'fast_charging ', 'battery_capacity', 'fast_charging', 'ram_capacity',
       'internal_memory', 'screen_size', 'refresh_rate', 'resolution',
       'display', 'num_rear_cameras', 'num_front_cameras', 'camera', 'card',
       'os', 'primary_camera_rear', 'primary_camera_front', 'extended_memory'],
      dtype='object')

In [136]:
export_df.head()

,brand_name,model,price,rating,has_5g,has_nfc,has_ir_blaster,processor_name,processor_brand,num_cores,processor_speed,fast_charging,battery_capacity,fast_charging,ram_capacity,internal_memory,screen_size,refresh_rate,resolution,num_rear_cameras,num_front_cameras,os,primary_camera_rear,primary_camera_front,extended_memory
0,oneplus,OnePlus 11 5G,54999,89.0,True,True,False,Snapdragon 8 Gen2,Snapdragon,Octa Core,3.2,[100],5000.0,100,12.0,256.0,6.70,120,1440 x 3216,3,1,android,50,16,0
1,oneplus,OnePlus Nord CE 2 Lite 5G,19989,81.0,True,False,False,Snapdragon 695,Snapdragon,Octa Core,2.2,[33],5000.0,33,6.0,128.0,6.59,120,1080 x 2412,3,1,android,64,16,1 TB
2,samsung,Samsung Galaxy A14 5G,16499,75.0,True,False,False,Exynos 1330,Exynos,Octa Core,2.4,[15],5000.0,15,4.0,64.0,6.60,90,1080 x 2408,3,1,android,50,13,1 TB
3,motorola,Motorola Moto G62 5G,14999,81.0,True,False,False,Snapdragon 695,Snapdragon,Octa Core,2.2,[],5000.0,0,6.0,128.0,6.55,120,1080 x 2400,3,1,android,50,16,1 TB
4,realme,Realme 10 Pro Plus,24999,82.0,True,False,False,Dimensity 1080,Dimensity,Octa Core,2.6,[67],5000.0,67,6.0,128.0,6.70,120,1080 x 2412,3,1,android,108,16,0

In [137]:
export_df.shape

(980, 25)